import type { CourseSeed } from '../types';

/**
 * A0 — At Home.
 *
 * Family, toys, food/drink basics, day/night, daily verbs.
 * Closes out the A0 ladder before A1.
 */
export const a0AtHome: CourseSeed = {
  slug: 'a0-at-home',
  createIfMissing: {
    title: 'At Home',
    titleUa: 'Вдома',
    subtitle: 'A0 · 5 уроків · стартовий рівень',
    description:
      'Знайома обстановка для перших слів: рідні, іграшки, їжа, день і ніч, прості дії. До кінця курсу ти готовий перейти на рівень A1.',
    descriptionShort:
      'Сімʼя, іграшки, їжа, день і ніч.',
    level: 'A0',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '🏠',
    tags: ['kids', 'a0', 'home', 'family'],
  },
  lessons: [
    {
      slug: 'a0-mom-dad-family',
      title: 'Mom, Dad, Family',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'home',
      sectionTitle: 'Юніт 1 · Дім',
      sectionOrder: 0,
      isFree: true,
      topic: 'family',
      steps: [
        {
          id: 'a0-fam-theory',
          type: 'theory',
          title: 'Моя родина 👨‍👩‍👧',
          body: 'Найрідніші люди: мама, тато, брат, сестра. Слово «my» = «мій / моя».',
          examples: [
            { en: 'mom', ua: 'мама' },
            { en: 'dad', ua: 'тато' },
            { en: 'sister', ua: 'сестра' },
            { en: 'brother', ua: 'брат' },
            { en: 'baby', ua: 'малюк' },
            { en: 'my mom', ua: 'моя мама' },
          ],
        },
        {
          id: 'a0-fam-mc1',
          type: 'multiple-choice',
          question: '«Brother» — це…',
          options: ['сестра', 'тато', 'брат', 'мама'],
          correctIndex: 2,
        },
        {
          id: 'a0-fam-mc2',
          type: 'multiple-choice',
          question: 'Як сказати «моя мама»?',
          options: ['mom my', 'my mom', 'I mom', 'me mom'],
          correctIndex: 1,
        },
        {
          id: 'a0-fam-fill',
          type: 'fill-blank',
          before: 'This is my',
          after: '. She is six.',
          answer: 'sister',
          hint: 'Дівчинка-родичка.',
        },
        {
          id: 'a0-fam-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'mom', right: 'мама' },
            { left: 'dad', right: 'тато' },
            { left: 'sister', right: 'сестра' },
            { left: 'brother', right: 'брат' },
            { left: 'baby', right: 'малюк' },
          ],
        },
        {
          id: 'a0-fam-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це мій тато.',
          answer: 'This is my dad.',
          acceptedAnswers: [
            'this is my dad',
            'This is my dad',
            'this is my dad.',
            'this is my father',
          ],
        },
      ],
    },

    {
      slug: 'a0-my-toys',
      title: 'My Toys',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'home',
      sectionTitle: 'Юніт 1 · Дім',
      sectionOrder: 0,
      topic: 'toys',
      steps: [
        {
          id: 'a0-toys-theory',
          type: 'theory',
          title: 'Іграшки 🧸',
          body: 'Розкажи, що в тебе є. «I have a teddy bear» = «У мене є плюшевий ведмедик».',
          examples: [
            { en: 'a ball', ua: 'мʼяч' },
            { en: 'a doll', ua: 'лялька' },
            { en: 'a car', ua: 'машинка' },
            { en: 'a teddy bear', ua: 'плюшевий ведмедик' },
            { en: 'a robot', ua: 'робот' },
            { en: 'I have a ball.', ua: 'У мене є мʼяч.' },
          ],
          tip: '💡 «A» ставимо перед іменником, який починається з приголосного.',
        },
        {
          id: 'a0-toys-mc1',
          type: 'multiple-choice',
          question: '«Doll» — це…',
          options: ['мʼяч', 'лялька', 'машинка', 'робот'],
          correctIndex: 1,
        },
        {
          id: 'a0-toys-mc2',
          type: 'multiple-choice',
          question: '«У мене є машинка» — це…',
          options: [
            'I have car',
            'I have a car',
            'My car is',
            'A car I have',
          ],
          correctIndex: 1,
        },
        {
          id: 'a0-toys-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' a teddy bear.',
          answer: 'have',
          hint: 'Дієслово «маю».',
        },
        {
          id: 'a0-toys-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'ball', right: 'мʼяч' },
            { left: 'doll', right: 'лялька' },
            { left: 'car', right: 'машинка' },
            { left: 'robot', right: 'робот' },
          ],
        },
        {
          id: 'a0-toys-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене є мʼяч.',
          words: ['ball', 'I', 'a', 'have'],
          answer: ['I', 'have', 'a', 'ball'],
        },
      ],
    },

    {
      slug: 'a0-eat-drink',
      title: 'Eat & Drink',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'home',
      sectionTitle: 'Юніт 1 · Дім',
      sectionOrder: 0,
      topic: 'food',
      steps: [
        {
          id: 'a0-ed-theory',
          type: 'theory',
          title: 'Їжа й напої 🍎',
          body: 'Найпростіше: яблуко, хліб, вода, молоко. «I want…» = «Я хочу…», «I like…» = «Мені подобається…».',
          examples: [
            { en: 'apple', ua: 'яблуко' },
            { en: 'bread', ua: 'хліб' },
            { en: 'water', ua: 'вода' },
            { en: 'milk', ua: 'молоко' },
            { en: 'I want water.', ua: 'Я хочу води.' },
            { en: 'I like apples.', ua: 'Мені подобаються яблука.' },
          ],
        },
        {
          id: 'a0-ed-mc1',
          type: 'multiple-choice',
          question: '«Apple» — це…',
          options: ['банан', 'яблуко', 'хліб', 'вода'],
          correctIndex: 1,
        },
        {
          id: 'a0-ed-mc2',
          type: 'multiple-choice',
          question: '«Я хочу води» — це…',
          options: [
            'I water',
            'Water I want',
            'I want water',
            'I drink water',
          ],
          correctIndex: 2,
        },
        {
          id: 'a0-ed-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' apples.',
          answer: 'like',
          hint: 'Дієслово «мені подобається».',
        },
        {
          id: 'a0-ed-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'apple', right: 'яблуко' },
            { left: 'bread', right: 'хліб' },
            { left: 'water', right: 'вода' },
            { left: 'milk', right: 'молоко' },
          ],
        },
        {
          id: 'a0-ed-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мені подобається молоко.',
          answer: 'I like milk.',
          acceptedAnswers: ['i like milk', 'I like milk', 'i like milk.'],
        },
      ],
    },

    {
      slug: 'a0-day-night',
      title: 'Day & Night',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'time',
      sectionTitle: 'Юніт 2 · Час дня',
      sectionOrder: 1,
      topic: 'time',
      steps: [
        {
          id: 'a0-dn-theory',
          type: 'theory',
          title: 'День і ніч 🌞🌙',
          body: 'Привітання залежить від часу: «Good morning» — вранці, «Good afternoon» — вдень, «Good evening» — увечері, «Good night» — на ніч.',
          examples: [
            { en: 'morning', ua: 'ранок' },
            { en: 'afternoon', ua: 'після обіду' },
            { en: 'evening', ua: 'вечір' },
            { en: 'night', ua: 'ніч' },
            { en: 'Good morning!', ua: 'Доброго ранку!' },
            { en: 'Good night!', ua: 'На добраніч!' },
          ],
        },
        {
          id: 'a0-dn-mc1',
          type: 'multiple-choice',
          question: 'Що сказати о 8-й ранку?',
          options: ['Good night', 'Good evening', 'Good morning', 'Good afternoon'],
          correctIndex: 2,
        },
        {
          id: 'a0-dn-mc2',
          type: 'multiple-choice',
          question: 'А перед сном?',
          options: ['Good night', 'Good morning', 'Good afternoon', 'Good day'],
          correctIndex: 0,
        },
        {
          id: 'a0-dn-fill',
          type: 'fill-blank',
          before: 'Good ',
          after: '! Time for school.',
          answer: 'morning',
          hint: 'Час сонячний, але сніданок ще теплий.',
        },
        {
          id: 'a0-dn-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'morning', right: 'ранок' },
            { left: 'afternoon', right: 'після обіду' },
            { left: 'evening', right: 'вечір' },
            { left: 'night', right: 'ніч' },
          ],
        },
        {
          id: 'a0-dn-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'На добраніч!',
          answer: 'Good night!',
          acceptedAnswers: ['good night', 'Good night', 'good night!'],
        },
      ],
    },

    {
      slug: 'a0-sleep-wash-eat',
      title: 'Sleep, Wash, Eat',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'time',
      sectionTitle: 'Юніт 2 · Час дня',
      sectionOrder: 1,
      topic: 'verbs',
      steps: [
        {
          id: 'a0-swe-theory',
          type: 'theory',
          title: 'Прості дії 🛏️',
          body: 'Кожен день ми робимо однакові речі: спимо, миємось, їмо. У теперішньому часі (з «I») — без жодних змін у дієслові.',
          examples: [
            { en: 'I sleep.', ua: 'Я сплю.' },
            { en: 'I wash.', ua: 'Я мию.' },
            { en: 'I eat.', ua: 'Я їм.' },
            { en: 'I drink.', ua: 'Я пʼю.' },
            { en: 'I play.', ua: 'Я граю.' },
          ],
          tip: '💡 «I» завжди з великої — навіть посеред речення.',
        },
        {
          id: 'a0-swe-mc1',
          type: 'multiple-choice',
          question: '«Eat» — це…',
          options: ['спати', 'мити', 'їсти', 'пити'],
          correctIndex: 2,
        },
        {
          id: 'a0-swe-mc2',
          type: 'multiple-choice',
          question: 'А «drink»?',
          options: ['пити', 'танцювати', 'спати', 'співати'],
          correctIndex: 0,
        },
        {
          id: 'a0-swe-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' at night.',
          answer: 'sleep',
          hint: 'Що ми робимо вночі?',
        },
        {
          id: 'a0-swe-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'sleep', right: 'спати' },
            { left: 'eat', right: 'їсти' },
            { left: 'drink', right: 'пити' },
            { left: 'play', right: 'грати' },
            { left: 'wash', right: 'мити' },
          ],
        },
        {
          id: 'a0-swe-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я граю з мʼячем.',
          words: ['ball', 'I', 'with', 'a', 'play'],
          answer: ['I', 'play', 'with', 'a', 'ball'],
        },
      ],
    },
  ],
};
