import type { CourseSeed } from '../types';

/**
 * A0 — First English Words.
 *
 * Total beginner. Greetings, names, yes/no, numbers 1–10, basic colors.
 * 5 lessons × 6–7 steps. First 3 lessons are free so a brand-new kid can
 * sample the platform without paying.
 */
export const a0FirstWords: CourseSeed = {
  slug: 'a0-first-words',
  createIfMissing: {
    title: 'First English Words',
    titleUa: 'Перші англійські слова',
    subtitle: 'A0 · 5 уроків · стартовий рівень',
    description:
      'Найперше знайомство з англійською мовою. Вітання, імʼя, числа 1–10, кольори. Уроки короткі та теплі — ідеально для дітей, які тільки починають.',
    descriptionShort:
      'Перший контакт з англійською: вітання, імʼя, числа, кольори.',
    level: 'A0',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '🌱',
    tags: ['kids', 'a0', 'starter', 'vocabulary'],
  },
  lessons: [
    // ─── 1. Hello & Goodbye ────────────────────────────────────────────
    {
      slug: 'a0-hello-goodbye',
      title: 'Hello & Goodbye',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'first-contact',
      sectionTitle: 'Юніт 1 · Перший контакт',
      sectionOrder: 0,
      isFree: true,
      topic: 'greetings',
      steps: [
        {
          id: 'a0-hg-theory',
          type: 'theory',
          title: 'Перші слова 👋',
          body: 'Коли зустрічаєш когось — кажеш «Hello». Коли йдеш — кажеш «Goodbye». Це найперші слова, які знають усі англомовні діти.',
          examples: [
            { en: 'Hello!', ua: 'Привіт!' },
            { en: 'Hi!', ua: 'Привіт! (коротко)' },
            { en: 'Goodbye!', ua: 'До побачення!' },
            { en: 'Bye!', ua: 'Бувай!' },
          ],
          tip: '💡 «Hi» — коротше і дружнє, «Hello» — нейтральне.',
        },
        {
          id: 'a0-hg-mc1',
          type: 'multiple-choice',
          question: 'Як сказати «Привіт» англійською?',
          options: ['Goodbye', 'Hello', 'Yes', 'Cat'],
          correctIndex: 1,
        },
        {
          id: 'a0-hg-mc2',
          type: 'multiple-choice',
          question: 'А що означає «Goodbye»?',
          options: ['Привіт', 'Дякую', 'До побачення', 'Так'],
          correctIndex: 2,
        },
        {
          id: 'a0-hg-fill',
          type: 'fill-blank',
          before: 'A: Hi! B:',
          after: '! How are you?',
          answer: 'Hello',
          hint: 'Привітайся у відповідь — повним словом.',
        },
        {
          id: 'a0-hg-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай слово з перекладом:',
          pairs: [
            { left: 'Hello', right: 'Привіт' },
            { left: 'Goodbye', right: 'До побачення' },
            { left: 'Hi', right: 'Привіт (коротко)' },
            { left: 'Bye', right: 'Бувай' },
          ],
        },
        {
          id: 'a0-hg-translate',
          type: 'translate',
          prompt: 'Переклади англійською:',
          sentence: 'Привіт!',
          answer: 'Hello!',
          acceptedAnswers: ['hello!', 'Hello', 'hello', 'Hi!', 'Hi', 'hi!', 'hi'],
        },
      ],
    },

    // ─── 2. What's Your Name? ──────────────────────────────────────────
    {
      slug: 'a0-whats-your-name',
      title: "What's Your Name?",
      orderIndex: 1,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'first-contact',
      sectionTitle: 'Юніт 1 · Перший контакт',
      sectionOrder: 0,
      isFree: true,
      topic: 'introductions',
      steps: [
        {
          id: 'a0-name-theory',
          type: 'theory',
          title: 'Як тебе звати? 🙋',
          body: 'Щоб познайомитись, питають «What\'s your name?». Ти відповідаєш «My name is …» або «I am …».',
          examples: [
            { en: "What's your name?", ua: 'Як тебе звати?' },
            { en: 'My name is Sofia.', ua: 'Мене звати Софія.' },
            { en: 'I am Max.', ua: 'Я Макс.' },
            { en: 'Nice to meet you!', ua: 'Приємно познайомитись!' },
          ],
          tip: '💡 «I am» можна скоротити: «I\'m».',
        },
        {
          id: 'a0-name-mc1',
          type: 'multiple-choice',
          question: 'Як спитати імʼя?',
          options: [
            'How old are you?',
            "What's your name?",
            'How are you?',
            'Where are you?',
          ],
          correctIndex: 1,
        },
        {
          id: 'a0-name-mc2',
          type: 'multiple-choice',
          question: 'Що означає «My name is Sofia»?',
          options: [
            'Я люблю Софію',
            'Софія — мій друг',
            'Мене звати Софія',
            'Це Софія',
          ],
          correctIndex: 2,
        },
        {
          id: 'a0-name-fill',
          type: 'fill-blank',
          before: 'My',
          after: ' is Anna.',
          answer: 'name',
          hint: 'Те, що в нас питають — як нас ____.',
        },
        {
          id: 'a0-name-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Мене звати Том.',
          words: ['name', 'My', 'is', 'Tom'],
          answer: ['My', 'name', 'is', 'Tom'],
        },
        {
          id: 'a0-name-translate',
          type: 'translate',
          prompt: 'Переклади англійською:',
          sentence: 'Мене звати Анна.',
          answer: 'My name is Anna.',
          acceptedAnswers: [
            'my name is anna',
            'My name is Anna',
            'my name is anna.',
            "I'm Anna",
            'I am Anna',
            'i am anna',
          ],
        },
      ],
    },

    // ─── 3. Yes & No ───────────────────────────────────────────────────
    {
      slug: 'a0-yes-no',
      title: 'Yes & No',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'first-contact',
      sectionTitle: 'Юніт 1 · Перший контакт',
      sectionOrder: 0,
      isFree: true,
      topic: 'basics',
      steps: [
        {
          id: 'a0-yn-theory',
          type: 'theory',
          title: 'Так чи ні? ✅',
          body: 'Дві найкорисніші відповіді — «Yes» та «No». Додавай до них «please» (будь ласка) і «thank you» (дякую) — і ти вже ввічливий!',
          examples: [
            { en: 'Yes', ua: 'Так' },
            { en: 'No', ua: 'Ні' },
            { en: 'Please', ua: 'Будь ласка' },
            { en: 'Thank you', ua: 'Дякую' },
            { en: 'Sorry', ua: 'Вибач' },
          ],
        },
        {
          id: 'a0-yn-mc1',
          type: 'multiple-choice',
          question: '«Будь ласка» — це…',
          options: ['Sorry', 'Yes', 'Please', 'No'],
          correctIndex: 2,
        },
        {
          id: 'a0-yn-mc2',
          type: 'multiple-choice',
          question: 'Як подякувати?',
          options: ['Hello', 'Thank you', 'Goodbye', 'Yes'],
          correctIndex: 1,
        },
        {
          id: 'a0-yn-fill',
          type: 'fill-blank',
          before: 'Can I have an apple,',
          after: '?',
          answer: 'please',
          hint: 'Ввічливе слівце.',
        },
        {
          id: 'a0-yn-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'Yes', right: 'Так' },
            { left: 'No', right: 'Ні' },
            { left: 'Please', right: 'Будь ласка' },
            { left: 'Thank you', right: 'Дякую' },
            { left: 'Sorry', right: 'Вибач' },
          ],
        },
        {
          id: 'a0-yn-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Так, дякую!',
          answer: 'Yes, thank you!',
          acceptedAnswers: [
            'yes, thank you',
            'Yes, thank you',
            'yes thank you',
            'Yes thanks',
            'yes, thanks',
            'yes thanks',
          ],
        },
      ],
    },

    // ─── 4. Numbers 1–10 ───────────────────────────────────────────────
    {
      slug: 'a0-numbers-1-10',
      title: 'Numbers 1–10',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'colors-and-numbers',
      sectionTitle: 'Юніт 2 · Кольори та числа',
      sectionOrder: 1,
      topic: 'numbers',
      steps: [
        {
          id: 'a0-num-theory',
          type: 'theory',
          title: 'Рахуємо до десяти 🔢',
          body: 'Числа — це фундамент. Один — «one», два — «two». Спробуй вимовити їх вголос разом з прикладами!',
          examples: [
            { en: 'one', ua: '1' },
            { en: 'two', ua: '2' },
            { en: 'three', ua: '3' },
            { en: 'four', ua: '4' },
            { en: 'five', ua: '5' },
            { en: 'six', ua: '6' },
            { en: 'seven', ua: '7' },
            { en: 'eight', ua: '8' },
            { en: 'nine', ua: '9' },
            { en: 'ten', ua: '10' },
          ],
          tip: '💡 «Eight» вимовляється як «ейт» — буква «h» не читається.',
        },
        {
          id: 'a0-num-mc1',
          type: 'multiple-choice',
          question: 'Що таке «five»?',
          options: ['3', '4', '5', '6'],
          correctIndex: 2,
        },
        {
          id: 'a0-num-mc2',
          type: 'multiple-choice',
          question: 'Як написати число «8» англійською?',
          options: ['ate', 'eight', 'eit', 'eitt'],
          correctIndex: 1,
        },
        {
          id: 'a0-num-fill',
          type: 'fill-blank',
          before: 'I have',
          after: ' apples.',
          answer: 'three',
          hint: 'Число 3.',
        },
        {
          id: 'a0-num-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай число з цифрою:',
          pairs: [
            { left: 'one', right: '1' },
            { left: 'three', right: '3' },
            { left: 'seven', right: '7' },
            { left: 'ten', right: '10' },
          ],
        },
        {
          id: 'a0-num-order',
          type: 'word-order',
          prompt: 'Склади число (з літер):',
          translation: 'six',
          words: ['s', 'i', 'x'],
          answer: ['s', 'i', 'x'],
        },
      ],
    },

    // ─── 5. Colors I Know ──────────────────────────────────────────────
    {
      slug: 'a0-colors',
      title: 'Colors I Know',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'colors-and-numbers',
      sectionTitle: 'Юніт 2 · Кольори та числа',
      sectionOrder: 1,
      topic: 'colors',
      steps: [
        {
          id: 'a0-col-theory',
          type: 'theory',
          title: 'Усе у кольорах 🌈',
          body: 'Щоб описати річ, кажуть «It is red» або «The cat is black». Слово «is» означає «є».',
          examples: [
            { en: 'red', ua: 'червоний' },
            { en: 'blue', ua: 'синій' },
            { en: 'yellow', ua: 'жовтий' },
            { en: 'green', ua: 'зелений' },
            { en: 'black', ua: 'чорний' },
            { en: 'white', ua: 'білий' },
            { en: 'orange', ua: 'оранжевий' },
            { en: 'pink', ua: 'рожевий' },
          ],
        },
        {
          id: 'a0-col-mc1',
          type: 'multiple-choice',
          question: 'Колір сонця:',
          options: ['blue', 'yellow', 'black', 'green'],
          correctIndex: 1,
        },
        {
          id: 'a0-col-mc2',
          type: 'multiple-choice',
          question: 'А кавун всередині якого кольору?',
          options: ['white', 'red', 'pink', 'green'],
          correctIndex: 1,
        },
        {
          id: 'a0-col-fill',
          type: 'fill-blank',
          before: 'Grass is',
          after: '.',
          answer: 'green',
          hint: 'Колір трави.',
        },
        {
          id: 'a0-col-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай кольори:',
          pairs: [
            { left: 'red', right: 'червоний' },
            { left: 'blue', right: 'синій' },
            { left: 'yellow', right: 'жовтий' },
            { left: 'black', right: 'чорний' },
            { left: 'pink', right: 'рожевий' },
          ],
        },
        {
          id: 'a0-col-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Небо синє.',
          answer: 'The sky is blue.',
          acceptedAnswers: [
            'the sky is blue',
            'The sky is blue',
            'the sky is blue.',
            'sky is blue',
            'Sky is blue.',
          ],
        },
      ],
    },
  ],
};
