import type { CourseSeed } from '../types';

/**
 * A0 — My Body.
 *
 * Body parts, simple imperatives, opposites (big/small), basic "I can".
 * 5 lessons × 6–7 steps. First lesson is free.
 */
export const a0MyBody: CourseSeed = {
  slug: 'a0-my-body',
  createIfMissing: {
    title: 'My Body',
    titleUa: 'Моє тіло',
    subtitle: 'A0 · 5 уроків · стартовий рівень',
    description:
      'Перші слова про себе: голова, руки, ноги, обличчя. Вчимось виконувати команди («Touch your nose»), порівнювати («big / small») і казати, що ми можемо («I can see»).',
    descriptionShort:
      'Частини тіла, прості команди, «I can…».',
    level: 'A0',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '👋',
    tags: ['kids', 'a0', 'body', 'commands'],
  },
  lessons: [
    // ─── 1. Head, Hands, Feet ──────────────────────────────────────────
    {
      slug: 'a0-head-hands-feet',
      title: 'Head, Hands, Feet',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'body-basics',
      sectionTitle: 'Юніт 1 · Тіло',
      sectionOrder: 0,
      isFree: true,
      topic: 'body',
      steps: [
        {
          id: 'a0-hhf-theory',
          type: 'theory',
          title: 'Частини тіла 🧍',
          body: 'Це найкорисніші слова: голова, рука, нога. З ними ти зможеш виконувати команди вчителя.',
          examples: [
            { en: 'head', ua: 'голова' },
            { en: 'hand', ua: 'рука (кисть)' },
            { en: 'arm', ua: 'рука (вся)' },
            { en: 'foot', ua: 'ступня' },
            { en: 'leg', ua: 'нога' },
            { en: 'body', ua: 'тіло' },
          ],
          tip: '💡 «Hand» — це кисть, «arm» — від плеча до кисті.',
        },
        {
          id: 'a0-hhf-mc1',
          type: 'multiple-choice',
          question: 'Що таке «head»?',
          options: ['нога', 'голова', 'рука', 'спина'],
          correctIndex: 1,
        },
        {
          id: 'a0-hhf-mc2',
          type: 'multiple-choice',
          question: 'А «foot»?',
          options: ['ступня', 'кисть', 'голова', 'плече'],
          correctIndex: 0,
        },
        {
          id: 'a0-hhf-fill',
          type: 'fill-blank',
          before: 'I have two',
          after: 's and two legs.',
          answer: 'arm',
          hint: 'Рука цілком (від плеча).',
        },
        {
          id: 'a0-hhf-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'head', right: 'голова' },
            { left: 'hand', right: 'кисть' },
            { left: 'leg', right: 'нога' },
            { left: 'foot', right: 'ступня' },
            { left: 'body', right: 'тіло' },
          ],
        },
        {
          id: 'a0-hhf-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене дві ноги.',
          words: ['have', 'I', 'two', 'legs'],
          answer: ['I', 'have', 'two', 'legs'],
        },
      ],
    },

    // ─── 2. Touch Your Nose! ───────────────────────────────────────────
    {
      slug: 'a0-touch-your-nose',
      title: 'Touch Your Nose!',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'body-basics',
      sectionTitle: 'Юніт 1 · Тіло',
      sectionOrder: 0,
      topic: 'commands',
      steps: [
        {
          id: 'a0-cmd-theory',
          type: 'theory',
          title: 'Прості команди ✋',
          body: 'Команди — це коли тебе просять щось зробити. Зазвичай вчитель каже «Touch...» (доторкнись) або «Show me...» (покажи мені).',
          examples: [
            { en: 'Touch your nose.', ua: 'Доторкнись до носа.' },
            { en: 'Show me your hand.', ua: 'Покажи мені руку.' },
            { en: 'Stand up.', ua: 'Встань.' },
            { en: 'Sit down.', ua: 'Сядь.' },
            { en: 'Open your eyes.', ua: 'Відкрий очі.' },
          ],
        },
        {
          id: 'a0-cmd-mc1',
          type: 'multiple-choice',
          question: '«Stand up» означає…',
          options: ['Сядь', 'Підніми руки', 'Встань', 'Закрий очі'],
          correctIndex: 2,
        },
        {
          id: 'a0-cmd-mc2',
          type: 'multiple-choice',
          question: 'Що сказати, коли хочеш сказати «Сядь»?',
          options: ['Sit down', 'Stand up', 'Wake up', 'Show me'],
          correctIndex: 0,
        },
        {
          id: 'a0-cmd-fill',
          type: 'fill-blank',
          before: '',
          after: ' your hand!',
          answer: 'Show',
          hint: 'З великої літери на початку речення.',
        },
        {
          id: 'a0-cmd-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'Stand up', right: 'Встань' },
            { left: 'Sit down', right: 'Сядь' },
            { left: 'Touch', right: 'Доторкнись' },
            { left: 'Show me', right: 'Покажи мені' },
          ],
        },
        {
          id: 'a0-cmd-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Доторкнись до голови.',
          answer: 'Touch your head.',
          acceptedAnswers: [
            'touch your head',
            'Touch your head',
            'touch your head.',
            'touch the head',
          ],
        },
      ],
    },

    // ─── 3. Big & Small ───────────────────────────────────────────────
    {
      slug: 'a0-big-small',
      title: 'Big & Small',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 6,
      xp: 15,
      sectionSlug: 'descriptions',
      sectionTitle: 'Юніт 2 · Опис',
      sectionOrder: 1,
      topic: 'adjectives',
      steps: [
        {
          id: 'a0-bs-theory',
          type: 'theory',
          title: 'Великий чи малий? 📏',
          body: 'Тепер опишемо речі. Слон — «big». Миша — «small». Слово ставимо ПЕРЕД іменником: «a big elephant».',
          examples: [
            { en: 'big', ua: 'великий' },
            { en: 'small', ua: 'маленький' },
            { en: 'tall', ua: 'високий' },
            { en: 'short', ua: 'низький / короткий' },
            { en: 'a big dog', ua: 'великий собака' },
            { en: 'a small cat', ua: 'маленький кіт' },
          ],
          tip: '💡 «Tall» — про зріст. «Short» — короткий або низький.',
        },
        {
          id: 'a0-bs-mc1',
          type: 'multiple-choice',
          question: 'Слон — який?',
          options: ['small', 'big', 'short', 'pink'],
          correctIndex: 1,
        },
        {
          id: 'a0-bs-mc2',
          type: 'multiple-choice',
          question: '«Маленький кіт» — це…',
          options: ['big cat', 'tall cat', 'small cat', 'short cat'],
          correctIndex: 2,
        },
        {
          id: 'a0-bs-fill',
          type: 'fill-blank',
          before: 'A mouse is',
          after: '.',
          answer: 'small',
          hint: 'Миша яка?',
        },
        {
          id: 'a0-bs-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай протилежності:',
          pairs: [
            { left: 'big', right: 'small' },
            { left: 'tall', right: 'short' },
            { left: 'yes', right: 'no' },
            { left: 'hello', right: 'goodbye' },
          ],
        },
        {
          id: 'a0-bs-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене маленький собака.',
          words: ['small', 'I', 'have', 'a', 'dog'],
          answer: ['I', 'have', 'a', 'small', 'dog'],
        },
      ],
    },

    // ─── 4. I Can See / I Can Hear ────────────────────────────────────
    {
      slug: 'a0-i-can',
      title: 'I Can See / I Can Hear',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'descriptions',
      sectionTitle: 'Юніт 2 · Опис',
      sectionOrder: 1,
      topic: 'modals',
      steps: [
        {
          id: 'a0-ican-theory',
          type: 'theory',
          title: 'Я можу… 👁️',
          body: 'Слово «can» означає «можу». Воно стоїть перед дієсловом: «I can see» = «Я бачу / Я можу бачити».',
          examples: [
            { en: 'I can see.', ua: 'Я бачу.' },
            { en: 'I can hear.', ua: 'Я чую.' },
            { en: 'I can run.', ua: 'Я можу бігати.' },
            { en: 'I can jump.', ua: 'Я можу стрибати.' },
            { en: "I can't fly.", ua: 'Я не можу літати.' },
          ],
          tip: '💡 «Can\'t» — скорочення від «cannot» (не можу).',
        },
        {
          id: 'a0-ican-mc1',
          type: 'multiple-choice',
          question: 'Що означає «I can run»?',
          options: ['Я люблю бігати', 'Я можу бігати', 'Я не біжу', 'Я бігаю зараз'],
          correctIndex: 1,
        },
        {
          id: 'a0-ican-mc2',
          type: 'multiple-choice',
          question: 'А «I can\'t fly» — це…',
          options: ['Я літаю', 'Я можу літати', 'Я не можу літати', 'Я хочу літати'],
          correctIndex: 2,
        },
        {
          id: 'a0-ican-fill',
          type: 'fill-blank',
          before: 'I can',
          after: ' a song.',
          answer: 'sing',
          hint: 'Що ми робимо з піснею? (співати)',
        },
        {
          id: 'a0-ican-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай дію з перекладом:',
          pairs: [
            { left: 'see', right: 'бачити' },
            { left: 'hear', right: 'чути' },
            { left: 'run', right: 'бігати' },
            { left: 'jump', right: 'стрибати' },
            { left: 'sing', right: 'співати' },
          ],
        },
        {
          id: 'a0-ican-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я можу стрибати.',
          answer: 'I can jump.',
          acceptedAnswers: ['i can jump', 'I can jump', 'i can jump.'],
        },
      ],
    },

    // ─── 5. My Face ───────────────────────────────────────────────────
    {
      slug: 'a0-my-face',
      title: 'My Face',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'descriptions',
      sectionTitle: 'Юніт 2 · Опис',
      sectionOrder: 1,
      topic: 'face',
      steps: [
        {
          id: 'a0-face-theory',
          type: 'theory',
          title: 'Моє обличчя 🙂',
          body: 'Опишемо обличчя: очі, ніс, рот, вуха. І додамо колір очей: «I have brown eyes» = «У мене карі очі».',
          examples: [
            { en: 'eyes', ua: 'очі' },
            { en: 'nose', ua: 'ніс' },
            { en: 'mouth', ua: 'рот' },
            { en: 'ears', ua: 'вуха' },
            { en: 'hair', ua: 'волосся' },
            { en: 'I have blue eyes.', ua: 'У мене блакитні очі.' },
          ],
        },
        {
          id: 'a0-face-mc1',
          type: 'multiple-choice',
          question: '«Mouth» — це…',
          options: ['ніс', 'рот', 'вухо', 'око'],
          correctIndex: 1,
        },
        {
          id: 'a0-face-mc2',
          type: 'multiple-choice',
          question: 'Скільки очей у людини?',
          options: ['one eye', 'two eyes', 'three eyes', 'no eyes'],
          correctIndex: 1,
        },
        {
          id: 'a0-face-fill',
          type: 'fill-blank',
          before: 'I have brown',
          after: '.',
          answer: 'eyes',
          hint: 'Множина від «eye».',
        },
        {
          id: 'a0-face-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'eyes', right: 'очі' },
            { left: 'nose', right: 'ніс' },
            { left: 'mouth', right: 'рот' },
            { left: 'ears', right: 'вуха' },
            { left: 'hair', right: 'волосся' },
          ],
        },
        {
          id: 'a0-face-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'У мене зелені очі.',
          answer: 'I have green eyes.',
          acceptedAnswers: [
            'i have green eyes',
            'I have green eyes',
            'i have green eyes.',
            "I've got green eyes",
            "i've got green eyes",
          ],
        },
      ],
    },
  ],
};
