import type { CourseSeed } from '../types';

/**
 * A1 — Elementary (3 courses, 15 lessons total).
 *   1. My Family & Me  — extended family + possessives + 3rd person.
 *   2. Around the House — rooms, prepositions, "there is/are".
 *   3. At School — school items, days of the week, classroom.
 *
 * Each course is 5 lessons × 6–7 steps. First lesson of each is free.
 * Bundled in one file to keep the seed footprint manageable; the
 * orchestrator imports each export individually.
 */

// ═══════════════════════════════════════════════════════════════════════
// 1. My Family & Me
// ═══════════════════════════════════════════════════════════════════════
export const a1MyFamily: CourseSeed = {
  slug: 'a1-my-family',
  createIfMissing: {
    title: 'My Family & Me',
    titleUa: 'Моя сімʼя і я',
    subtitle: 'A1 · 5 уроків · початковий рівень',
    description:
      'Більше про родину: дідусь, бабуся, тіточка, дядько. Вчимось казати «це мій / його / її», запитувати про вік, описувати фотографії.',
    descriptionShort: 'Розширена родина, присвійні, опис фотографій.',
    level: 'A1',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '👨‍👩‍👧',
    tags: ['kids', 'a1', 'family', 'grammar'],
  },
  lessons: [
    {
      slug: 'a1-family-members',
      title: 'Family Members',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-family',
      sectionTitle: 'Юніт 1 · Родина',
      sectionOrder: 0,
      isFree: true,
      topic: 'family',
      steps: [
        {
          id: 'a1-fm-theory',
          type: 'theory',
          title: 'Уся родина 👵👴',
          body: 'У родині не лише мама й тато. Є дідусь, бабуся, дядько, тіточка, кузени.',
          examples: [
            { en: 'grandma / granny', ua: 'бабуся' },
            { en: 'grandpa / grandad', ua: 'дідусь' },
            { en: 'aunt', ua: 'тіточка' },
            { en: 'uncle', ua: 'дядько' },
            { en: 'cousin', ua: 'кузен / кузина' },
            { en: 'parents', ua: 'батьки' },
          ],
          tip: '💡 «Granny» / «grandad» — теплі дитячі форми.',
        },
        {
          id: 'a1-fm-mc1',
          type: 'multiple-choice',
          question: '«Aunt» — це…',
          options: ['тіточка', 'дядько', 'кузен', 'бабуся'],
          correctIndex: 0,
        },
        {
          id: 'a1-fm-mc2',
          type: 'multiple-choice',
          question: 'Хто такі «parents»?',
          options: ['дідусь і бабуся', 'батьки', 'двоюрідні', 'брати'],
          correctIndex: 1,
        },
        {
          id: 'a1-fm-fill',
          type: 'fill-blank',
          before: "My mom's brother is my",
          after: '.',
          answer: 'uncle',
          hint: 'Брат мами — це…',
        },
        {
          id: 'a1-fm-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'grandma', right: 'бабуся' },
            { left: 'grandpa', right: 'дідусь' },
            { left: 'aunt', right: 'тіточка' },
            { left: 'uncle', right: 'дядько' },
            { left: 'cousin', right: 'кузен' },
            { left: 'parents', right: 'батьки' },
          ],
        },
        {
          id: 'a1-fm-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це моя бабуся.',
          answer: 'This is my grandma.',
          acceptedAnswers: [
            'this is my grandma',
            'This is my grandma',
            'this is my granny',
            'this is my grandmother',
          ],
        },
      ],
    },
    {
      slug: 'a1-this-is-my-mom',
      title: 'This Is My Mom',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-family',
      sectionTitle: 'Юніт 1 · Родина',
      sectionOrder: 0,
      topic: 'demonstratives',
      steps: [
        {
          id: 'a1-tim-theory',
          type: 'theory',
          title: 'Це / Ці 👉',
          body: '«This» — для одного предмета поруч. «These» — для кількох. Перевір число іменника: «this dog» / «these dogs».',
          examples: [
            { en: 'This is my mom.', ua: 'Це моя мама.' },
            { en: 'These are my parents.', ua: 'Це мої батьки.' },
            { en: 'This is a cat.', ua: 'Це кіт.' },
            { en: 'These are cats.', ua: 'Це коти.' },
          ],
          tip: '💡 «s» в кінці = множина.',
        },
        {
          id: 'a1-tim-mc1',
          type: 'multiple-choice',
          question: 'Один предмет — який варіант?',
          options: ['these', 'those', 'this', 'they'],
          correctIndex: 2,
        },
        {
          id: 'a1-tim-mc2',
          type: 'multiple-choice',
          question: 'Як сказати «це мої батьки»?',
          options: [
            'This is my parents',
            'These are my parents',
            'This are my parents',
            'These is my parents',
          ],
          correctIndex: 1,
        },
        {
          id: 'a1-tim-fill',
          type: 'fill-blank',
          before: '',
          after: ' are my brothers.',
          answer: 'These',
          hint: 'Множина — і з великої літери.',
        },
        {
          id: 'a1-tim-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Це моя сестра.',
          words: ['my', 'is', 'This', 'sister'],
          answer: ['This', 'is', 'my', 'sister'],
        },
        {
          id: 'a1-tim-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це мої кузени.',
          answer: 'These are my cousins.',
          acceptedAnswers: [
            'these are my cousins',
            'These are my cousins',
            'these are my cousins.',
          ],
        },
      ],
    },
    {
      slug: 'a1-how-old',
      title: 'How Old?',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-family',
      sectionTitle: 'Юніт 1 · Родина',
      sectionOrder: 0,
      topic: 'numbers-age',
      steps: [
        {
          id: 'a1-age-theory',
          type: 'theory',
          title: 'Числа 11–30 та вік 🎂',
          body: 'Запам\'ятай числа: eleven, twelve, thirteen… І питання: «How old are you?» — «I am ten».',
          examples: [
            { en: 'eleven', ua: '11' },
            { en: 'twelve', ua: '12' },
            { en: 'thirteen', ua: '13' },
            { en: 'fifteen', ua: '15' },
            { en: 'twenty', ua: '20' },
            { en: 'How old are you?', ua: 'Скільки тобі років?' },
            { en: 'I am ten.', ua: 'Мені десять.' },
          ],
          tip: '💡 13–19 закінчуються на «-teen». 20, 30… — «-ty».',
        },
        {
          id: 'a1-age-mc1',
          type: 'multiple-choice',
          question: '«Twelve» — це…',
          options: ['10', '11', '12', '13'],
          correctIndex: 2,
        },
        {
          id: 'a1-age-mc2',
          type: 'multiple-choice',
          question: 'Як спитати про вік?',
          options: [
            'How are you?',
            "What's your age?",
            'How old are you?',
            'When are you?',
          ],
          correctIndex: 2,
        },
        {
          id: 'a1-age-fill',
          type: 'fill-blank',
          before: 'I am',
          after: ' years old.',
          answer: 'twelve',
          hint: 'Число 12 словом.',
        },
        {
          id: 'a1-age-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай число з цифрою:',
          pairs: [
            { left: 'eleven', right: '11' },
            { left: 'fifteen', right: '15' },
            { left: 'twenty', right: '20' },
            { left: 'thirteen', right: '13' },
          ],
        },
        {
          id: 'a1-age-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мені одинадцять.',
          answer: 'I am eleven.',
          acceptedAnswers: [
            'i am eleven',
            'I am eleven',
            "I'm eleven",
            "i'm eleven",
            'I am 11',
          ],
        },
      ],
    },
    {
      slug: 'a1-what-she-likes',
      title: 'What She Likes',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-grammar',
      sectionTitle: 'Юніт 2 · Перша граматика',
      sectionOrder: 1,
      topic: 'present-simple-3rd',
      steps: [
        {
          id: 'a1-she-theory',
          type: 'theory',
          title: 'Він / Вона любить ☝️',
          body: 'Коли говоримо про когось одного («he», «she», «it») — додаємо «-s» до дієслова. «I like» але «She likes».',
          examples: [
            { en: 'I like apples.', ua: 'Я люблю яблука.' },
            { en: 'She likes apples.', ua: 'Вона любить яблука.' },
            { en: 'He plays football.', ua: 'Він грає у футбол.' },
            { en: 'My sister reads books.', ua: 'Моя сестра читає книжки.' },
          ],
          tip: '💡 «Read» → «reads», «play» → «plays», «like» → «likes».',
        },
        {
          id: 'a1-she-mc1',
          type: 'multiple-choice',
          question: 'Виправ помилку: She ___ pizza.',
          options: ['like', 'likes', 'liking', 'liked'],
          correctIndex: 1,
        },
        {
          id: 'a1-she-mc2',
          type: 'multiple-choice',
          question: 'А з «I» як буде?',
          options: ['I likes pizza', 'I like pizza', 'I liking pizza', 'I am like pizza'],
          correctIndex: 1,
        },
        {
          id: 'a1-she-fill',
          type: 'fill-blank',
          before: 'He',
          after: ' football every day.',
          answer: 'plays',
          hint: 'Додай «s» до «play».',
        },
        {
          id: 'a1-she-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Моя сестра любить котів.',
          words: ['cats', 'sister', 'My', 'likes'],
          answer: ['My', 'sister', 'likes', 'cats'],
        },
        {
          id: 'a1-she-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Він читає книжку.',
          answer: 'He reads a book.',
          acceptedAnswers: [
            'he reads a book',
            'He reads a book',
            'he reads a book.',
            "he's reading a book",
          ],
        },
      ],
    },
    {
      slug: 'a1-family-photo',
      title: 'Family Photo',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a1-grammar',
      sectionTitle: 'Юніт 2 · Перша граматика',
      sectionOrder: 1,
      topic: 'prepositions',
      steps: [
        {
          id: 'a1-fp-theory',
          type: 'theory',
          title: 'Хто де? 📸',
          body: 'Опишемо фото: хто на ньому, де стоїть. Використовуємо «next to», «behind», «in front of», «in the middle».',
          examples: [
            { en: 'next to', ua: 'поруч / біля' },
            { en: 'behind', ua: 'позаду' },
            { en: 'in front of', ua: 'попереду' },
            { en: 'in the middle', ua: 'посередині' },
            { en: 'My mom is next to my dad.', ua: 'Моя мама поруч з татом.' },
          ],
        },
        {
          id: 'a1-fp-mc1',
          type: 'multiple-choice',
          question: '«Behind» — це…',
          options: ['попереду', 'позаду', 'поруч', 'усередині'],
          correctIndex: 1,
        },
        {
          id: 'a1-fp-mc2',
          type: 'multiple-choice',
          question: 'Як сказати «поруч»?',
          options: ['behind', 'in front of', 'next to', 'on'],
          correctIndex: 2,
        },
        {
          id: 'a1-fp-fill',
          type: 'fill-blank',
          before: 'My brother is',
          after: ' me.',
          answer: 'next to',
          hint: 'Дві слова — фраза.',
        },
        {
          id: 'a1-fp-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'next to', right: 'поруч' },
            { left: 'behind', right: 'позаду' },
            { left: 'in front of', right: 'попереду' },
            { left: 'in the middle', right: 'посередині' },
          ],
        },
        {
          id: 'a1-fp-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мій тато стоїть позаду мами.',
          answer: 'My dad is behind my mom.',
          acceptedAnswers: [
            'my dad is behind my mom',
            'My dad is behind my mom',
            'my dad is behind my mom.',
            'my father is behind my mother',
          ],
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════
// 2. Around the House
// ═══════════════════════════════════════════════════════════════════════
export const a1AroundTheHouse: CourseSeed = {
  slug: 'a1-around-the-house',
  createIfMissing: {
    title: 'Around the House',
    titleUa: 'По дому',
    subtitle: 'A1 · 5 уроків · початковий рівень',
    description:
      'Кімнати, меблі, прийменники місця, «there is / there are», прибирання. Усе, що потрібно, щоб описати свою кімнату.',
    descriptionShort: 'Кімнати, меблі, де що знаходиться.',
    level: 'A1',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '🛋️',
    tags: ['kids', 'a1', 'house', 'prepositions'],
  },
  lessons: [
    {
      slug: 'a1-rooms',
      title: 'Rooms in the House',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'a1-house',
      sectionTitle: 'Юніт 1 · Кімнати',
      sectionOrder: 0,
      isFree: true,
      topic: 'rooms',
      steps: [
        {
          id: 'a1-rm-theory',
          type: 'theory',
          title: 'Кімнати у домі 🏠',
          body: 'Дім складається з кімнат. Кухня — «kitchen», спальня — «bedroom», ванна — «bathroom», вітальня — «living room».',
          examples: [
            { en: 'kitchen', ua: 'кухня' },
            { en: 'bedroom', ua: 'спальня' },
            { en: 'bathroom', ua: 'ванна' },
            { en: 'living room', ua: 'вітальня' },
            { en: 'garden', ua: 'сад' },
          ],
        },
        {
          id: 'a1-rm-mc1',
          type: 'multiple-choice',
          question: 'Де ми готуємо їжу?',
          options: ['bedroom', 'bathroom', 'kitchen', 'garden'],
          correctIndex: 2,
        },
        {
          id: 'a1-rm-mc2',
          type: 'multiple-choice',
          question: 'А де спимо?',
          options: ['kitchen', 'bedroom', 'bathroom', 'living room'],
          correctIndex: 1,
        },
        {
          id: 'a1-rm-fill',
          type: 'fill-blank',
          before: 'I watch TV in the',
          after: ' room.',
          answer: 'living',
          hint: 'У вітальні.',
        },
        {
          id: 'a1-rm-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'kitchen', right: 'кухня' },
            { left: 'bedroom', right: 'спальня' },
            { left: 'bathroom', right: 'ванна' },
            { left: 'living room', right: 'вітальня' },
            { left: 'garden', right: 'сад' },
          ],
        },
        {
          id: 'a1-rm-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Моя кухня велика.',
          answer: 'My kitchen is big.',
          acceptedAnswers: ['my kitchen is big', 'My kitchen is big', 'my kitchen is big.'],
        },
      ],
    },
    {
      slug: 'a1-where-is-it',
      title: 'Where Is It?',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-house',
      sectionTitle: 'Юніт 1 · Кімнати',
      sectionOrder: 0,
      topic: 'prepositions',
      steps: [
        {
          id: 'a1-wi-theory',
          type: 'theory',
          title: 'Прийменники місця 🔍',
          body: 'Маленькі слова, які кажуть, де що знаходиться: «in» (у), «on» (на), «under» (під), «next to» (біля).',
          examples: [
            { en: 'The book is on the table.', ua: 'Книжка на столі.' },
            { en: 'The cat is under the bed.', ua: 'Кіт під ліжком.' },
            { en: 'The pen is in the bag.', ua: 'Ручка у сумці.' },
            { en: 'The lamp is next to the bed.', ua: 'Лампа біля ліжка.' },
          ],
        },
        {
          id: 'a1-wi-mc1',
          type: 'multiple-choice',
          question: '«Under the bed» — це…',
          options: ['на ліжку', 'під ліжком', 'біля ліжка', 'у ліжку'],
          correctIndex: 1,
        },
        {
          id: 'a1-wi-mc2',
          type: 'multiple-choice',
          question: 'Як сказати «у сумці»?',
          options: ['on the bag', 'in the bag', 'under the bag', 'next to the bag'],
          correctIndex: 1,
        },
        {
          id: 'a1-wi-fill',
          type: 'fill-blank',
          before: 'The cat is',
          after: ' the chair.',
          answer: 'on',
          hint: 'Кіт сидить НА стільці.',
        },
        {
          id: 'a1-wi-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'in', right: 'у' },
            { left: 'on', right: 'на' },
            { left: 'under', right: 'під' },
            { left: 'next to', right: 'біля' },
          ],
        },
        {
          id: 'a1-wi-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Книжка під столом.',
          answer: 'The book is under the table.',
          acceptedAnswers: [
            'the book is under the table',
            'The book is under the table',
            'the book is under the table.',
            'book is under the table',
          ],
        },
      ],
    },
    {
      slug: 'a1-furniture',
      title: 'Furniture',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-house',
      sectionTitle: 'Юніт 1 · Кімнати',
      sectionOrder: 0,
      topic: 'furniture',
      steps: [
        {
          id: 'a1-fu-theory',
          type: 'theory',
          title: 'Меблі 🪑',
          body: '«There is» — є щось одне; «There are» — є кілька. «There is a sofa» / «There are two chairs».',
          examples: [
            { en: 'table', ua: 'стіл' },
            { en: 'chair', ua: 'стілець' },
            { en: 'bed', ua: 'ліжко' },
            { en: 'sofa', ua: 'диван' },
            { en: 'There is a TV in the room.', ua: 'У кімнаті є телевізор.' },
            { en: 'There are two windows.', ua: 'Є два вікна.' },
          ],
        },
        {
          id: 'a1-fu-mc1',
          type: 'multiple-choice',
          question: 'Що з цього — меблі для сну?',
          options: ['chair', 'bed', 'table', 'lamp'],
          correctIndex: 1,
        },
        {
          id: 'a1-fu-mc2',
          type: 'multiple-choice',
          question: '«Є три стільці» — це…',
          options: [
            'There is three chairs',
            'There are three chairs',
            'There three chairs',
            'They are three chairs',
          ],
          correctIndex: 1,
        },
        {
          id: 'a1-fu-fill',
          type: 'fill-blank',
          before: 'There',
          after: ' a big table.',
          answer: 'is',
          hint: '«Є один стіл» — однина.',
        },
        {
          id: 'a1-fu-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'table', right: 'стіл' },
            { left: 'chair', right: 'стілець' },
            { left: 'bed', right: 'ліжко' },
            { left: 'sofa', right: 'диван' },
          ],
        },
        {
          id: 'a1-fu-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У моїй кімнаті є диван.',
          words: ['my', 'sofa', 'a', 'is', 'There', 'in', 'room'],
          answer: ['There', 'is', 'a', 'sofa', 'in', 'my', 'room'],
        },
      ],
    },
    {
      slug: 'a1-my-room',
      title: 'My Room',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a1-house',
      sectionTitle: 'Юніт 1 · Кімнати',
      sectionOrder: 0,
      topic: 'description',
      steps: [
        {
          id: 'a1-mr-theory',
          type: 'theory',
          title: 'Опиши свою кімнату 🛏️',
          body: 'Скласти повне речення: «In my room there is a bed, a table and a chair». Використовуй «and» (і) для перерахування.',
          examples: [
            { en: 'In my room there is a bed.', ua: 'У моїй кімнаті є ліжко.' },
            { en: 'There are two windows.', ua: 'Є два вікна.' },
            { en: 'My desk is near the window.', ua: 'Мій стіл біля вікна.' },
          ],
        },
        {
          id: 'a1-mr-mc1',
          type: 'multiple-choice',
          question: 'Як зʼєднати слова «ліжко і стіл»?',
          options: [
            'a bed or a table',
            'a bed and a table',
            'a bed but a table',
            'a bed if a table',
          ],
          correctIndex: 1,
        },
        {
          id: 'a1-mr-mc2',
          type: 'multiple-choice',
          question: 'У кімнаті 3 стільці — як скажеш?',
          options: [
            'There is three chair',
            'There are three chair',
            'There are three chairs',
            'There is three chairs',
          ],
          correctIndex: 2,
        },
        {
          id: 'a1-mr-fill',
          type: 'fill-blank',
          before: 'There are two',
          after: ' in my room.',
          answer: 'windows',
          hint: 'Множина.',
        },
        {
          id: 'a1-mr-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене є ліжко і стіл.',
          words: ['table', 'I', 'have', 'a', 'and', 'bed', 'a'],
          answer: ['I', 'have', 'a', 'bed', 'and', 'a', 'table'],
        },
        {
          id: 'a1-mr-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Моя кімната маленька.',
          answer: 'My room is small.',
          acceptedAnswers: ['my room is small', 'My room is small', 'my room is small.'],
        },
      ],
    },
    {
      slug: 'a1-cleaning-up',
      title: 'Cleaning Up',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'a1-house',
      sectionTitle: 'Юніт 1 · Кімнати',
      sectionOrder: 0,
      topic: 'verbs-cleaning',
      steps: [
        {
          id: 'a1-cu-theory',
          type: 'theory',
          title: 'Прибираю 🧹',
          body: 'Дієслова: «clean» (прибирати), «wash» (мити), «tidy» (наводити порядок), «throw» (кидати).',
          examples: [
            { en: 'I clean my room.', ua: 'Я прибираю кімнату.' },
            { en: 'I wash my hands.', ua: 'Я мию руки.' },
            { en: 'I tidy my desk.', ua: 'Я навожу порядок на столі.' },
            { en: 'I throw rubbish in the bin.', ua: 'Я кидаю сміття у відро.' },
          ],
        },
        {
          id: 'a1-cu-mc1',
          type: 'multiple-choice',
          question: '«Wash» — це…',
          options: ['прибирати', 'мити', 'кидати', 'спати'],
          correctIndex: 1,
        },
        {
          id: 'a1-cu-mc2',
          type: 'multiple-choice',
          question: 'Що ми робимо з рукою (hand)?',
          options: ['throw', 'wash', 'sleep', 'eat'],
          correctIndex: 1,
        },
        {
          id: 'a1-cu-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' my room every day.',
          answer: 'clean',
          hint: 'Прибирати.',
        },
        {
          id: 'a1-cu-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'clean', right: 'прибирати' },
            { left: 'wash', right: 'мити' },
            { left: 'tidy', right: 'наводити порядок' },
            { left: 'throw', right: 'кидати' },
          ],
        },
        {
          id: 'a1-cu-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я мию руки.',
          answer: 'I wash my hands.',
          acceptedAnswers: [
            'i wash my hands',
            'I wash my hands',
            'i wash my hands.',
            'i am washing my hands',
          ],
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════
// 3. At School
// ═══════════════════════════════════════════════════════════════════════
export const a1AtSchool: CourseSeed = {
  slug: 'a1-at-school',
  createIfMissing: {
    title: 'At School',
    titleUa: 'У школі',
    subtitle: 'A1 · 5 уроків · початковий рівень',
    description:
      'Шкільне життя: ранець, предмети, дні тижня, фрази в класі, опис друга. Найпрактичніший курс на рівні A1.',
    descriptionShort: 'Школа, дні тижня, опис друга.',
    level: 'A1',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '✏️',
    tags: ['kids', 'a1', 'school', 'days'],
  },
  lessons: [
    {
      slug: 'a1-things-in-bag',
      title: 'Things in My Bag',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'a1-school',
      sectionTitle: 'Юніт 1 · Шкільне життя',
      sectionOrder: 0,
      isFree: true,
      topic: 'school-items',
      steps: [
        {
          id: 'a1-bg-theory',
          type: 'theory',
          title: 'У ранці 🎒',
          body: 'Що носить кожен школяр: книжки, зошити, олівці, ручки, гумка.',
          examples: [
            { en: 'book', ua: 'книжка' },
            { en: 'notebook', ua: 'зошит' },
            { en: 'pencil', ua: 'олівець' },
            { en: 'pen', ua: 'ручка' },
            { en: 'eraser', ua: 'гумка' },
            { en: 'ruler', ua: 'лінійка' },
          ],
        },
        {
          id: 'a1-bg-mc1',
          type: 'multiple-choice',
          question: '«Pencil» — це…',
          options: ['ручка', 'зошит', 'олівець', 'гумка'],
          correctIndex: 2,
        },
        {
          id: 'a1-bg-mc2',
          type: 'multiple-choice',
          question: 'Що використовуємо, щоб стерти?',
          options: ['ruler', 'pen', 'eraser', 'book'],
          correctIndex: 2,
        },
        {
          id: 'a1-bg-fill',
          type: 'fill-blank',
          before: 'I write with a',
          after: '.',
          answer: 'pen',
          hint: 'Чим пишемо у школі?',
        },
        {
          id: 'a1-bg-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'book', right: 'книжка' },
            { left: 'notebook', right: 'зошит' },
            { left: 'pencil', right: 'олівець' },
            { left: 'pen', right: 'ручка' },
            { left: 'eraser', right: 'гумка' },
            { left: 'ruler', right: 'лінійка' },
          ],
        },
        {
          id: 'a1-bg-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У моїй сумці є книжка.',
          words: ['my', 'is', 'in', 'There', 'a', 'bag', 'book'],
          answer: ['There', 'is', 'a', 'book', 'in', 'my', 'bag'],
        },
      ],
    },
    {
      slug: 'a1-subjects',
      title: 'Subjects I Study',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'a1-school',
      sectionTitle: 'Юніт 1 · Шкільне життя',
      sectionOrder: 0,
      topic: 'subjects',
      steps: [
        {
          id: 'a1-sb-theory',
          type: 'theory',
          title: 'Шкільні предмети 📚',
          body: 'Найпопулярніші предмети у школі.',
          examples: [
            { en: 'Maths', ua: 'математика' },
            { en: 'English', ua: 'англійська' },
            { en: 'Art', ua: 'малювання' },
            { en: 'Music', ua: 'музика' },
            { en: 'PE (Physical Education)', ua: 'фізкультура' },
            { en: 'Science', ua: 'природознавство' },
          ],
        },
        {
          id: 'a1-sb-mc1',
          type: 'multiple-choice',
          question: 'На якому предметі ми малюємо?',
          options: ['Maths', 'Art', 'PE', 'English'],
          correctIndex: 1,
        },
        {
          id: 'a1-sb-mc2',
          type: 'multiple-choice',
          question: 'А де співаємо й слухаємо музику?',
          options: ['Music', 'Science', 'Art', 'Maths'],
          correctIndex: 0,
        },
        {
          id: 'a1-sb-fill',
          type: 'fill-blank',
          before: 'My favourite subject is',
          after: '.',
          answer: 'English',
          hint: 'Той, на якому ти зараз вчишся!',
        },
        {
          id: 'a1-sb-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'Maths', right: 'математика' },
            { left: 'Art', right: 'малювання' },
            { left: 'Music', right: 'музика' },
            { left: 'PE', right: 'фізкультура' },
            { left: 'Science', right: 'природознавство' },
          ],
        },
        {
          id: 'a1-sb-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я люблю математику.',
          answer: 'I like Maths.',
          acceptedAnswers: ['i like maths', 'I like maths', 'i like maths.', 'I like math'],
        },
      ],
    },
    {
      slug: 'a1-days-of-week',
      title: 'Days of the Week',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'a1-school',
      sectionTitle: 'Юніт 1 · Шкільне життя',
      sectionOrder: 0,
      topic: 'days',
      steps: [
        {
          id: 'a1-dw-theory',
          type: 'theory',
          title: 'Дні тижня 📅',
          body: 'У англомовних країнах тиждень часто починається з неділі. Дні пишуться з великої літери. Перед днем кажемо «on»: «on Monday».',
          examples: [
            { en: 'Monday', ua: 'понеділок' },
            { en: 'Tuesday', ua: 'вівторок' },
            { en: 'Wednesday', ua: 'середа' },
            { en: 'Thursday', ua: 'четвер' },
            { en: 'Friday', ua: 'пʼятниця' },
            { en: 'Saturday', ua: 'субота' },
            { en: 'Sunday', ua: 'неділя' },
          ],
          tip: '💡 Subота й неділя — «weekend» (вихідні).',
        },
        {
          id: 'a1-dw-mc1',
          type: 'multiple-choice',
          question: 'Перший день шкільного тижня — це…',
          options: ['Sunday', 'Monday', 'Friday', 'Saturday'],
          correctIndex: 1,
        },
        {
          id: 'a1-dw-mc2',
          type: 'multiple-choice',
          question: 'Як кажуть «у пʼятницю»?',
          options: ['in Friday', 'on Friday', 'at Friday', 'of Friday'],
          correctIndex: 1,
        },
        {
          id: 'a1-dw-fill',
          type: 'fill-blank',
          before: 'On',
          after: ' I have Music.',
          answer: 'Wednesday',
          hint: 'Середа.',
        },
        {
          id: 'a1-dw-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'Monday', right: 'понеділок' },
            { left: 'Wednesday', right: 'середа' },
            { left: 'Friday', right: 'пʼятниця' },
            { left: 'Sunday', right: 'неділя' },
          ],
        },
        {
          id: 'a1-dw-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'У вівторок я граю у футбол.',
          answer: 'On Tuesday I play football.',
          acceptedAnswers: [
            'on tuesday i play football',
            'On Tuesday I play football',
            'on tuesday i play football.',
          ],
        },
      ],
    },
    {
      slug: 'a1-teacher-says',
      title: 'My Teacher Says…',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'a1-school',
      sectionTitle: 'Юніт 1 · Шкільне життя',
      sectionOrder: 0,
      topic: 'classroom',
      steps: [
        {
          id: 'a1-ts-theory',
          type: 'theory',
          title: 'Фрази у класі 🍎',
          body: 'Що часто чуємо від вчителя: «Open your books», «Raise your hand», «Listen, please».',
          examples: [
            { en: 'Open your books.', ua: 'Відкрийте книжки.' },
            { en: 'Close the door.', ua: 'Закрий двері.' },
            { en: 'Raise your hand.', ua: 'Підніми руку.' },
            { en: 'Listen, please.', ua: 'Слухай, будь ласка.' },
            { en: 'Be quiet.', ua: 'Тихіше / помовчи.' },
          ],
        },
        {
          id: 'a1-ts-mc1',
          type: 'multiple-choice',
          question: '«Raise your hand» — це…',
          options: ['Опусти руку', 'Підніми руку', 'Дай руку', 'Помий руку'],
          correctIndex: 1,
        },
        {
          id: 'a1-ts-mc2',
          type: 'multiple-choice',
          question: 'Що означає «Be quiet»?',
          options: ['Голосніше', 'Тихіше', 'Швидше', 'Повільніше'],
          correctIndex: 1,
        },
        {
          id: 'a1-ts-fill',
          type: 'fill-blank',
          before: '',
          after: ' your books, please!',
          answer: 'Open',
          hint: 'З великої літери на початку.',
        },
        {
          id: 'a1-ts-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'Open', right: 'Відкрий' },
            { left: 'Close', right: 'Закрий' },
            { left: 'Listen', right: 'Слухай' },
            { left: 'Be quiet', right: 'Тихіше' },
          ],
        },
        {
          id: 'a1-ts-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Закрий двері, будь ласка.',
          answer: 'Close the door, please.',
          acceptedAnswers: [
            'close the door, please',
            'Close the door please',
            'close the door please',
            'close the door, please.',
          ],
        },
      ],
    },
    {
      slug: 'a1-best-friend',
      title: 'My Best Friend',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a1-school',
      sectionTitle: 'Юніт 1 · Шкільне життя',
      sectionOrder: 0,
      topic: 'description',
      steps: [
        {
          id: 'a1-bf-theory',
          type: 'theory',
          title: 'Опис друга 👫',
          body: 'Як описати друга? Імʼя, вік, зовнішність, характер. «He is funny» / «She has long hair».',
          examples: [
            { en: 'tall', ua: 'високий' },
            { en: 'short', ua: 'низький' },
            { en: 'funny', ua: 'веселий' },
            { en: 'kind', ua: 'добрий' },
            { en: 'long hair', ua: 'довге волосся' },
            { en: 'She has long hair.', ua: 'У неї довге волосся.' },
          ],
        },
        {
          id: 'a1-bf-mc1',
          type: 'multiple-choice',
          question: '«Kind» — це…',
          options: ['веселий', 'високий', 'добрий', 'розумний'],
          correctIndex: 2,
        },
        {
          id: 'a1-bf-mc2',
          type: 'multiple-choice',
          question: 'Як сказати «у нього коротке волосся»?',
          options: [
            'He has short hair',
            'He have short hair',
            'He is short hair',
            'He short hair',
          ],
          correctIndex: 0,
        },
        {
          id: 'a1-bf-fill',
          type: 'fill-blank',
          before: 'My friend',
          after: ' brown eyes.',
          answer: 'has',
          hint: '«Має» — третя особа.',
        },
        {
          id: 'a1-bf-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'tall', right: 'високий' },
            { left: 'short', right: 'низький' },
            { left: 'funny', right: 'веселий' },
            { left: 'kind', right: 'добрий' },
          ],
        },
        {
          id: 'a1-bf-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мій друг високий і добрий.',
          answer: 'My friend is tall and kind.',
          acceptedAnswers: [
            'my friend is tall and kind',
            'My friend is tall and kind',
            'my friend is tall and kind.',
          ],
        },
      ],
    },
  ],
};
