import type { CourseSeed, LessonStep } from '../types';

/**
 * A2..C2 catalog — course shells.
 *
 * Each course has 2 sample lessons (high-quality content) so that the
 * course appears in the kids school listing and a curious learner can
 * try it. The remaining 1–3 lessons per course are intentionally
 * deferred to future content sessions; teachers can also extend any
 * course via the `/dashboard/teacher-library` editor without touching
 * seeds. See `COURSES.md` for the per-course brief.
 */

// Helper for translate-step accepted-answers boilerplate so we don't
// hand-roll 5 variants every time. Lower-case + with/without trailing
// punctuation + the original.
function accepted(answer: string, extras: string[] = []): string[] {
  const noPunct = answer.replace(/[.!?]$/, '');
  const lc = answer.toLowerCase();
  const lcNoPunct = noPunct.toLowerCase();
  return Array.from(new Set([answer, noPunct, lc, lcNoPunct, ...extras]));
}

// Helper for the standard 2-sample-lesson course so we don't repeat the
// boilerplate. Real content per course is in the `lessons` arg.
function shellCourse(
  course: Omit<CourseSeed, 'lessons'>,
  lessons: CourseSeed['lessons'],
): CourseSeed {
  return { ...course, lessons };
}

// ═══════════════════════════════════════════════════════════════════════
// A2 — Pre-Intermediate (2 courses)
// ═══════════════════════════════════════════════════════════════════════

export const a2FoodAndDrinks = shellCourse(
  {
    slug: 'a2-food-and-drinks',
    createIfMissing: {
      title: 'Food & Drinks',
      titleUa: 'Їжа і напої',
      subtitle: 'A2 · 5 уроків · початково-середній рівень',
      description:
        'Здорове й смачне, прийоми їжі, ресторан, кулінарні дієслова, кухні світу. Працюємо з present simple і дієсловами стану «like / love / hate».',
      descriptionShort: 'Лексика їжі, ресторан, кулінарні дієслова.',
      level: 'A2',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '🍎',
      tags: ['kids', 'a2', 'food'],
    },
  },
  [
    {
      slug: 'a2-healthy-tasty',
      title: 'Healthy & Tasty',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-food',
      sectionTitle: 'Юніт 1 · Кухня',
      sectionOrder: 0,
      isFree: true,
      topic: 'food-vocab',
      steps: [
        {
          id: 'a2-ht-theory',
          type: 'theory',
          title: 'Smачно і корисно 🥦',
          body: 'Овочі, фрукти, солодке. «Healthy» — корисно, «tasty» — смачно. Ставимо ці слова перед іменником: «a tasty cake».',
          examples: [
            { en: 'fruit', ua: 'фрукт' },
            { en: 'vegetable', ua: 'овоч' },
            { en: 'sweet', ua: 'солодощі' },
            { en: 'healthy', ua: 'здоровий, корисний' },
            { en: 'tasty', ua: 'смачний' },
          ],
        },
        {
          id: 'a2-ht-mc1',
          type: 'multiple-choice',
          question: 'Який варіант — фрукт?',
          options: ['carrot', 'apple', 'broccoli', 'tomato'],
          correctIndex: 1,
        } as LessonStep,
        {
          id: 'a2-ht-mc2',
          type: 'multiple-choice',
          question: '«Tasty» — це…',
          options: ['здоровий', 'смачний', 'солодкий', 'дорогий'],
          correctIndex: 1,
        },
        {
          id: 'a2-ht-fill',
          type: 'fill-blank',
          before: 'Carrots are',
          after: '.',
          answer: 'healthy',
          hint: 'Морква — корисна.',
        },
        {
          id: 'a2-ht-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'fruit', right: 'фрукт' },
            { left: 'vegetable', right: 'овоч' },
            { left: 'sweet', right: 'солодощі' },
            { left: 'healthy', right: 'корисний' },
          ],
        },
        {
          id: 'a2-ht-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Овочі дуже корисні.',
          answer: 'Vegetables are very healthy.',
          acceptedAnswers: accepted('Vegetables are very healthy.', [
            'vegetables are healthy',
            'Vegetables are healthy',
          ]),
        },
      ],
    },
    {
      slug: 'a2-restaurant',
      title: 'In the Restaurant',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'a2-food',
      sectionTitle: 'Юніт 1 · Кухня',
      sectionOrder: 0,
      topic: 'ordering',
      steps: [
        {
          id: 'a2-rt-theory',
          type: 'theory',
          title: 'Замовляємо 🍽️',
          body: 'Ввічливо просити їжу: «Can I have…», «I\'d like…». «I\'d» = «I would» — більш формальне.',
          examples: [
            { en: 'Can I have a pizza, please?', ua: 'Можна піцу, будь ласка?' },
            { en: "I'd like some water.", ua: 'Я б хотів води.' },
            { en: 'How much is it?', ua: 'Скільки коштує?' },
            { en: "Here's your order.", ua: 'Ось ваше замовлення.' },
          ],
          tip: '💡 «Some» — для незліченних і кількості: «some water», «some bread».',
        },
        {
          id: 'a2-rt-mc1',
          type: 'multiple-choice',
          question: 'Як ввічливо попросити води?',
          options: [
            'Give me water',
            "I'd like some water, please",
            'I want water now',
            'Water!',
          ],
          correctIndex: 1,
        },
        {
          id: 'a2-rt-fill',
          type: 'fill-blank',
          before: 'Can I',
          after: ' a pizza?',
          answer: 'have',
          hint: 'Що ми «маємо» в ресторані?',
        },
        {
          id: 'a2-rt-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'order', right: 'замовлення' },
            { left: 'menu', right: 'меню' },
            { left: 'waiter', right: 'офіціант' },
            { left: 'bill', right: 'рахунок' },
          ],
        },
        {
          id: 'a2-rt-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я хотів би сік, будь ласка.',
          answer: "I'd like some juice, please.",
          acceptedAnswers: accepted("I'd like some juice, please.", [
            'i would like some juice please',
            'i want some juice please',
          ]),
        },
      ],
    },
    // ─── 3. Breakfast, Lunch, Dinner ─────────────────────────────────
    {
      slug: 'a2-meals',
      title: 'Breakfast, Lunch, Dinner',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-food',
      sectionTitle: 'Юніт 1 · Кухня',
      sectionOrder: 0,
      topic: 'meals',
      steps: [
        {
          id: 'a2-ml-theory',
          type: 'theory',
          title: 'Прийоми їжі 🍳',
          body: '«Breakfast» — сніданок, «lunch» — обід, «dinner» — вечеря. З цими словами кажемо «have»: «I have breakfast at 8».',
          examples: [
            { en: 'breakfast', ua: 'сніданок' },
            { en: 'lunch', ua: 'обід' },
            { en: 'dinner', ua: 'вечеря' },
            { en: 'I usually have cereal for breakfast.', ua: 'Я зазвичай їм пластівці на сніданок.' },
            { en: 'For lunch we have soup.', ua: 'На обід у нас суп.' },
          ],
          tip: '💡 «Have» з прийомами їжі — без артикля.',
        },
        {
          id: 'a2-ml-mc1',
          type: 'multiple-choice',
          question: 'Що ми зазвичай їмо вранці?',
          options: ['lunch', 'dinner', 'breakfast', 'snack'],
          correctIndex: 2,
        },
        {
          id: 'a2-ml-mc2',
          type: 'multiple-choice',
          question: '«Я обідаю об одинадцятій» — це…',
          options: [
            'I have lunch at eleven',
            'I lunch at eleven',
            "I'm lunching at eleven",
            'I do lunch at eleven',
          ],
          correctIndex: 0,
        },
        {
          id: 'a2-ml-fill',
          type: 'fill-blank',
          before: 'For',
          after: ' I usually eat fish.',
          answer: 'dinner',
          hint: 'Вечірня їжа.',
        },
        {
          id: 'a2-ml-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай прийом їжі з типовою стравою:',
          pairs: [
            { left: 'breakfast', right: 'cereal' },
            { left: 'lunch', right: 'sandwich' },
            { left: 'dinner', right: 'pasta' },
            { left: 'snack', right: 'apple' },
          ],
        },
        {
          id: 'a2-ml-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я снідаю о пів на восьму.',
          answer: 'I have breakfast at half past seven.',
          acceptedAnswers: accepted('I have breakfast at half past seven.', [
            'i have breakfast at 7:30',
            'i eat breakfast at half past seven',
          ]),
        },
      ],
    },
    // ─── 4. Cooking Verbs ────────────────────────────────────────────
    {
      slug: 'a2-cooking',
      title: 'Cooking Verbs',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-food',
      sectionTitle: 'Юніт 1 · Кухня',
      sectionOrder: 0,
      topic: 'cooking',
      steps: [
        {
          id: 'a2-cook-theory',
          type: 'theory',
          title: 'Куховарські дієслова 👨‍🍳',
          body: 'Що робимо на кухні? «cut» — ріжемо, «fry» — смажимо, «bake» — печемо, «mix» — змішуємо, «boil» — варимо.',
          examples: [
            { en: 'cut', ua: 'різати' },
            { en: 'fry', ua: 'смажити' },
            { en: 'bake', ua: 'пекти' },
            { en: 'mix', ua: 'змішувати' },
            { en: 'boil', ua: 'варити, кип\'ятити' },
            { en: 'I bake a cake every Sunday.', ua: 'Я печу торт щонеділі.' },
          ],
        },
        {
          id: 'a2-cook-mc1',
          type: 'multiple-choice',
          question: 'Що робимо з тортом у духовці?',
          options: ['fry', 'bake', 'boil', 'cut'],
          correctIndex: 1,
        },
        {
          id: 'a2-cook-mc2',
          type: 'multiple-choice',
          question: '«Boil» — це…',
          options: ['печемо', 'смажимо', 'варимо', 'ріжемо'],
          correctIndex: 2,
        },
        {
          id: 'a2-cook-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' the carrots into small pieces.',
          answer: 'cut',
          hint: 'Робимо ножем.',
        },
        {
          id: 'a2-cook-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'cut', right: 'різати' },
            { left: 'fry', right: 'смажити' },
            { left: 'bake', right: 'пекти' },
            { left: 'mix', right: 'змішувати' },
            { left: 'boil', right: 'варити' },
          ],
        },
        {
          id: 'a2-cook-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я смажу яйця вранці.',
          words: ['the', 'in', 'fry', 'eggs', 'I', 'morning'],
          answer: ['I', 'fry', 'eggs', 'in', 'the', 'morning'],
        },
      ],
    },
    // ─── 5. Food Around the World ────────────────────────────────────
    {
      slug: 'a2-food-around-world',
      title: 'Food Around the World',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-food',
      sectionTitle: 'Юніт 1 · Кухня',
      sectionOrder: 0,
      topic: 'cuisines',
      steps: [
        {
          id: 'a2-faw-theory',
          type: 'theory',
          title: 'Кухні світу 🌍',
          body: 'Прикметники з країн: «Italian pizza», «Japanese sushi», «Mexican tacos». Пишуться завжди з великої літери.',
          examples: [
            { en: 'Italian pizza', ua: 'італійська піца' },
            { en: 'Japanese sushi', ua: 'японські суші' },
            { en: 'Mexican tacos', ua: 'мексиканські такоси' },
            { en: 'Ukrainian borscht', ua: 'український борщ' },
            { en: 'French croissant', ua: 'французький круасан' },
          ],
          tip: '💡 Прикметники з країн = з великої літери: Italian, French, Japanese.',
        },
        {
          id: 'a2-faw-mc1',
          type: 'multiple-choice',
          question: 'Звідки походять суші?',
          options: ['Italy', 'Japan', 'Mexico', 'France'],
          correctIndex: 1,
        },
        {
          id: 'a2-faw-mc2',
          type: 'multiple-choice',
          question: 'Як по-англійськи «французький круасан»?',
          options: [
            'France croissant',
            'French croissant',
            'frenchy croissant',
            'french croissant',
          ],
          correctIndex: 1,
        },
        {
          id: 'a2-faw-fill',
          type: 'fill-blank',
          before: 'Borscht is',
          after: ' soup.',
          answer: 'Ukrainian',
          hint: 'З великої літери — прикметник з країни.',
        },
        {
          id: 'a2-faw-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай страву з кухнею:',
          pairs: [
            { left: 'pizza', right: 'Italian' },
            { left: 'sushi', right: 'Japanese' },
            { left: 'tacos', right: 'Mexican' },
            { left: 'borscht', right: 'Ukrainian' },
          ],
        },
        {
          id: 'a2-faw-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я люблю італійську піцу.',
          answer: 'I love Italian pizza.',
          acceptedAnswers: accepted('I love Italian pizza.', [
            'i like italian pizza',
            'i love italian pizza',
          ]),
        },
      ],
    },
  ],
);

export const a2MyDay = shellCourse(
  {
    slug: 'a2-my-day',
    createIfMissing: {
      title: 'My Daily Routine',
      titleUa: 'Мій день',
      subtitle: 'A2 · 5 уроків · початково-середній рівень',
      description:
        'Котра година, ранкова рутина, після школи, хобі, плани на вихідні. Граматика: present simple + frequency adverbs, present continuous для планів.',
      descriptionShort: 'Час, рутина, плани на вихідні.',
      level: 'A2',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '🕐',
      tags: ['kids', 'a2', 'routine'],
    },
  },
  [
    {
      slug: 'a2-telling-time',
      title: 'Telling Time',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-routine',
      sectionTitle: 'Юніт 1 · Час',
      sectionOrder: 0,
      isFree: true,
      topic: 'time',
      steps: [
        {
          id: 'a2-tt-theory',
          type: 'theory',
          title: 'Котра година? ⏰',
          body: '«It\'s seven o\'clock» = рівно 7. «Half past seven» = пів на 8 (тобто 7:30). «Quarter past» = 15 хв після, «quarter to» = 15 хв до.',
          examples: [
            { en: "It's seven o'clock.", ua: '7:00 рівно.' },
            { en: "It's half past seven.", ua: '7:30.' },
            { en: "It's quarter past nine.", ua: '9:15.' },
            { en: "It's quarter to ten.", ua: '9:45.' },
          ],
        },
        {
          id: 'a2-tt-mc1',
          type: 'multiple-choice',
          question: '7:30 англійською — це…',
          options: [
            'half past seven',
            'quarter past seven',
            'quarter to seven',
            'seven thirty past',
          ],
          correctIndex: 0,
        },
        {
          id: 'a2-tt-mc2',
          type: 'multiple-choice',
          question: 'А 9:45?',
          options: [
            'quarter past nine',
            'quarter to ten',
            'half past nine',
            'ten quarter',
          ],
          correctIndex: 1,
        },
        {
          id: 'a2-tt-fill',
          type: 'fill-blank',
          before: "It's",
          after: ' past eight.',
          answer: 'half',
          hint: '8:30 = пів на 9 = "half past 8".',
        },
        {
          id: 'a2-tt-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Зараз чверть на третю.',
          answer: "It's quarter past two.",
          acceptedAnswers: accepted("It's quarter past two.", [
            "it is quarter past two",
            "it's a quarter past two",
          ]),
        },
      ],
    },
    {
      slug: 'a2-morning-routine',
      title: 'Morning Routine',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-routine',
      sectionTitle: 'Юніт 1 · Час',
      sectionOrder: 0,
      topic: 'routine',
      steps: [
        {
          id: 'a2-mr-theory',
          type: 'theory',
          title: 'Ранкова рутина ☀️',
          body: 'Дієслова, які показують послідовність: «get up» (вставати), «brush teeth» (чистити зуби), «have breakfast» (снідати).',
          examples: [
            { en: 'I get up at 7.', ua: 'Я встаю о 7-й.' },
            { en: 'I brush my teeth.', ua: 'Я чищу зуби.' },
            { en: 'I have breakfast.', ua: 'Я снідаю.' },
            { en: 'I go to school.', ua: 'Я йду до школи.' },
          ],
          tip: '💡 «Have breakfast / lunch / dinner» — без «a / the».',
        },
        {
          id: 'a2-mr-mc1',
          type: 'multiple-choice',
          question: '«Get up» — це…',
          options: ['прокидатись', 'вставати з ліжка', 'снідати', 'мити обличчя'],
          correctIndex: 1,
        },
        {
          id: 'a2-mr-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' my teeth at 7:15.',
          answer: 'brush',
          hint: 'Дієслово для зубів.',
        },
        {
          id: 'a2-mr-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я снідаю о восьмій.',
          words: ['breakfast', 'I', 'eight', 'have', 'at'],
          answer: ['I', 'have', 'breakfast', 'at', 'eight'],
        },
        {
          id: 'a2-mr-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я встаю о сьомій.',
          answer: 'I get up at seven.',
          acceptedAnswers: accepted('I get up at seven.', [
            'i wake up at 7',
            'i get up at 7',
          ]),
        },
      ],
    },
    // ─── 3. After School ─────────────────────────────────────────────
    {
      slug: 'a2-after-school',
      title: 'After School',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-routine',
      sectionTitle: 'Юніт 1 · Час',
      sectionOrder: 0,
      topic: 'frequency',
      steps: [
        {
          id: 'a2-as-theory',
          type: 'theory',
          title: 'Прислівники частоти ⏱️',
          body: 'Як часто? «always» (завжди), «usually» (зазвичай), «often» (часто), «sometimes» (іноді), «never» (ніколи). Ставимо ПЕРЕД основним дієсловом.',
          examples: [
            { en: 'I always do my homework.', ua: 'Я завжди роблю домашку.' },
            { en: 'She usually watches TV.', ua: 'Вона зазвичай дивиться телевізор.' },
            { en: 'We often play outside.', ua: 'Ми часто граємось надворі.' },
            { en: 'I never eat fast food.', ua: 'Я ніколи не їм фастфуд.' },
          ],
          tip: '💡 Виключення: ці слова ставимо ПІСЛЯ дієслова «be»: «He is always late».',
        },
        {
          id: 'a2-as-mc1',
          type: 'multiple-choice',
          question: '«Often» — це…',
          options: ['завжди', 'часто', 'іноді', 'ніколи'],
          correctIndex: 1,
        },
        {
          id: 'a2-as-mc2',
          type: 'multiple-choice',
          question: 'Куди ставимо «sometimes» у реченні «I __ play tennis»?',
          options: ['на початку', 'після play', 'перед play', 'не важливо'],
          correctIndex: 2,
        },
        {
          id: 'a2-as-fill',
          type: 'fill-blank',
          before: 'My brother',
          after: ' watches cartoons after school.',
          answer: 'usually',
          hint: 'Зазвичай.',
        },
        {
          id: 'a2-as-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'always', right: 'завжди' },
            { left: 'usually', right: 'зазвичай' },
            { left: 'often', right: 'часто' },
            { left: 'sometimes', right: 'іноді' },
            { left: 'never', right: 'ніколи' },
          ],
        },
        {
          id: 'a2-as-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я часто граю у футбол після школи.',
          answer: 'I often play football after school.',
          acceptedAnswers: accepted('I often play football after school.'),
        },
      ],
    },
    // ─── 4. My Hobbies ───────────────────────────────────────────────
    {
      slug: 'a2-my-hobbies',
      title: 'My Hobbies',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'a2-routine',
      sectionTitle: 'Юніт 1 · Час',
      sectionOrder: 0,
      topic: 'gerunds',
      steps: [
        {
          id: 'a2-hb-theory',
          type: 'theory',
          title: 'Хобі і герундій 🎨',
          body: 'Після «like / love / hate» дієслово отримує закінчення «-ing» (це герундій): «I like reading». Не плутай з present continuous («I am reading»).',
          examples: [
            { en: 'I like reading.', ua: 'Я люблю читати.' },
            { en: 'She loves drawing.', ua: 'Вона обожнює малювати.' },
            { en: 'My brother hates running.', ua: 'Мій брат ненавидить бігати.' },
            { en: "I don't like dancing.", ua: 'Мені не подобається танцювати.' },
          ],
        },
        {
          id: 'a2-hb-mc1',
          type: 'multiple-choice',
          question: 'Виправ помилку: I like ___.',
          options: ['read', 'reading', 'to reading', 'reads'],
          correctIndex: 1,
        },
        {
          id: 'a2-hb-mc2',
          type: 'multiple-choice',
          question: '«Я обожнюю співати» — це…',
          options: [
            'I love singing',
            'I love sing',
            'I am loving sing',
            'I am singing love',
          ],
          correctIndex: 0,
        },
        {
          id: 'a2-hb-fill',
          type: 'fill-blank',
          before: 'My sister loves',
          after: ' (draw).',
          answer: 'drawing',
          hint: 'Додай «-ing» до «draw».',
        },
        {
          id: 'a2-hb-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'reading', right: 'читання' },
            { left: 'drawing', right: 'малювання' },
            { left: 'dancing', right: 'танці' },
            { left: 'singing', right: 'спів' },
            { left: 'cooking', right: 'готування' },
          ],
        },
        {
          id: 'a2-hb-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мені не подобається бігати.',
          answer: "I don't like running.",
          acceptedAnswers: accepted("I don't like running.", [
            'i do not like running',
          ]),
        },
      ],
    },
    // ─── 5. Weekend Plans ────────────────────────────────────────────
    {
      slug: 'a2-weekend-plans',
      title: 'Weekend Plans',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'a2-routine',
      sectionTitle: 'Юніт 1 · Час',
      sectionOrder: 0,
      topic: 'future-plans',
      steps: [
        {
          id: 'a2-wp-theory',
          type: 'theory',
          title: 'Плани на завтра 📅',
          body: 'Для запланованих майбутніх подій кажемо «be + going to» або present continuous: «I\'m meeting friends» / «I\'m going to visit grandma».',
          examples: [
            { en: "I'm going to visit my grandma.", ua: 'Я збираюсь відвідати бабусю.' },
            { en: "We're meeting friends on Saturday.", ua: 'Ми зустрічаємось з друзями в суботу.' },
            { en: "She's playing tennis tomorrow.", ua: 'Вона завтра гратиме в теніс.' },
          ],
          tip: '💡 «Going to» — конкретний план; «will» — спонтанне рішення / прогноз.',
        },
        {
          id: 'a2-wp-mc1',
          type: 'multiple-choice',
          question: 'Який час для запланованого майбутнього?',
          options: [
            'past simple',
            'present simple',
            'be going to / present continuous',
            "will",
          ],
          correctIndex: 2,
        },
        {
          id: 'a2-wp-mc2',
          type: 'multiple-choice',
          question: '«Завтра я зустрічаюся з другом» — найприродніший варіант:',
          options: [
            'I meet a friend tomorrow',
            "I'm meeting a friend tomorrow",
            'I will meet a friend tomorrow',
            'I met a friend tomorrow',
          ],
          correctIndex: 1,
        },
        {
          id: 'a2-wp-fill',
          type: 'fill-blank',
          before: "We're",
          after: ' to the park on Sunday.',
          answer: 'going',
          hint: '«Be going to + V» для планів.',
        },
        {
          id: 'a2-wp-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я збираюсь дивитись фільм увечері.',
          words: ['watch', "I'm", 'a', 'going', 'movie', 'to', 'tonight'],
          answer: ["I'm", 'going', 'to', 'watch', 'a', 'movie', 'tonight'],
        },
        {
          id: 'a2-wp-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'У суботу ми збираємось до парку.',
          answer: "On Saturday we're going to the park.",
          acceptedAnswers: accepted("On Saturday we're going to the park.", [
            'on saturday we are going to the park',
            "we're going to the park on saturday",
          ]),
        },
      ],
    },
  ],
);

// ═══════════════════════════════════════════════════════════════════════
// B1 — Intermediate (2 courses)
// ═══════════════════════════════════════════════════════════════════════

export const b1TravelStories = shellCourse(
  {
    slug: 'b1-travel-stories',
    createIfMissing: {
      title: 'Travel Stories',
      titleUa: 'Подорожі',
      subtitle: 'B1 · 4 уроки · середній рівень',
      description:
        'Минулі пригоди, аеропорт, твоя найкраща поїздка, культурні відмінності. Past simple regular/irregular, comparative adjectives, «would» для гіпотез.',
      descriptionShort: 'Past simple, аеропорт, культури світу.',
      level: 'B1',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '✈️',
      tags: ['kids', 'b1', 'travel', 'past-simple'],
    },
  },
  [
    {
      slug: 'b1-past-adventures',
      title: 'Past Adventures',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'b1-travel',
      sectionTitle: 'Юніт 1 · Подорожі',
      sectionOrder: 0,
      isFree: true,
      topic: 'past-simple',
      steps: [
        {
          id: 'b1-pa-theory',
          type: 'theory',
          title: 'Минулий час ⏪',
          body: 'Регулярні дієслова: додаємо «-ed» (play → played, walk → walked). Нерегулярні треба запамʼятати: go → went, see → saw, eat → ate.',
          examples: [
            { en: 'I played football yesterday.', ua: 'Я грав у футбол учора.' },
            { en: 'We went to the beach.', ua: 'Ми ходили на пляж.' },
            { en: 'She saw a movie.', ua: 'Вона дивилася фільм.' },
            { en: 'They ate ice cream.', ua: 'Вони їли морозиво.' },
          ],
          tip: '💡 Заперечення: «I didn\'t go» (не ходив).',
        },
        {
          id: 'b1-pa-mc1',
          type: 'multiple-choice',
          question: 'Past simple від «go» — це…',
          options: ['goed', 'went', 'going', 'go-ed'],
          correctIndex: 1,
        },
        {
          id: 'b1-pa-mc2',
          type: 'multiple-choice',
          question: 'А від «play»?',
          options: ['plaied', 'played', 'plaed', 'played-ed'],
          correctIndex: 1,
        },
        {
          id: 'b1-pa-fill',
          type: 'fill-blank',
          before: 'Last summer we',
          after: ' to Spain.',
          answer: 'went',
          hint: 'Past simple від «go».',
        },
        {
          id: 'b1-pa-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай дієслово з його past simple формою:',
          pairs: [
            { left: 'go', right: 'went' },
            { left: 'see', right: 'saw' },
            { left: 'eat', right: 'ate' },
            { left: 'play', right: 'played' },
          ],
        },
        {
          id: 'b1-pa-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Учора я бачив свого друга.',
          answer: 'Yesterday I saw my friend.',
          acceptedAnswers: accepted('Yesterday I saw my friend.', [
            'i saw my friend yesterday',
            'I saw my friend yesterday',
          ]),
        },
      ],
    },
    {
      slug: 'b1-airport',
      title: 'At the Airport',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'b1-travel',
      sectionTitle: 'Юніт 1 · Подорожі',
      sectionOrder: 0,
      topic: 'airport',
      steps: [
        {
          id: 'b1-ap-theory',
          type: 'theory',
          title: 'В аеропорту 🛫',
          body: 'Найкорисніші слова в аеропорту: gate (вихід), boarding (посадка), passport, luggage (багаж), delayed (затримано).',
          examples: [
            { en: 'gate', ua: 'вихід на посадку' },
            { en: 'boarding pass', ua: 'посадковий талон' },
            { en: 'luggage', ua: 'багаж' },
            { en: 'delayed', ua: 'затримано' },
            { en: 'on time', ua: 'вчасно' },
          ],
        },
        {
          id: 'b1-ap-mc1',
          type: 'multiple-choice',
          question: '«Luggage» — це…',
          options: ['літак', 'квиток', 'багаж', 'паспорт'],
          correctIndex: 2,
        },
        {
          id: 'b1-ap-mc2',
          type: 'multiple-choice',
          question: '«Delayed» означає…',
          options: ['скасовано', 'вчасно', 'затримано', 'прибуло'],
          correctIndex: 2,
        },
        {
          id: 'b1-ap-fill',
          type: 'fill-blank',
          before: 'Where is the boarding',
          after: '?',
          answer: 'pass',
          hint: 'Документ, який показуємо при посадці.',
        },
        {
          id: 'b1-ap-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Наш літак затримано.',
          answer: 'Our flight is delayed.',
          acceptedAnswers: accepted('Our flight is delayed.', [
            'our plane is delayed',
            'the flight is delayed',
          ]),
        },
      ],
    },
    // ─── 3. My Best Trip Ever ────────────────────────────────────────
    {
      slug: 'b1-best-trip',
      title: 'My Best Trip Ever',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 11,
      xp: 15,
      sectionSlug: 'b1-travel',
      sectionTitle: 'Юніт 1 · Подорожі',
      sectionOrder: 0,
      topic: 'comparatives',
      steps: [
        {
          id: 'b1-bt-theory',
          type: 'theory',
          title: 'Порівняльний ступінь 🏔️',
          body: 'Коротке прикметник + «-er»: «high → higher». Довге → «more + adj»: «expensive → more expensive». Найвищий: «-est» / «the most»: «highest / the most expensive».',
          examples: [
            { en: 'My trip was longer than yours.', ua: 'Моя поїздка була довшою за твою.' },
            { en: 'Paris is more beautiful than I expected.', ua: 'Париж красивіший, ніж я очікував.' },
            { en: 'It was the best holiday ever!', ua: 'Це були найкращі канікули!' },
          ],
          tip: '💡 Виключення: good → better, bad → worse, far → further/farther.',
        },
        {
          id: 'b1-bt-mc1',
          type: 'multiple-choice',
          question: 'Comparative від «good» — це…',
          options: ['gooder', 'more good', 'better', 'goodest'],
          correctIndex: 2,
        },
        {
          id: 'b1-bt-mc2',
          type: 'multiple-choice',
          question: 'А superlative від «interesting»?',
          options: [
            'interestinger',
            'most interesting',
            'the most interesting',
            'interestingest',
          ],
          correctIndex: 2,
        },
        {
          id: 'b1-bt-fill',
          type: 'fill-blank',
          before: 'This city is',
          after: ' than I expected.',
          answer: 'bigger',
          hint: 'Comparative від «big» — подвоюємо приголосну.',
        },
        {
          id: 'b1-bt-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай прикметник з його comparative формою:',
          pairs: [
            { left: 'big', right: 'bigger' },
            { left: 'good', right: 'better' },
            { left: 'far', right: 'further' },
            { left: 'beautiful', right: 'more beautiful' },
          ],
        },
        {
          id: 'b1-bt-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це була найдовша подорож мого життя.',
          answer: 'It was the longest trip of my life.',
          acceptedAnswers: accepted('It was the longest trip of my life.'),
        },
      ],
    },
    // ─── 4. Different Cultures ───────────────────────────────────────
    {
      slug: 'b1-different-cultures',
      title: 'Different Cultures',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 11,
      xp: 15,
      sectionSlug: 'b1-travel',
      sectionTitle: 'Юніт 1 · Подорожі',
      sectionOrder: 0,
      topic: 'would-hypothetical',
      steps: [
        {
          id: 'b1-dc-theory',
          type: 'theory',
          title: '«Would» для гіпотез 🌐',
          body: '«Would» = «би». Для уявних / умовних ситуацій: «I would visit Japan» = «Я б відвідав Японію». Скорочується як «I\'d».',
          examples: [
            { en: "I'd love to live in Spain.", ua: 'Я б охоче жив в Іспанії.' },
            { en: 'What would you do in Tokyo?', ua: 'Що б ти робив у Токіо?' },
            { en: 'I think I would miss home.', ua: 'Думаю, я б сумував за домом.' },
          ],
          tip: '💡 «Would» + base form (без «to»): «would visit», не «would to visit».',
        },
        {
          id: 'b1-dc-mc1',
          type: 'multiple-choice',
          question: 'Що б ти НЕ сказав?',
          options: [
            'I would love to travel',
            'I would to travel',
            "I'd like to travel",
            'Would you travel?',
          ],
          correctIndex: 1,
        },
        {
          id: 'b1-dc-fill',
          type: 'fill-blank',
          before: "If I had a million, I",
          after: ' travel the world.',
          answer: 'would',
          hint: '«Я б…» — модальне дієслово.',
        },
        {
          id: 'b1-dc-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'culture', right: 'культура' },
            { left: 'tradition', right: 'традиція' },
            { left: 'custom', right: 'звичай' },
            { left: 'language', right: 'мова' },
          ],
        },
        {
          id: 'b1-dc-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я б хотів вивчати японську.',
          words: ['like', 'Japanese', 'I', 'study', 'would', 'to'],
          answer: ['I', 'would', 'like', 'to', 'study', 'Japanese'],
        },
        {
          id: 'b1-dc-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Що б ти зробив на моєму місці?',
          answer: 'What would you do in my place?',
          acceptedAnswers: accepted('What would you do in my place?', [
            'what would you do if you were me',
          ]),
        },
      ],
    },
  ],
);

export const b1TechAroundUs = shellCourse(
  {
    slug: 'b1-tech-around-us',
    createIfMissing: {
      title: 'Technology Around Us',
      titleUa: 'Технології довкола',
      subtitle: 'B1 · 4 уроки · середній рівень',
      description:
        'Сучасна техніка: смартфони, інтернет, штучний інтелект. Модальні дієслова should/must, плюси й мінуси, прогнози майбутнього.',
      descriptionShort: 'Девайси, безпека в інтернеті, прогнози.',
      level: 'B1',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '💻',
      tags: ['kids', 'b1', 'tech', 'modals'],
    },
  },
  [
    {
      slug: 'b1-devices',
      title: 'Devices We Use',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'b1-tech',
      sectionTitle: 'Юніт 1 · Технології',
      sectionOrder: 0,
      isFree: true,
      topic: 'tech-vocab',
      steps: [
        {
          id: 'b1-dv-theory',
          type: 'theory',
          title: 'Девайси 📱',
          body: 'Сучасний словник: phone, tablet, laptop, headphones, charger.',
          examples: [
            { en: 'smartphone', ua: 'смартфон' },
            { en: 'tablet', ua: 'планшет' },
            { en: 'laptop', ua: 'ноутбук' },
            { en: 'headphones', ua: 'навушники' },
            { en: 'charger', ua: 'зарядний пристрій' },
          ],
        },
        {
          id: 'b1-dv-mc1',
          type: 'multiple-choice',
          question: '«Charger» — це…',
          options: ['ноутбук', 'зарядка', 'клавіатура', 'миша'],
          correctIndex: 1,
        },
        {
          id: 'b1-dv-fill',
          type: 'fill-blank',
          before: 'I listen to music with my',
          after: '.',
          answer: 'headphones',
          hint: 'Слухаємо ___ музику.',
        },
        {
          id: 'b1-dv-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'tablet', right: 'планшет' },
            { left: 'laptop', right: 'ноутбук' },
            { left: 'headphones', right: 'навушники' },
            { left: 'charger', right: 'зарядка' },
          ],
        },
        {
          id: 'b1-dv-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мій ноутбук швидкий.',
          answer: 'My laptop is fast.',
          acceptedAnswers: accepted('My laptop is fast.'),
        },
      ],
    },
    {
      slug: 'b1-internet-safety',
      title: 'Internet Safely',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'b1-tech',
      sectionTitle: 'Юніт 1 · Технології',
      sectionOrder: 0,
      topic: 'modals',
      steps: [
        {
          id: 'b1-is-theory',
          type: 'theory',
          title: 'Модальні дієслова 🔒',
          body: '«Should» — варто, краще; «must» — мусиш, обовʼязково; «mustn\'t» — не можна.',
          examples: [
            { en: 'You should use a strong password.', ua: 'Тобі варто використовувати надійний пароль.' },
            { en: 'You must protect your data.', ua: 'Ти мусиш захищати свої дані.' },
            { en: "You mustn't share your password.", ua: 'Не можна ділитись паролем.' },
          ],
          tip: '💡 «Should» — порада, «must» — правило / закон.',
        },
        {
          id: 'b1-is-mc1',
          type: 'multiple-choice',
          question: 'Що сильніше — порада чи заборона?',
          options: ['Should', 'Must / mustn\'t', 'Однакові', 'Ні те, ні те'],
          correctIndex: 1,
        },
        {
          id: 'b1-is-fill',
          type: 'fill-blank',
          before: 'You',
          after: " share your password with anyone!",
          answer: "mustn't",
          hint: 'Жорстка заборона.',
        },
        {
          id: 'b1-is-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'should', right: 'варто' },
            { left: 'must', right: 'мусиш' },
            { left: "mustn't", right: 'не можна' },
            { left: "shouldn't", right: 'краще не' },
          ],
        },
        {
          id: 'b1-is-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Тобі варто бути обережним онлайн.',
          answer: 'You should be careful online.',
          acceptedAnswers: accepted('You should be careful online.'),
        },
      ],
    },
    // ─── 3. Pros and Cons ────────────────────────────────────────────
    {
      slug: 'b1-pros-cons',
      title: 'Pros and Cons',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 11,
      xp: 15,
      sectionSlug: 'b1-tech',
      sectionTitle: 'Юніт 1 · Технології',
      sectionOrder: 0,
      topic: 'opinions',
      steps: [
        {
          id: 'b1-pc-theory',
          type: 'theory',
          title: 'Зважена думка ⚖️',
          body: 'Аргумент «за» — «pro» / «advantage». «Проти» — «con» / «disadvantage». Зʼєднуйте через «on the other hand», «however», «although».',
          examples: [
            { en: 'One advantage is that…', ua: 'Одна перевага в тому, що…' },
            { en: 'However, a disadvantage is…', ua: 'Однак недолік у тому, що…' },
            { en: 'On the other hand…', ua: 'З іншого боку…' },
            { en: 'Although phones are useful, they can distract us.', ua: 'Хоча телефони корисні, вони можуть відволікати.' },
          ],
        },
        {
          id: 'b1-pc-mc1',
          type: 'multiple-choice',
          question: '«Disadvantage» — це…',
          options: ['перевага', 'недолік', 'правило', 'питання'],
          correctIndex: 1,
        },
        {
          id: 'b1-pc-mc2',
          type: 'multiple-choice',
          question: 'Який зʼєднувач показує контраст?',
          options: ['and', 'because', 'however', 'so'],
          correctIndex: 2,
        },
        {
          id: 'b1-pc-fill',
          type: 'fill-blank',
          before: 'On the other',
          after: ', social media can be addictive.',
          answer: 'hand',
          hint: 'Фраза «з іншого ____».',
        },
        {
          id: 'b1-pc-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'advantage', right: 'перевага' },
            { left: 'disadvantage', right: 'недолік' },
            { left: 'however', right: 'однак' },
            { left: 'although', right: 'хоча' },
          ],
        },
        {
          id: 'b1-pc-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Хоча інтернет корисний, він може відволікати.',
          answer: 'Although the internet is useful, it can be distracting.',
          acceptedAnswers: accepted('Although the internet is useful, it can be distracting.'),
        },
      ],
    },
    // ─── 4. My Future Job ────────────────────────────────────────────
    {
      slug: 'b1-future-job',
      title: 'My Future Job',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 11,
      xp: 15,
      sectionSlug: 'b1-tech',
      sectionTitle: 'Юніт 1 · Технології',
      sectionOrder: 0,
      topic: 'will-going-to',
      steps: [
        {
          id: 'b1-fj-theory',
          type: 'theory',
          title: '«Will» vs «going to» 🚀',
          body: '«Will» — спонтанне рішення або прогноз: «I think I\'ll be a doctor». «Going to» — конкретний план / намір: «I\'m going to study medicine».',
          examples: [
            { en: 'I think AI will change everything.', ua: 'Думаю, ШІ все змінить.' },
            { en: "I'm going to learn programming.", ua: 'Я планую вивчати програмування.' },
            { en: 'In 10 years, robots will help us.', ua: 'Через 10 років роботи нам допомагатимуть.' },
          ],
          tip: '💡 «Will» — для прогнозів і спонтанного. «Going to» — план, який вже у голові.',
        },
        {
          id: 'b1-fj-mc1',
          type: 'multiple-choice',
          question: 'Який варіант для конкретного плану?',
          options: ['I will study tonight', "I'm going to study tonight", 'I study tonight', 'I would study tonight'],
          correctIndex: 1,
        },
        {
          id: 'b1-fj-mc2',
          type: 'multiple-choice',
          question: 'А який — для прогнозу?',
          options: [
            'AI is going to change everything',
            "AI's changing everything",
            'AI changes everything',
            'AI will change everything',
          ],
          correctIndex: 3,
        },
        {
          id: 'b1-fj-fill',
          type: 'fill-blank',
          before: 'I think technology',
          after: ' make our lives easier.',
          answer: 'will',
          hint: 'Прогноз — «буде, мабуть».',
        },
        {
          id: 'b1-fj-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай професію з перекладом:',
          pairs: [
            { left: 'engineer', right: 'інженер' },
            { left: 'doctor', right: 'лікар' },
            { left: 'programmer', right: 'програміст' },
            { left: 'scientist', right: 'науковець' },
          ],
        },
        {
          id: 'b1-fj-translate',
          type: 'translate',
          prompt: 'Переклади (з конкретним планом):',
          sentence: 'Я планую стати лікарем.',
          answer: "I'm going to be a doctor.",
          acceptedAnswers: accepted("I'm going to be a doctor.", [
            'i am going to be a doctor',
            "i'm going to become a doctor",
          ]),
        },
      ],
    },
  ],
);

// ═══════════════════════════════════════════════════════════════════════
// B2 — Upper-Intermediate (2 courses)
// ═══════════════════════════════════════════════════════════════════════

export const b2NewsAndSociety = shellCourse(
  {
    slug: 'b2-news-society',
    createIfMissing: {
      title: 'News & Society',
      titleUa: 'Новини та суспільство',
      subtitle: 'B2 · 3 уроки · продвинутий-середній рівень',
      description:
        'Заголовки новин, клімат, волонтерство. Present perfect, passive voice, conditionals — складніша граматика на знайомих темах.',
      descriptionShort: 'Заголовки, клімат, волонтерство.',
      level: 'B2',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '📰',
      tags: ['kids', 'b2', 'news', 'present-perfect'],
    },
  },
  [
    {
      slug: 'b2-news-headlines',
      title: 'Reading News Headlines',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-news',
      sectionTitle: 'Юніт 1 · Сучасність',
      sectionOrder: 0,
      isFree: true,
      topic: 'present-perfect',
      steps: [
        {
          id: 'b2-nh-theory',
          type: 'theory',
          title: 'Present Perfect 🗞️',
          body: '«Have / has + V3» — для подій, які щойно сталися або мають вплив на тепер. Заголовки новин люблять цей час.',
          examples: [
            { en: 'Scientists have discovered a new planet.', ua: 'Вчені відкрили нову планету.' },
            { en: 'The team has won the championship.', ua: 'Команда виграла чемпіонат.' },
            { en: 'I have just finished my homework.', ua: 'Я щойно закінчив домашку.' },
          ],
          tip: '💡 «Just», «already», «yet» — типові слова для present perfect.',
        },
        {
          id: 'b2-nh-mc1',
          type: 'multiple-choice',
          question: 'Виправ помилку: She ___ already finished.',
          options: ['have', 'has', 'is', 'was'],
          correctIndex: 1,
        },
        {
          id: 'b2-nh-fill',
          type: 'fill-blank',
          before: 'They have',
          after: ' a new app.',
          answer: 'launched',
          hint: 'Past participle від «launch» — запустили.',
        },
        {
          id: 'b2-nh-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я щойно прочитав цю новину.',
          answer: "I have just read this news.",
          acceptedAnswers: accepted("I have just read this news.", [
            "i've just read this news",
            "I've just read the news",
          ]),
        },
      ],
    },
    {
      slug: 'b2-climate',
      title: 'Climate & Environment',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-news',
      sectionTitle: 'Юніт 1 · Сучасність',
      sectionOrder: 0,
      topic: 'passive',
      steps: [
        {
          id: 'b2-cl-theory',
          type: 'theory',
          title: 'Пасивний стан 🌍',
          body: '«Trees are planted» — дерева висаджуються. Пасив фокусує увагу на ОБʼЄКТІ дії, а не на тому, хто діє.',
          examples: [
            { en: 'Trees are planted every spring.', ua: 'Дерева висаджуються щовесни.' },
            { en: 'Plastic is recycled in many countries.', ua: 'Пластик переробляється у багатьох країнах.' },
            { en: 'The Earth must be protected.', ua: 'Землю треба захищати.' },
          ],
        },
        {
          id: 'b2-cl-mc1',
          type: 'multiple-choice',
          question: 'Активний → пасивний: «We plant trees»',
          options: [
            'Trees are planted',
            'Trees plant',
            'Trees were planting',
            'Trees plants',
          ],
          correctIndex: 0,
        },
        {
          id: 'b2-cl-fill',
          type: 'fill-blank',
          before: 'Plastic ',
          after: ' recycled in our city.',
          answer: 'is',
          hint: 'Допоміжне «be» в present passive.',
        },
        {
          id: 'b2-cl-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'recycle', right: 'переробляти' },
            { left: 'pollute', right: 'забруднювати' },
            { left: 'protect', right: 'захищати' },
            { left: 'reduce', right: 'зменшувати' },
          ],
        },
        {
          id: 'b2-cl-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Папір перероблюється тут.',
          answer: 'Paper is recycled here.',
          acceptedAnswers: accepted('Paper is recycled here.'),
        },
      ],
    },
    // ─── 3. Volunteering ─────────────────────────────────────────────
    {
      slug: 'b2-volunteering',
      title: 'Volunteering',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-news',
      sectionTitle: 'Юніт 1 · Сучасність',
      sectionOrder: 0,
      topic: 'first-conditional',
      steps: [
        {
          id: 'b2-vt-theory',
          type: 'theory',
          title: 'First Conditional 🤝',
          body: 'Реальна умова: «If + present simple, ... will + V». «If we volunteer, we will help others».',
          examples: [
            { en: 'If we plant trees, the city will be greener.', ua: 'Якщо ми посадимо дерева, місто стане зеленішим.' },
            { en: "If you join us, we'll have more hands.", ua: 'Якщо приєднаєшся, у нас буде більше рук.' },
            { en: 'I will donate if you organize it.', ua: 'Я зроблю пожертву, якщо ти організуєш.' },
          ],
          tip: '💡 First conditional = реальне майбутнє. Second conditional = уявне (would).',
        },
        {
          id: 'b2-vt-mc1',
          type: 'multiple-choice',
          question: 'Виправ: If it ___ tomorrow, we will stay home.',
          options: ['will rain', 'rains', 'rained', 'is raining'],
          correctIndex: 1,
        },
        {
          id: 'b2-vt-mc2',
          type: 'multiple-choice',
          question: '«Volunteer» — це…',
          options: ['робітник', 'волонтер', 'студент', 'інвестор'],
          correctIndex: 1,
        },
        {
          id: 'b2-vt-fill',
          type: 'fill-blank',
          before: 'If we work together, we',
          after: ' make a difference.',
          answer: 'will',
          hint: 'Майбутнє у головній частині.',
        },
        {
          id: 'b2-vt-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'volunteer', right: 'волонтер' },
            { left: 'donate', right: 'жертвувати' },
            { left: 'charity', right: 'благодійність' },
            { left: 'community', right: 'громада' },
          ],
        },
        {
          id: 'b2-vt-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Якщо ми допоможемо, дитина посміхнеться.',
          answer: 'If we help, the child will smile.',
          acceptedAnswers: accepted('If we help, the child will smile.'),
        },
      ],
    },
  ],
);

export const b2BooksMovies = shellCourse(
  {
    slug: 'b2-books-movies',
    createIfMissing: {
      title: 'Books & Movies',
      titleUa: 'Книги і фільми',
      subtitle: 'B2 · 3 уроки · продвинутий-середній рівень',
      description:
        'Розповідаємо історії, рецензуємо фільми, фантазуємо у умовних реченнях. Narrative tenses + conditionals.',
      descriptionShort: 'Narrative tenses, рецензії, conditionals.',
      level: 'B2',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '📚',
      tags: ['kids', 'b2', 'narrative'],
    },
  },
  [
    {
      slug: 'b2-telling-stories',
      title: 'Telling Stories',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-stories',
      sectionTitle: 'Юніт 1 · Розповідь',
      sectionOrder: 0,
      isFree: true,
      topic: 'narrative',
      steps: [
        {
          id: 'b2-ts-theory',
          type: 'theory',
          title: 'Розповідаємо історію 📖',
          body: 'Past simple — основна дія, past continuous — фон («I was reading when…»), past perfect — раніше за минуле («I had finished before…»).',
          examples: [
            { en: 'I was reading when the phone rang.', ua: 'Я читав, коли задзвонив телефон.' },
            { en: 'She had already left when I arrived.', ua: 'Вона вже пішла, коли я прийшов.' },
          ],
        },
        {
          id: 'b2-ts-mc1',
          type: 'multiple-choice',
          question: 'Який час — для тривалої дії в минулому?',
          options: ['past simple', 'past continuous', 'past perfect', 'present perfect'],
          correctIndex: 1,
        },
        {
          id: 'b2-ts-fill',
          type: 'fill-blank',
          before: 'I',
          after: ' a book when she called.',
          answer: 'was reading',
          hint: 'Past continuous: was + V-ing.',
        },
        {
          id: 'b2-ts-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я обідав, коли він прийшов.',
          answer: 'I was having lunch when he came.',
          acceptedAnswers: accepted('I was having lunch when he came.'),
        },
      ],
    },
    {
      slug: 'b2-what-if',
      title: 'What If…?',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-stories',
      sectionTitle: 'Юніт 1 · Розповідь',
      sectionOrder: 0,
      topic: 'conditionals',
      steps: [
        {
          id: 'b2-wi-theory',
          type: 'theory',
          title: 'Умовні речення 💭',
          body: '2nd conditional — нереальна теперішня ситуація: «If I had wings, I would fly». 3rd conditional — нереальне минуле: «If I had studied, I would have passed».',
          examples: [
            { en: 'If I had wings, I would fly.', ua: 'Якби я мав крила, я б літав.' },
            { en: 'If she were here, she would help.', ua: 'Якби вона була тут, вона б допомогла.' },
          ],
        },
        {
          id: 'b2-wi-mc1',
          type: 'multiple-choice',
          question: 'Виправ: If I ___ rich, I would travel a lot.',
          options: ['am', 'were', 'will be', 'be'],
          correctIndex: 1,
        },
        {
          id: 'b2-wi-fill',
          type: 'fill-blank',
          before: 'If I had time, I',
          after: ' learn the piano.',
          answer: 'would',
          hint: '2nd conditional: would + base form.',
        },
        {
          id: 'b2-wi-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Якби я був твоїм другом, я б тобі допоміг.',
          answer: 'If I were your friend, I would help you.',
          acceptedAnswers: accepted('If I were your friend, I would help you.'),
        },
      ],
    },
    // ─── 3. Reviewing a Movie ────────────────────────────────────────
    {
      slug: 'b2-review-movie',
      title: 'Reviewing a Movie',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'b2-stories',
      sectionTitle: 'Юніт 1 · Розповідь',
      sectionOrder: 0,
      topic: 'opinion-language',
      steps: [
        {
          id: 'b2-rm-theory',
          type: 'theory',
          title: 'Мова рецензії 🎬',
          body: 'Складні прикметники: «thrilling» (захопливий), «predictable» (передбачуваний), «moving» (зворушливий), «overrated» (переоцінений).',
          examples: [
            { en: 'The plot was thrilling and unpredictable.', ua: 'Сюжет був захопливим і непередбачуваним.' },
            { en: 'The acting was outstanding.', ua: 'Акторська гра — видатна.' },
            { en: 'Honestly, the film was overrated.', ua: 'Чесно, фільм переоцінений.' },
          ],
          tip: '💡 «-ing» — характеристика речі (boring movie); «-ed» — твій стан (I am bored).',
        },
        {
          id: 'b2-rm-mc1',
          type: 'multiple-choice',
          question: '«The movie was ___» — який варіант правильний?',
          options: ['boring', 'bored', 'bore', 'boringly'],
          correctIndex: 0,
        },
        {
          id: 'b2-rm-mc2',
          type: 'multiple-choice',
          question: '«Predictable» — це…',
          options: ['непередбачуваний', 'передбачуваний', 'дорогий', 'зворушливий'],
          correctIndex: 1,
        },
        {
          id: 'b2-rm-fill',
          type: 'fill-blank',
          before: 'The ending was very',
          after: ' — I cried.',
          answer: 'moving',
          hint: 'Зворушливий.',
        },
        {
          id: 'b2-rm-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай прикметник з перекладом:',
          pairs: [
            { left: 'thrilling', right: 'захопливий' },
            { left: 'predictable', right: 'передбачуваний' },
            { left: 'moving', right: 'зворушливий' },
            { left: 'overrated', right: 'переоцінений' },
          ],
        },
        {
          id: 'b2-rm-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Сюжет був захопливим, але кінцівка передбачувана.',
          answer: 'The plot was thrilling, but the ending was predictable.',
          acceptedAnswers: accepted('The plot was thrilling, but the ending was predictable.'),
        },
      ],
    },
  ],
);

// ═══════════════════════════════════════════════════════════════════════
// C1 — Advanced (1 course)
// ═══════════════════════════════════════════════════════════════════════

export const c1CriticalThinking = shellCourse(
  {
    slug: 'c1-critical-thinking',
    createIfMissing: {
      title: 'Critical Thinking',
      titleUa: 'Критичне мислення',
      subtitle: 'C1 · 3 уроки · продвинутий рівень',
      description:
        'Як розрізняти факти й думки, помічати логічні помилки, писати переконливі тексти. Hedging language, formal register.',
      descriptionShort: 'Факт vs думка, логічні помилки.',
      level: 'C1',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '🧠',
      tags: ['kids', 'c1', 'critical-thinking'],
    },
  },
  [
    {
      slug: 'c1-fact-vs-opinion',
      title: 'Fact vs Opinion',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 14,
      xp: 15,
      sectionSlug: 'c1-think',
      sectionTitle: 'Юніт 1 · Думати уважно',
      sectionOrder: 0,
      isFree: true,
      topic: 'fact-opinion',
      steps: [
        {
          id: 'c1-fo-theory',
          type: 'theory',
          title: 'Факт чи думка? 🧠',
          body: 'Факт можна перевірити. Думка — особиста оцінка. «Water boils at 100°C» — факт. «This song is the best» — думка. Слова hedging («I think», «it seems», «probably») сигналізують про думку.',
          examples: [
            { en: 'The Earth orbits the Sun.', ua: 'Земля обертається навколо Сонця. (факт)' },
            { en: 'Pizza is the best food.', ua: 'Піца — найкраща їжа. (думка)' },
            { en: 'It seems that…', ua: 'Здається, що…' },
            { en: 'In my opinion…', ua: 'На мою думку…' },
          ],
        },
        {
          id: 'c1-fo-mc1',
          type: 'multiple-choice',
          question: 'Що з цього — факт?',
          options: [
            'Coffee is delicious',
            'Coffee contains caffeine',
            'Coffee is the best drink',
            'Coffee should be free',
          ],
          correctIndex: 1,
        },
        {
          id: 'c1-fo-fill',
          type: 'fill-blank',
          before: 'In my',
          after: ', online learning is effective.',
          answer: 'opinion',
          hint: 'Сигнал думки.',
        },
        {
          id: 'c1-fo-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай із значенням:',
          pairs: [
            { left: 'It seems', right: 'Здається' },
            { left: 'I believe', right: 'Я вважаю' },
            { left: 'In fact', right: 'Насправді' },
            { left: 'Apparently', right: 'Очевидно' },
          ],
        },
        {
          id: 'c1-fo-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'На мою думку, це найкраща книга.',
          answer: 'In my opinion, this is the best book.',
          acceptedAnswers: accepted('In my opinion, this is the best book.'),
        },
      ],
    },
    {
      slug: 'c1-fallacies',
      title: 'Logical Fallacies',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 14,
      xp: 15,
      sectionSlug: 'c1-think',
      sectionTitle: 'Юніт 1 · Думати уважно',
      sectionOrder: 0,
      topic: 'fallacies',
      steps: [
        {
          id: 'c1-fl-theory',
          type: 'theory',
          title: 'Помилки в думанні ⚠️',
          body: 'Розглянемо 3 типи: ad hominem (атака на людину, не на аргумент), straw man (спрощення позиції опонента), slippery slope (ланцюгова реакція без доказів).',
          examples: [
            { en: "You can't trust him because he is young. (ad hominem)", ua: 'Йому не можна довіряти, бо він молодий.' },
            { en: 'If we let kids use phones, soon they will forget how to read! (slippery slope)', ua: 'Якщо дозволимо телефони, скоро діти забудуть, як читати!' },
          ],
        },
        {
          id: 'c1-fl-mc1',
          type: 'multiple-choice',
          question: 'Яка це помилка: «Він не може мати рацію — він новачок»?',
          options: ['ad hominem', 'straw man', 'slippery slope', 'правильний аргумент'],
          correctIndex: 0,
        },
        {
          id: 'c1-fl-fill',
          type: 'fill-blank',
          before: 'When someone attacks you instead of your idea, it is called ad',
          after: '.',
          answer: 'hominem',
          hint: 'Латинський термін.',
        },
        {
          id: 'c1-fl-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це не аргумент, це особиста атака.',
          answer: 'This is not an argument, it is a personal attack.',
          acceptedAnswers: accepted('This is not an argument, it is a personal attack.'),
        },
      ],
    },
    // ─── 3. Convincing Writing ───────────────────────────────────────
    {
      slug: 'c1-convincing-writing',
      title: 'Convincing Writing',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 14,
      xp: 15,
      sectionSlug: 'c1-think',
      sectionTitle: 'Юніт 1 · Думати уважно',
      sectionOrder: 0,
      topic: 'discourse-markers',
      steps: [
        {
          id: 'c1-cw-theory',
          type: 'theory',
          title: 'Слова-зчіпки 🔗',
          body: 'Discourse markers звʼязують думки: «firstly / secondly» (упорядкування), «furthermore / moreover» (додавання), «however / nevertheless» (контраст), «therefore / consequently» (висновок).',
          examples: [
            { en: 'Firstly, AI saves time.', ua: 'По-перше, ШІ заощаджує час.' },
            { en: 'Furthermore, it learns from data.', ua: 'Окрім цього, він навчається з даних.' },
            { en: 'However, it can make mistakes.', ua: 'Однак, він може помилятись.' },
            { en: 'Therefore, human review is essential.', ua: 'Отже, людська перевірка є важливою.' },
          ],
          tip: '💡 У formal writing — починаємо з discourse marker + кома.',
        },
        {
          id: 'c1-cw-mc1',
          type: 'multiple-choice',
          question: 'Який зʼєднувач показує висновок?',
          options: ['however', 'moreover', 'therefore', 'firstly'],
          correctIndex: 2,
        },
        {
          id: 'c1-cw-mc2',
          type: 'multiple-choice',
          question: 'А який — для додавання аргументу?',
          options: ['however', 'furthermore', 'although', 'unfortunately'],
          correctIndex: 1,
        },
        {
          id: 'c1-cw-fill',
          type: 'fill-blank',
          before: 'The data is incomplete.',
          after: ', we cannot draw conclusions.',
          answer: 'Therefore',
          hint: 'Висновок з великої літери (з нової теми).',
        },
        {
          id: 'c1-cw-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'firstly', right: 'по-перше' },
            { left: 'furthermore', right: 'окрім цього' },
            { left: 'however', right: 'однак' },
            { left: 'therefore', right: 'отже' },
            { left: 'nevertheless', right: 'все ж таки' },
          ],
        },
        {
          id: 'c1-cw-translate',
          type: 'translate',
          prompt: 'Переклади (з discourse marker):',
          sentence: 'Однак цей аргумент має слабкі сторони.',
          answer: 'However, this argument has weak points.',
          acceptedAnswers: accepted('However, this argument has weak points.'),
        },
      ],
    },
  ],
);

// ═══════════════════════════════════════════════════════════════════════
// C2 — Proficient (1 course)
// ═══════════════════════════════════════════════════════════════════════

export const c2IdiomsAndNuance = shellCourse(
  {
    slug: 'c2-idioms-nuance',
    createIfMissing: {
      title: 'Idioms & Nuance',
      titleUa: 'Ідіоми і нюанси',
      subtitle: 'C2 · 2 уроки · вільне володіння',
      description:
        'Найпоширеніші англійські ідіоми та тонкі відтінки значення. Майже-синоніми, реєстр, іронія.',
      descriptionShort: 'Ідіоми, реєстр, синоніми.',
      level: 'C2',
      audience: 'kids',
      kind: 'course',
      iconEmoji: '✨',
      tags: ['kids', 'c2', 'idioms'],
    },
  },
  [
    {
      slug: 'c2-everyday-idioms',
      title: 'Everyday Idioms',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 14,
      xp: 15,
      sectionSlug: 'c2-nuance',
      sectionTitle: 'Юніт 1 · Тонкощі мови',
      sectionOrder: 0,
      isFree: true,
      topic: 'idioms',
      steps: [
        {
          id: 'c2-ei-theory',
          type: 'theory',
          title: 'Ідіоми у щоденному житті 🎭',
          body: 'Ідіома — фраза, де загальне значення не дорівнює сумі слів. «Break a leg!» = «Удачі!» (актори вірять, що бажати удачі — погана прикмета).',
          examples: [
            { en: 'Break a leg!', ua: 'Удачі! (буквально: «Зламай ногу!»)' },
            { en: "It's a piece of cake.", ua: 'Це елементарно. (буквально: «шматок торту»)' },
            { en: 'Once in a blue moon.', ua: 'Раз на сто років. (буквально: «у блакитному місяці»)' },
            { en: "Bite the bullet.", ua: 'Стиснути зуби й зробити.' },
          ],
        },
        {
          id: 'c2-ei-mc1',
          type: 'multiple-choice',
          question: '«It\'s a piece of cake» означає…',
          options: ['Це смачно', 'Це елементарно', 'Це дорого', 'Це торт'],
          correctIndex: 1,
        },
        {
          id: 'c2-ei-mc2',
          type: 'multiple-choice',
          question: 'А «break a leg»?',
          options: ['Вибач', 'Втікай!', 'Удачі!', 'Зламав'],
          correctIndex: 2,
        },
        {
          id: 'c2-ei-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай ідіому зі значенням:',
          pairs: [
            { left: 'Break a leg!', right: 'Удачі!' },
            { left: 'Piece of cake', right: 'Легко' },
            { left: 'Once in a blue moon', right: 'Дуже рідко' },
            { left: 'Bite the bullet', right: 'Стиснути зуби' },
          ],
        },
        {
          id: 'c2-ei-translate',
          type: 'translate',
          prompt: 'Переклади (англ. ідіомою):',
          sentence: 'Це було дуже легко.',
          answer: 'It was a piece of cake.',
          acceptedAnswers: accepted('It was a piece of cake.'),
        },
      ],
    },
    {
      slug: 'c2-subtle-differences',
      title: 'Subtle Differences',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 14,
      xp: 15,
      sectionSlug: 'c2-nuance',
      sectionTitle: 'Юніт 1 · Тонкощі мови',
      sectionOrder: 0,
      topic: 'register',
      steps: [
        {
          id: 'c2-sd-theory',
          type: 'theory',
          title: 'Майже-синоніми 🎯',
          body: '«Slim» і «skinny» обидва означають «худий», але slim — компліментарне, skinny — нейтрально-негативне. Реєстр (formal/informal) важить.',
          examples: [
            { en: 'slim (positive) / skinny (neutral-negative)', ua: 'стрункий / худющий' },
            { en: 'home (warm) / house (neutral building)', ua: 'дім / будинок' },
            { en: 'tell (neutral) / inform (formal)', ua: 'сказати / повідомити' },
          ],
        },
        {
          id: 'c2-sd-mc1',
          type: 'multiple-choice',
          question: 'Який варіант — комплімент?',
          options: ['skinny', 'slim', 'thin', 'bony'],
          correctIndex: 1,
        },
        {
          id: 'c2-sd-mc2',
          type: 'multiple-choice',
          question: 'У офіційному листі краще:',
          options: ['Hey, just letting you know…', 'I would like to inform you…', 'Hi, just so you know…', 'FYI…'],
          correctIndex: 1,
        },
        {
          id: 'c2-sd-fill',
          type: 'fill-blank',
          before: 'In a formal letter we say "I would like to',
          after: ' you" instead of "tell".',
          answer: 'inform',
          hint: 'Більш офіційно.',
        },
        {
          id: 'c2-sd-translate',
          type: 'translate',
          prompt: 'Переклади (формально):',
          sentence: 'Я хотів би повідомити вам про зміни.',
          answer: 'I would like to inform you about the changes.',
          acceptedAnswers: accepted('I would like to inform you about the changes.'),
        },
      ],
    },
  ],
);
