import type { CourseSeed } from '../types';

/**
 * v2 EXEMPLAR — `a-foundation`.
 *
 * Entry-point A-band course. 8 sequential lessons (~12 substantive
 * steps each) that take a total beginner from "knows nothing" to
 * "can introduce self, describe family, name objects, express simple
 * preferences and say what they do every day".
 *
 * Each lesson follows the v2 step-budget from COURSES.md:
 *   2 theory + 4 mcq + 2 fill-blank + 1 match-pairs + 1 word-order
 *   + 1 translate (+ 1 reading on lessons 4 and 8 — narrative anchors).
 *
 * The lesson sequence is INTENTIONAL — Lesson 4 (Family) reuses the
 * "I am" / "My name is" pattern from Lessons 1–2; Lesson 7 (I Like)
 * builds on the family + objects vocabulary from 4–5; Lesson 8
 * (My Day) is the cumulative recap.
 */

// Tiny helper for translate-step accepted-answers boilerplate.
function accepted(answer: string, extras: string[] = []): string[] {
  const noPunct = answer.replace(/[.!?]$/, '');
  const lc = answer.toLowerCase();
  const lcNoPunct = noPunct.toLowerCase();
  return Array.from(new Set([answer, noPunct, lc, lcNoPunct, ...extras]));
}

export const aFoundation: CourseSeed = {
  slug: 'a-foundation',
  createIfMissing: {
    title: 'English Foundation',
    titleUa: 'Фундамент англійської',
    subtitle: 'A-рівень · 8 уроків · повний старт',
    description:
      'Курс №1 для початківців. За 8 уроків ти навчишся представлятись, розповідати про родину, називати предмети, висловлювати прості вподобання й описувати свій звичайний день. Кожен урок — 10–15 хвилин зосередженого навчання, без зайвих повторів.',
    descriptionShort: 'Привітання, імʼя, родина, предмети, прості вподобання.',
    level: 'A1',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '🌱',
    tags: ['a-band', 'foundation', 'speaking', 'grammar'],
  },
  lessons: [
    // ═══════════════════════════════════════════════════════════════════
    // LESSON 1 · Hello! Names
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-1-hello-names',
      title: "Hello! What's Your Name?",
      orderIndex: 0,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'a-foundation-intro',
      sectionTitle: 'Юніт 1 · Я та інші',
      sectionOrder: 0,
      isFree: true,
      topic: 'greetings-introductions',
      steps: [
        {
          id: 'l1-theory-greetings',
          type: 'theory',
          title: 'Як вітатись 👋',
          body: 'У англійській мові є кілька способів привітатись — і всі вони дуже короткі. «Hello» — нейтрально, можна казати будь-кому. «Hi» — те саме, але дружніше, частіше з друзями. Якщо хочемо привітатись часовоприйнятно, додаємо час дня: «Good morning» (до полудня), «Good afternoon» (з полудня до 17:00), «Good evening» (після 17:00).',
          examples: [
            { en: 'Hello!', ua: 'Привіт!' },
            { en: 'Hi!', ua: 'Привіт! (дружньо)' },
            { en: 'Good morning!', ua: 'Доброго ранку!' },
            { en: 'Good afternoon!', ua: 'Добрий день!' },
            { en: 'Good evening!', ua: 'Доброго вечора!' },
            { en: 'Goodbye!', ua: 'До побачення!' },
            { en: 'See you!', ua: 'До зустрічі!' },
          ],
          tip: '💡 «Good night» — це не привітання, а побажання на ніч (як «На добраніч»).',
        },
        {
          id: 'l1-theory-introducing',
          type: 'theory',
          title: 'Як назвати своє імʼя 🙋',
          body: 'Щоб познайомитись, питають: «What\'s your name?» (Як тебе звати?). Відповідаємо двома способами:\n\n• «My name is + імʼя» — формально й чітко.\n• «I\'m + імʼя» — коротше й дружніше. «I\'m» = скорочення від «I am».\n\nПісля відповіді часто кажуть: «Nice to meet you!» (Приємно познайомитись!).',
          examples: [
            { en: "What's your name?", ua: 'Як тебе звати?' },
            { en: 'My name is Sofia.', ua: 'Мене звати Софія.' },
            { en: "I'm Max.", ua: 'Я Макс.' },
            { en: 'Nice to meet you!', ua: 'Приємно познайомитись!' },
            { en: 'Nice to meet you too!', ua: 'Мені теж приємно!' },
          ],
          tip: '💡 «I\'m» — апостроф ставимо саме перед «m». Не «Im», а «I\'m».',
        },
        {
          id: 'l1-mc-1',
          type: 'multiple-choice',
          question: 'Хтось каже тобі «Hi!». Як відповіси найприродніше?',
          options: ['Goodbye!', 'Hi!', 'Good night!', 'Thanks!'],
          correctIndex: 1,
          explanation: '«Hi» — на «Hi». Те саме слово підходить як відповідь.',
        },
        {
          id: 'l1-mc-2',
          type: 'multiple-choice',
          question: 'О 9:00 ранку зустрічаєш вчителя. Що сказати?',
          options: ['Good evening', 'Good night', 'Good morning', 'Goodbye'],
          correctIndex: 2,
          explanation: 'До полудня — «Good morning». «Good night» — лише перед сном.',
        },
        {
          id: 'l1-mc-3',
          type: 'multiple-choice',
          question: 'Як коротко сказати «Я Анна»?',
          options: ['I am name Anna', "I'm Anna", 'Im Anna', 'Me Anna'],
          correctIndex: 1,
          explanation: '«I\'m Anna» — апостроф обовʼязковий. «Im» без апострофа — помилка.',
        },
        {
          id: 'l1-mc-4',
          type: 'multiple-choice',
          question: 'Що відповіси на «Nice to meet you!»?',
          options: [
            'Thank you, goodbye',
            'Nice to meet you too!',
            'My name is too',
            'Hi, how are you',
          ],
          correctIndex: 1,
          explanation: 'Дзеркальна відповідь: «Nice to meet you too!». Слово «too» = «теж».',
        },
        {
          id: 'l1-fill-1',
          type: 'fill-blank',
          before: "What's your",
          after: '?',
          answer: 'name',
          hint: 'Питання «Як тебе ____?».',
        },
        {
          id: 'l1-fill-2',
          type: 'fill-blank',
          before: '',
          after: " Anna. Nice to meet you!",
          answer: "I'm",
          hint: 'Скорочена форма «I am» — з апострофом.',
        },
        {
          id: 'l1-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай вираз з перекладом:',
          pairs: [
            { left: 'Hello', right: 'Привіт' },
            { left: 'Good morning', right: 'Доброго ранку' },
            { left: 'Good evening', right: 'Доброго вечора' },
            { left: 'Goodbye', right: 'До побачення' },
            { left: 'Nice to meet you', right: 'Приємно познайомитись' },
            { left: 'See you', right: 'До зустрічі' },
          ],
        },
        {
          id: 'l1-order',
          type: 'word-order',
          prompt: 'Склади відповідь на «What\'s your name?»:',
          translation: 'Мене звати Макс.',
          words: ['name', 'My', 'is', 'Max'],
          answer: ['My', 'name', 'is', 'Max'],
        },
        {
          id: 'l1-translate-1',
          type: 'translate',
          prompt: 'Переклади англійською:',
          sentence: 'Привіт! Я Анна. Приємно познайомитись!',
          answer: "Hi! I'm Anna. Nice to meet you!",
          acceptedAnswers: accepted("Hi! I'm Anna. Nice to meet you!", [
            'hi! i am anna. nice to meet you!',
            "hello, i'm anna. nice to meet you",
            "hi i'm anna nice to meet you",
            "hello i'm anna nice to meet you",
          ]),
        },
        {
          id: 'l1-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Як тебе звати?',
          answer: "What's your name?",
          acceptedAnswers: accepted("What's your name?", [
            'what is your name',
            'what is your name?',
            'whats your name',
          ]),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 2 · Where Are You From?
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-2-where-from',
      title: 'Where Are You From?',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'a-foundation-intro',
      sectionTitle: 'Юніт 1 · Я та інші',
      sectionOrder: 0,
      isFree: true,
      topic: 'countries-nationalities',
      steps: [
        {
          id: 'l2-theory-from',
          type: 'theory',
          title: 'Звідки ти? 🌍',
          body: 'Питання «Where are you from?» — «Звідки ти?». Відповідаємо: «I\'m from + країна».\n\nКраїни в англійській завжди пишемо з великої літери: Ukraine, Poland, England, France, Italy, Germany, Spain, Japan.',
          examples: [
            { en: 'Where are you from?', ua: 'Звідки ти?' },
            { en: "I'm from Ukraine.", ua: 'Я з України.' },
            { en: "She's from Poland.", ua: 'Вона з Польщі.' },
            { en: 'They are from Italy.', ua: 'Вони з Італії.' },
          ],
          tip: '💡 Прислівник «from» = «з». Без нього не вийде сказати, звідки людина.',
        },
        {
          id: 'l2-theory-nationalities',
          type: 'theory',
          title: 'Національність 🇺🇦',
          body: 'Окрім назви країни є ще «національність» — прикметник: «I\'m Ukrainian» = «Я українець / українка».\n\nДеякі національності утворюються від країни додаванням -ian, -ish, -an: Ukraine → Ukrainian, Poland → Polish, Spain → Spanish, Italy → Italian, America → American.\n\nУсі національності з ВЕЛИКОЇ літери — як і країни.',
          examples: [
            { en: "I'm Ukrainian.", ua: 'Я українець / українка.' },
            { en: "He's Italian.", ua: 'Він італієць.' },
            { en: "She's American.", ua: 'Вона американка.' },
            { en: "We're Polish.", ua: 'Ми поляки.' },
          ],
          tip: '💡 Можна сказати або «I\'m from Ukraine», або «I\'m Ukrainian» — однаково правильно.',
        },
        {
          id: 'l2-mc-1',
          type: 'multiple-choice',
          question: 'Як спитати у нового друга, з якої він країни?',
          options: [
            'Where you are from?',
            'Where are you from?',
            'From where you?',
            'You are where from?',
          ],
          correctIndex: 1,
          explanation: 'Структура: Where + are + you + from. Дієслово «are» — на 2-му місці.',
        },
        {
          id: 'l2-mc-2',
          type: 'multiple-choice',
          question: 'Виправ помилку: «He is from france.»',
          options: [
            'France треба з великої літери',
            '«From» зайве',
            '«Is» неправильно',
            'Все правильно',
          ],
          correctIndex: 0,
          explanation: 'Усі країни — з великої: France, Italy, Spain.',
        },
        {
          id: 'l2-mc-3',
          type: 'multiple-choice',
          question: 'Звідки слово «Ukrainian»?',
          options: ['Це країна', 'Це національність', 'Це місто', 'Це мова'],
          correctIndex: 1,
          explanation: '«Ukraine» — країна, «Ukrainian» — національність / прикметник.',
        },
        {
          id: 'l2-mc-4',
          type: 'multiple-choice',
          question: 'Як сказати «Вони з Польщі»?',
          options: [
            "They're from Polish",
            "They're from Poland",
            "They're Poland",
            'They Poland from',
          ],
          correctIndex: 1,
          explanation: 'Після «from» — країна (Poland), не національність (Polish).',
        },
        {
          id: 'l2-fill-1',
          type: 'fill-blank',
          before: 'Where are you',
          after: '?',
          answer: 'from',
          hint: 'Прислівник, який означає «з».',
        },
        {
          id: 'l2-fill-2',
          type: 'fill-blank',
          before: "I'm from",
          after: '.',
          answer: 'Ukraine',
          hint: 'Назва нашої країни — з великої літери.',
        },
        {
          id: 'l2-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай країну з національністю:',
          pairs: [
            { left: 'Ukraine', right: 'Ukrainian' },
            { left: 'Poland', right: 'Polish' },
            { left: 'Italy', right: 'Italian' },
            { left: 'Spain', right: 'Spanish' },
            { left: 'America', right: 'American' },
            { left: 'Germany', right: 'German' },
          ],
        },
        {
          id: 'l2-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я з України.',
          words: ['Ukraine', "I'm", 'from'],
          answer: ["I'm", 'from', 'Ukraine'],
        },
        {
          id: 'l2-translate-1',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Привіт! Я Макс. Я з України.',
          answer: "Hi! I'm Max. I'm from Ukraine.",
          acceptedAnswers: accepted("Hi! I'm Max. I'm from Ukraine.", [
            "hi i'm max i'm from ukraine",
            "hello, i'm max. i'm from ukraine",
            "hi i'm max. i'm from ukraine",
          ]),
        },
        {
          id: 'l2-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Він італієць.',
          answer: "He's Italian.",
          acceptedAnswers: accepted("He's Italian.", [
            'he is italian',
            "he's italian",
            'he is italian.',
          ]),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 3 · Numbers & Age
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-3-numbers-age',
      title: 'Numbers & Age',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 13,
      xp: 15,
      sectionSlug: 'a-foundation-intro',
      sectionTitle: 'Юніт 1 · Я та інші',
      sectionOrder: 0,
      topic: 'numbers',
      steps: [
        {
          id: 'l3-theory-numbers',
          type: 'theory',
          title: 'Числа 1–20 🔢',
          body: 'Спочатку 1–10: one, two, three, four, five, six, seven, eight, nine, ten.\n\nПотім 11–12 — особливі: eleven, twelve.\n\nВід 13 до 19 — додаємо «-teen» до основного числа: thirteen (3+teen), fourteen (4+teen), fifteen (5+teen)...\n\n20 — twenty.',
          examples: [
            { en: 'one, two, three', ua: '1, 2, 3' },
            { en: 'four, five, six', ua: '4, 5, 6' },
            { en: 'seven, eight, nine', ua: '7, 8, 9' },
            { en: 'ten', ua: '10' },
            { en: 'eleven, twelve', ua: '11, 12' },
            { en: 'thirteen, fourteen, fifteen', ua: '13, 14, 15' },
            { en: 'sixteen, seventeen', ua: '16, 17' },
            { en: 'eighteen, nineteen, twenty', ua: '18, 19, 20' },
          ],
          tip: '💡 Букву «h» в «eighteen» / «eight» НЕ читаємо — звучить як «ейт».',
        },
        {
          id: 'l3-theory-age',
          type: 'theory',
          title: 'Скільки тобі років? 🎂',
          body: 'Питання: «How old are you?» — буквально «Який ти старий?», тобто «Скільки тобі років?».\n\nВідповідь: «I\'m + число + (years old)». Слово «years old» можна опустити: «I\'m ten».',
          examples: [
            { en: 'How old are you?', ua: 'Скільки тобі років?' },
            { en: "I'm ten years old.", ua: 'Мені десять років.' },
            { en: "I'm ten.", ua: 'Мені десять.' },
            { en: 'How old is your sister?', ua: 'Скільки років твоїй сестрі?' },
            { en: "She's seven.", ua: 'Їй сім.' },
          ],
          tip: '💡 «Years old» — лише множина. Не «year old», навіть якщо рік один.',
        },
        {
          id: 'l3-mc-1',
          type: 'multiple-choice',
          question: 'Що таке «fifteen»?',
          options: ['5', '15', '50', '500'],
          correctIndex: 1,
          explanation: 'fifteen = five + teen → 15. Усі «-teen» = 13–19.',
        },
        {
          id: 'l3-mc-2',
          type: 'multiple-choice',
          question: 'Скільки буде «seven + ten»?',
          options: ['seventeen', 'seventy', 'seven-ten', 'twenty'],
          correctIndex: 0,
          explanation: '7 + 10 = 17 = seventeen.',
        },
        {
          id: 'l3-mc-3',
          type: 'multiple-choice',
          question: 'Як спитати про вік сестри?',
          options: [
            'How old is your sister?',
            'How old are your sister?',
            'How is old your sister?',
            'Your sister how old?',
          ],
          correctIndex: 0,
          explanation: '«Sister» — одна, тому «is» (одна особа), не «are» (кілька).',
        },
        {
          id: 'l3-mc-4',
          type: 'multiple-choice',
          question: 'Виправ: «I am ten year old.»',
          options: [
            "Має бути «I'm 10», без «year»",
            'Має бути «years old», з «s»',
            'Помилки немає',
            'Має бути «old years»',
          ],
          correctIndex: 1,
          explanation: 'Правило: завжди «years old» (множина), навіть для одного року.',
        },
        {
          id: 'l3-fill-1',
          type: 'fill-blank',
          before: 'How',
          after: ' are you?',
          answer: 'old',
          hint: 'Питання про вік.',
        },
        {
          id: 'l3-fill-2',
          type: 'fill-blank',
          before: "I'm twelve",
          after: ' old.',
          answer: 'years',
          hint: 'Множина від «year».',
        },
        {
          id: 'l3-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай число з цифрою:',
          pairs: [
            { left: 'three', right: '3' },
            { left: 'eight', right: '8' },
            { left: 'eleven', right: '11' },
            { left: 'fifteen', right: '15' },
            { left: 'eighteen', right: '18' },
            { left: 'twenty', right: '20' },
          ],
        },
        {
          id: 'l3-order',
          type: 'word-order',
          prompt: 'Склади відповідь на «How old are you?»:',
          translation: 'Мені одинадцять років.',
          words: ['old', "I'm", 'eleven', 'years'],
          answer: ["I'm", 'eleven', 'years', 'old'],
        },
        {
          id: 'l3-translate-1',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Скільки тобі років?',
          answer: 'How old are you?',
          acceptedAnswers: accepted('How old are you?', [
            'how old are you',
            'how old are you?',
          ]),
        },
        {
          id: 'l3-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Мені вісім років.',
          answer: "I'm eight years old.",
          acceptedAnswers: accepted("I'm eight years old.", [
            'i am eight years old',
            "i'm 8 years old",
            'i am 8',
            "i'm eight",
          ]),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 4 · My Family (with reading)
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-4-my-family',
      title: 'My Family',
      orderIndex: 3,
      type: 'interactive',
      durationMin: 15,
      xp: 15,
      sectionSlug: 'a-foundation-relationships',
      sectionTitle: 'Юніт 2 · Близькі люди й речі',
      sectionOrder: 1,
      topic: 'family-possessives',
      steps: [
        {
          id: 'l4-theory-vocab',
          type: 'theory',
          title: 'Слова про родину 👨‍👩‍👧',
          body: 'Найважливіші слова, з якими ти познайомиш будь-кого зі своєю родиною:\n\n• mom / dad — мама / тато (дитячі форми, дуже теплі).\n• mother / father — більш формально.\n• sister / brother — сестра / брат.\n• grandma / grandpa — бабуся / дідусь.\n• aunt / uncle — тіточка / дядько.\n• cousin — кузен або кузина (рід не важить!).\n• parents — батьки разом.',
          examples: [
            { en: 'mom / mother', ua: 'мама' },
            { en: 'dad / father', ua: 'тато' },
            { en: 'sister', ua: 'сестра' },
            { en: 'brother', ua: 'брат' },
            { en: 'grandma / grandpa', ua: 'бабуся / дідусь' },
            { en: 'aunt / uncle', ua: 'тіточка / дядько' },
            { en: 'cousin', ua: 'кузен / кузина' },
          ],
          tip: '💡 Англійський «cousin» — будь-якої статі. Один корінь — одне слово.',
        },
        {
          id: 'l4-theory-possessives',
          type: 'theory',
          title: 'Чий — мій / його / її 🔑',
          body: 'Щоб сказати «мій тато» / «її мама», використовуємо присвійні займенники:\n\n• my — мій / моя / моє / мої (від «I»)\n• your — твій / твоя… (від «you»)\n• his — його (від «he»)\n• her — її (від «she»)\n• our — наш (від «we»)\n• their — їхній (від «they»)\n\nСтавимо ПЕРЕД іменником: «my mom», «her sister».\n\nЩе можна сказати «This is my dad» (Це мій тато) — слово «this» = «це».',
          examples: [
            { en: 'This is my mom.', ua: 'Це моя мама.' },
            { en: 'His name is Tom.', ua: 'Його звати Том.' },
            { en: 'Her sister is six.', ua: 'Її сестрі шість років.' },
            { en: 'Our family is big.', ua: 'Наша родина велика.' },
          ],
          tip: '💡 «Her» = «її» AND «їй» — у англійській одне слово на обидва значення.',
        },
        {
          id: 'l4-mc-1',
          type: 'multiple-choice',
          question: 'Брат твоєї мами — це твій…',
          options: ['cousin', 'brother', 'uncle', 'grandpa'],
          correctIndex: 2,
          explanation: 'Брат мами або тата — uncle (дядько).',
        },
        {
          id: 'l4-mc-2',
          type: 'multiple-choice',
          question: 'Як сказати «його мама»?',
          options: ['her mom', 'his mom', 'their mom', 'our mom'],
          correctIndex: 1,
          explanation: '«His» — від «he» (він). «Her» — від «she» (вона).',
        },
        {
          id: 'l4-mc-3',
          type: 'multiple-choice',
          question: 'Хто такі «parents»?',
          options: ['діти', 'дідусі та бабусі', 'батьки', 'усі родичі'],
          correctIndex: 2,
          explanation: '«Parents» = mom + dad разом.',
        },
        {
          id: 'l4-mc-4',
          type: 'multiple-choice',
          question: 'Виправ: «This is she sister.»',
          options: [
            '«She» → «her»',
            '«Sister» → «sisters»',
            '«This» → «that»',
            'Все правильно',
          ],
          correctIndex: 0,
          explanation: 'Перед іменником ставимо присвійну форму: «her sister», не «she sister».',
        },
        {
          id: 'l4-fill-1',
          type: 'fill-blank',
          before: 'This is',
          after: " mom. Her name is Olha.",
          answer: 'my',
          hint: 'Присвійний займенник від «I».',
        },
        {
          id: 'l4-fill-2',
          type: 'fill-blank',
          before: 'His',
          after: ' is twelve. His brother is Max.',
          answer: 'sister',
          hint: 'Дівчинка-родичка.',
        },
        {
          id: 'l4-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай слово з перекладом:',
          pairs: [
            { left: 'mom', right: 'мама' },
            { left: 'dad', right: 'тато' },
            { left: 'grandma', right: 'бабуся' },
            { left: 'aunt', right: 'тіточка' },
            { left: 'uncle', right: 'дядько' },
            { left: 'cousin', right: 'кузен/кузина' },
            { left: 'parents', right: 'батьки' },
          ],
        },
        {
          id: 'l4-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Це моя бабуся. Її звати Ніна.',
          words: ['name', 'is', 'This', 'my', 'is', 'grandma', 'Her', 'Nina'],
          answer: ['This', 'is', 'my', 'grandma', 'Her', 'name', 'is', 'Nina'],
        },
        {
          id: 'l4-reading',
          type: 'reading',
          title: "Sofia's Family",
          text: "Hi! My name is Sofia. I'm ten years old. I'm from Ukraine.\n\nThis is my family. I have a mom, a dad, a brother and a sister. My mom's name is Olha. She is a teacher. My dad's name is Andrii. He is a doctor.\n\nMy brother is fourteen. His name is Roman. He likes football. My sister is six. Her name is Maria. She is small but very funny.\n\nI also have a grandma and a grandpa. They live in Lviv. We visit them every summer.",
          vocabulary: [
            { word: 'teacher', translation: 'вчителька / вчитель' },
            { word: 'doctor', translation: 'лікар / лікарка' },
            { word: 'visit', translation: 'відвідувати' },
            { word: 'every summer', translation: 'щоліта' },
            { word: 'funny', translation: 'веселий' },
            { word: 'small', translation: 'маленький' },
            { word: 'live', translation: 'жити' },
          ],
          questions: [
            {
              id: 'l4-q1',
              question: 'Скільки років Софії?',
              options: ['6', '10', '14', '20'],
              correctIndex: 1,
              explanation: 'У тексті: "I\'m ten years old".',
            },
            {
              id: 'l4-q2',
              question: 'Чим займається мама Софії?',
              options: ['Вона лікарка', 'Вона вчителька', 'Вона мати-домогосподарка', 'У тексті не сказано'],
              correctIndex: 1,
              explanation: '«My mom\'s name is Olha. She is a teacher».',
            },
            {
              id: 'l4-q3',
              question: 'Хто живе у Львові?',
              options: ['Софія і її батьки', 'Її брат Роман', 'Бабуся й дідусь', 'Її сестра Марія'],
              correctIndex: 2,
              explanation: '«I also have a grandma and a grandpa. They live in Lviv».',
            },
          ],
        },
        {
          id: 'l4-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це мій брат. Його звати Тарас.',
          answer: "This is my brother. His name is Taras.",
          acceptedAnswers: accepted("This is my brother. His name is Taras.", [
            'this is my brother his name is taras',
            "this is my brother. his name's taras",
          ]),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 5 · What's This?
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-5-whats-this',
      title: "What's This?",
      orderIndex: 4,
      type: 'interactive',
      durationMin: 13,
      xp: 15,
      sectionSlug: 'a-foundation-relationships',
      sectionTitle: 'Юніт 2 · Близькі люди й речі',
      sectionOrder: 1,
      topic: 'objects-articles',
      steps: [
        {
          id: 'l5-theory-objects',
          type: 'theory',
          title: 'Звичайні речі довкола ✏️',
          body: 'Перші слова, які ти часто бачиш кожного дня: book (книжка), pen (ручка), bag (сумка), phone (телефон), table (стіл), chair (стілець), door (двері), window (вікно).\n\nЩоб запитати «Що це?», скажи: «What\'s this?» (для предмета поруч) або «What\'s that?» (для предмета далі).',
          examples: [
            { en: "What's this?", ua: 'Що це? (поруч)' },
            { en: "What's that?", ua: 'Що то? (далі)' },
            { en: "It's a book.", ua: 'Це книжка.' },
            { en: "It's a pen.", ua: 'Це ручка.' },
          ],
          tip: '💡 «It\'s» = скорочено від «it is». «It» = «воно» — для речей.',
        },
        {
          id: 'l5-theory-articles',
          type: 'theory',
          title: 'a / an / the — артиклі ☝️',
          body: 'Перед іменником у англійській майже завжди є маленьке слово — артикль:\n\n• «a» — перед приголосною: a book, a pen, a chair.\n• «an» — перед голосною (a, e, i, o, u): an apple, an egg, an umbrella.\n• «the» — коли мова про КОНКРЕТНУ річ, яку обидва знаємо: «open the door» (ту саму двері).\n\nКоли вперше згадуємо предмет — ставимо «a» / «an». Коли знову — «the».',
          examples: [
            { en: 'a book', ua: 'книжка (якась, не вказана)' },
            { en: 'an apple', ua: 'яблуко (одне)' },
            { en: 'the apple', ua: 'те саме яблуко (про яке вже говорили)' },
            { en: "I have a pen. The pen is blue.", ua: 'У мене є ручка. Ця ручка синя.' },
          ],
          tip: '💡 Винятки: «an hour» (h не читається — голосний звук). Слухай ЗВУК, не літеру.',
        },
        {
          id: 'l5-mc-1',
          type: 'multiple-choice',
          question: 'Що сказати про яблуко (вперше згадане)?',
          options: ['It is a apple', 'It is an apple', 'It is the apple', 'It apple'],
          correctIndex: 1,
          explanation: '«Apple» починається з голосного — «an».',
        },
        {
          id: 'l5-mc-2',
          type: 'multiple-choice',
          question: 'Як показати на стіл, який ВЖЕ згадувався?',
          options: ['a table', 'an table', 'the table', 'table'],
          correctIndex: 2,
          explanation: '«The» — для конкретного, вже відомого предмета.',
        },
        {
          id: 'l5-mc-3',
          type: 'multiple-choice',
          question: 'Спитай про предмет біля себе:',
          options: ["What's that?", "What's this?", "Where this?", "How this?"],
          correctIndex: 1,
          explanation: '«This» — близько (поруч), «that» — далі.',
        },
        {
          id: 'l5-mc-4',
          type: 'multiple-choice',
          question: 'Виправ: «I have a egg».',
          options: [
            'a → an (egg починається з голосного)',
            'a → the',
            '«have» → «has»',
            'Помилки немає',
          ],
          correctIndex: 0,
          explanation: '«Egg» — голосний звук на початку, тому «an egg».',
        },
        {
          id: 'l5-fill-1',
          type: 'fill-blank',
          before: 'I have',
          after: ' umbrella.',
          answer: 'an',
          hint: 'Голосна перед «umbrella».',
        },
        {
          id: 'l5-fill-2',
          type: 'fill-blank',
          before: '',
          after: " is this? — It's a chair.",
          answer: 'What',
          hint: 'Питальне слово «що».',
        },
        {
          id: 'l5-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'book', right: 'книжка' },
            { left: 'pen', right: 'ручка' },
            { left: 'bag', right: 'сумка' },
            { left: 'phone', right: 'телефон' },
            { left: 'door', right: 'двері' },
            { left: 'window', right: 'вікно' },
            { left: 'chair', right: 'стілець' },
          ],
        },
        {
          id: 'l5-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Це яблуко. Воно червоне.',
          words: ['red', 'apple', 'is', "It's", 'an', 'It'],
          answer: ["It's", 'an', 'apple', 'It', 'is', 'red'],
        },
        {
          id: 'l5-translate-1',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Що це? — Це ручка.',
          answer: "What's this? — It's a pen.",
          acceptedAnswers: accepted("What's this? — It's a pen.", [
            "what is this it's a pen",
            "what's this? it's a pen",
            "whats this its a pen",
          ]),
        },
        {
          id: 'l5-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'У мене є яблуко.',
          answer: 'I have an apple.',
          acceptedAnswers: accepted('I have an apple.'),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 6 · Colors & Sizes
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-6-colors-sizes',
      title: 'Colors & Sizes',
      orderIndex: 5,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'a-foundation-relationships',
      sectionTitle: 'Юніт 2 · Близькі люди й речі',
      sectionOrder: 1,
      topic: 'descriptors',
      steps: [
        {
          id: 'l6-theory-colors',
          type: 'theory',
          title: 'Кольори 🎨',
          body: 'Базові кольори: red (червоний), blue (синій), green (зелений), yellow (жовтий), black (чорний), white (білий), orange, pink, brown, grey.\n\nЩоб описати річ, кажемо: «It is + колір» або «The + річ + is + колір»: «The car is red».',
          examples: [
            { en: 'The sky is blue.', ua: 'Небо синє.' },
            { en: 'My dog is brown.', ua: 'Мій собака коричневий.' },
            { en: 'The sun is yellow.', ua: 'Сонце жовте.' },
            { en: 'Snow is white.', ua: 'Сніг білий.' },
          ],
          tip: '💡 Колір ставимо ПІСЛЯ «is»: «The car is red», а не «The red car is».',
        },
        {
          id: 'l6-theory-adjectives',
          type: 'theory',
          title: 'Великий, маленький, високий 📏',
          body: 'Прикметники описують річ — її розмір, форму, відчуття:\n\n• big — великий, small — маленький.\n• tall — високий (про людей чи будівлі), short — низький.\n• long — довгий, short — короткий.\n• new — новий, old — старий.\n• hot — гарячий, cold — холодний.\n\nСтавимо ПЕРЕД іменником: «a big dog», «a small cat». Або після «is»: «The dog is big».',
          examples: [
            { en: 'a big house', ua: 'великий будинок' },
            { en: 'a small cat', ua: 'маленький кіт' },
            { en: 'My grandpa is tall.', ua: 'Мій дідусь високий.' },
            { en: 'This book is new.', ua: 'Ця книжка нова.' },
            { en: 'The tea is hot.', ua: 'Чай гарячий.' },
          ],
          tip: '💡 «Short» = і «низький» (про людей), і «короткий» (про предмети). Контекст вирішує.',
        },
        {
          id: 'l6-mc-1',
          type: 'multiple-choice',
          question: 'Якого кольору трава?',
          options: ['blue', 'red', 'green', 'yellow'],
          correctIndex: 2,
        },
        {
          id: 'l6-mc-2',
          type: 'multiple-choice',
          question: 'Виправ: «I have a red big car».',
          options: [
            'Спочатку розмір, потім колір: a big red car',
            'Не «red», а «pink»',
            'Не «have», а «has»',
            'Все правильно',
          ],
          correctIndex: 0,
          explanation: 'У англійській порядок прикметників: розмір → колір → інше. «A big red car».',
        },
        {
          id: 'l6-mc-3',
          type: 'multiple-choice',
          question: '«Hot» — це…',
          options: ['холодний', 'гарячий', 'смачний', 'старий'],
          correctIndex: 1,
        },
        {
          id: 'l6-mc-4',
          type: 'multiple-choice',
          question: 'Як сказати «маленький білий собака»?',
          options: [
            'a white small dog',
            'a small white dog',
            'a small dog white',
            'a dog small white',
          ],
          correctIndex: 1,
          explanation: 'Розмір (small) → колір (white) → іменник (dog).',
        },
        {
          id: 'l6-fill-1',
          type: 'fill-blank',
          before: 'A mouse is',
          after: '.',
          answer: 'small',
          hint: 'Миша яка?',
        },
        {
          id: 'l6-fill-2',
          type: 'fill-blank',
          before: 'The sky is',
          after: '.',
          answer: 'blue',
          hint: 'Колір неба.',
        },
        {
          id: 'l6-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай протилежності:',
          pairs: [
            { left: 'big', right: 'small' },
            { left: 'tall', right: 'short' },
            { left: 'new', right: 'old' },
            { left: 'hot', right: 'cold' },
            { left: 'long', right: 'short' },
            { left: 'black', right: 'white' },
          ],
        },
        {
          id: 'l6-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене великий чорний пес.',
          words: ['have', 'a', 'I', 'big', 'dog', 'black'],
          answer: ['I', 'have', 'a', 'big', 'black', 'dog'],
        },
        {
          id: 'l6-translate-1',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Моя сумка маленька і зелена.',
          answer: 'My bag is small and green.',
          acceptedAnswers: accepted('My bag is small and green.'),
        },
        {
          id: 'l6-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Це нова книжка. Вона біла.',
          answer: "It's a new book. It's white.",
          acceptedAnswers: accepted("It's a new book. It's white.", [
            'it is a new book it is white',
            "it's a new book. it is white",
          ]),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 7 · I Like / I Don't
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-7-i-like',
      title: "I Like / I Don't",
      orderIndex: 6,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'a-foundation-action',
      sectionTitle: 'Юніт 3 · Що я роблю',
      sectionOrder: 2,
      topic: 'preferences-negation',
      steps: [
        {
          id: 'l7-theory-like',
          type: 'theory',
          title: 'Що мені подобається ❤️',
          body: 'Слово «like» — основне для вподобань: «I like + щось» = «Мені подобається…».\n\nЯкщо подобається ДУЖЕ, кажемо «love» замість «like». Якщо НЕ подобається — додаємо «don\'t»: «I don\'t like».\n\nПісля «like / love» можна ставити:\n• Іменник: «I like cats» (Я люблю котів).\n• Дієслово з -ing: «I like reading» (Я люблю читати).',
          examples: [
            { en: 'I like apples.', ua: 'Мені подобаються яблука.' },
            { en: 'I love football.', ua: 'Я обожнюю футбол.' },
            { en: "I don't like spiders.", ua: 'Я не люблю павуків.' },
            { en: 'I like reading books.', ua: 'Я люблю читати книжки.' },
          ],
          tip: '💡 «Don\'t» = «do not». Скорочення — апостроф обовʼязковий.',
        },
        {
          id: 'l7-theory-questions',
          type: 'theory',
          title: 'Запитуємо, чи подобається ❓',
          body: 'Щоб спитати, чи подобається щось іншому, додаємо «do» на початок:\n\n• «Do you like + щось?» — «Тобі подобається…?»\n\nВідповіді:\n• «Yes, I do.» — Так, подобається.\n• «No, I don\'t.» — Ні, не подобається.\n\nКоротко й чітко.',
          examples: [
            { en: 'Do you like cats?', ua: 'Ти любиш котів?' },
            { en: 'Yes, I do.', ua: 'Так.' },
            { en: 'Do you like spiders?', ua: 'Ти любиш павуків?' },
            { en: "No, I don't.", ua: 'Ні.' },
          ],
          tip: '💡 У відповіді не повторюй «like» — досить «I do» або «I don\'t».',
        },
        {
          id: 'l7-mc-1',
          type: 'multiple-choice',
          question: 'Як сказати «Я не люблю молоко»?',
          options: [
            'I no like milk',
            "I don't like milk",
            'I not like milk',
            'I like not milk',
          ],
          correctIndex: 1,
          explanation: '«Don\'t» — стандартна форма заперечення з «I / you / we / they».',
        },
        {
          id: 'l7-mc-2',
          type: 'multiple-choice',
          question: 'Спитай у друга, чи любить він спорт:',
          options: [
            'You like sport?',
            'Do you like sport?',
            'Are you like sport?',
            'Like you sport?',
          ],
          correctIndex: 1,
          explanation: 'Питання починається з «Do» для дієслів типу «like».',
        },
        {
          id: 'l7-mc-3',
          type: 'multiple-choice',
          question: 'У відповідь на «Do you like ice cream?» якщо так:',
          options: ['Yes, I am', 'Yes, I do', 'Yes, I like', 'Yes, like'],
          correctIndex: 1,
          explanation: 'Відповідь повторює допоміжне дієслово: «Do you…?» → «Yes, I do».',
        },
        {
          id: 'l7-mc-4',
          type: 'multiple-choice',
          question: 'Що краще після «like»: «read» чи «reading»?',
          options: [
            "Тільки «read»",
            "Тільки «reading»",
            'Краще з -ing: «I like reading»',
            "Без різниці",
          ],
          correctIndex: 2,
          explanation: 'Класична правило A1/A2: після «like / love / hate» — V-ing.',
        },
        {
          id: 'l7-fill-1',
          type: 'fill-blank',
          before: 'I',
          after: ' like apples.',
          answer: "don't",
          hint: 'Заперечення — скорочена форма.',
        },
        {
          id: 'l7-fill-2',
          type: 'fill-blank',
          before: '',
          after: ' you like cats?',
          answer: 'Do',
          hint: 'Допоміжне дієслово на початку питання.',
        },
        {
          id: 'l7-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай:',
          pairs: [
            { left: 'I like', right: 'мені подобається' },
            { left: 'I love', right: 'я обожнюю' },
            { left: "I don't like", right: 'мені не подобається' },
            { left: 'Do you like…?', right: 'Тобі подобається…?' },
            { left: 'Yes, I do', right: 'Так' },
            { left: "No, I don't", right: 'Ні' },
          ],
        },
        {
          id: 'l7-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я люблю читати книжки.',
          words: ['I', 'reading', 'books', 'like'],
          answer: ['I', 'like', 'reading', 'books'],
        },
        {
          id: 'l7-translate-1',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я обожнюю шоколад.',
          answer: 'I love chocolate.',
          acceptedAnswers: accepted('I love chocolate.', [
            'i really like chocolate',
          ]),
        },
        {
          id: 'l7-translate-2',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Ти любиш собак?',
          answer: 'Do you like dogs?',
          acceptedAnswers: accepted('Do you like dogs?'),
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════
    // LESSON 8 · My Day (recap with reading)
    // ═══════════════════════════════════════════════════════════════════
    {
      slug: 'a-foundation-8-my-day',
      title: 'My Day',
      orderIndex: 7,
      type: 'interactive',
      durationMin: 15,
      xp: 15,
      sectionSlug: 'a-foundation-action',
      sectionTitle: 'Юніт 3 · Що я роблю',
      sectionOrder: 2,
      topic: 'present-simple-recap',
      steps: [
        {
          id: 'l8-theory-verbs',
          type: 'theory',
          title: 'Звичні дії 🌞',
          body: 'Те, що ми робимо щодня — описуємо у Present Simple. З «I», «you», «we», «they» дієслово БЕЗ змін:\n\n• I get up at 7. — Я встаю о 7.\n• I eat breakfast. — Я снідаю.\n• I go to school. — Я йду до школи.\n• I play with friends. — Я граюся з друзями.\n• I sleep at night. — Я сплю вночі.\n\nПорядок зазвичай: ХТО + ЩО РОБИТЬ + ДЕТАЛІ.',
          examples: [
            { en: 'I get up.', ua: 'Я встаю.' },
            { en: 'I eat.', ua: 'Я їм.' },
            { en: 'I go.', ua: 'Я йду.' },
            { en: 'I play.', ua: 'Я граю.' },
            { en: 'I sleep.', ua: 'Я сплю.' },
            { en: 'I read.', ua: 'Я читаю.' },
          ],
          tip: '💡 У Present Simple з «I» НІЧОГО до дієслова не додаємо. «I go», не «I goes».',
        },
        {
          id: 'l8-theory-time',
          type: 'theory',
          title: 'Коли я це роблю ⏰',
          body: 'Щоб додати час — використовуємо «at» з годиною, «in» з частиною дня:\n\n• at 7 = о 7-й.\n• at 8 o\'clock = о 8 рівно.\n• in the morning = вранці.\n• in the afternoon = після обіду.\n• in the evening = увечері.\n• at night = вночі.\n\nЗверни увагу: «in the morning», але «at night» — традиція.',
          examples: [
            { en: 'I get up at 7.', ua: 'Я встаю о 7.' },
            { en: 'I have lunch at 1.', ua: 'Я обідаю о 1-й.' },
            { en: 'I read in the evening.', ua: 'Я читаю увечері.' },
            { en: 'I sleep at night.', ua: 'Я сплю вночі.' },
          ],
          tip: '💡 «O\'clock» — лише з рівними годинами: «6 o\'clock», ніколи «6:30 o\'clock».',
        },
        {
          id: 'l8-mc-1',
          type: 'multiple-choice',
          question: 'Що означає «I go to school»?',
          options: [
            'Я в школі',
            'Я йду до школи',
            'Я зайшов у школу',
            'Школа моя',
          ],
          correctIndex: 1,
        },
        {
          id: 'l8-mc-2',
          type: 'multiple-choice',
          question: 'Виправ: «I goes to school».',
          options: [
            "Має бути «I go» (без -s з I)",
            "Має бути «I going»",
            "Має бути «I am go»",
            'Все правильно',
          ],
          correctIndex: 0,
          explanation: '-s додаємо лише з «he / she / it», не з «I».',
        },
        {
          id: 'l8-mc-3',
          type: 'multiple-choice',
          question: 'Як сказати «о 8 ранку»?',
          options: [
            'in 8 morning',
            'at 8 o\'clock',
            'on 8 morning',
            'to 8',
          ],
          correctIndex: 1,
        },
        {
          id: 'l8-mc-4',
          type: 'multiple-choice',
          question: 'Який прийменник правильний? «___ the evening»',
          options: ['at', 'in', 'on', 'to'],
          correctIndex: 1,
          explanation: '«In the morning / afternoon / evening», але «at night».',
        },
        {
          id: 'l8-fill-1',
          type: 'fill-blank',
          before: 'I',
          after: ' breakfast at 8.',
          answer: 'have',
          hint: '«Have breakfast» — стандартна фраза «снідати».',
        },
        {
          id: 'l8-fill-2',
          type: 'fill-blank',
          before: 'I read books',
          after: ' the evening.',
          answer: 'in',
          hint: 'Прийменник для частини дня.',
        },
        {
          id: 'l8-match',
          type: 'match-pairs',
          prompt: 'Зʼєднай дію з перекладом:',
          pairs: [
            { left: 'get up', right: 'вставати' },
            { left: 'have breakfast', right: 'снідати' },
            { left: 'go to school', right: 'йти до школи' },
            { left: 'play', right: 'грати' },
            { left: 'sleep', right: 'спати' },
            { left: 'read', right: 'читати' },
          ],
        },
        {
          id: 'l8-order',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я снідаю о восьмій ранку.',
          words: ['breakfast', 'I', 'in', 'have', 'at', 'morning', '8', 'the'],
          answer: ['I', 'have', 'breakfast', 'at', '8', 'in', 'the', 'morning'],
        },
        {
          id: 'l8-reading',
          type: 'reading',
          title: "Roman's Day",
          text: "Hello! My name is Roman. I'm fourteen years old. I'm from Kyiv.\n\nI get up at 7 in the morning. I have breakfast at 7:30. I usually have eggs and tea.\n\nAt 8 o'clock I go to school. School is big and new. I have six lessons every day. My favourite subject is English. I love English very much!\n\nAfter school I play football with my friends. I love football! In the evening I read books or watch TV. I go to bed at 10.\n\nI like my day. It's busy but happy.",
          vocabulary: [
            { word: 'usually', translation: 'зазвичай' },
            { word: 'lesson', translation: 'урок' },
            { word: 'subject', translation: 'предмет (шкільний)' },
            { word: 'favourite', translation: 'улюблений' },
            { word: 'after school', translation: 'після школи' },
            { word: 'go to bed', translation: 'лягати спати' },
            { word: 'busy', translation: 'насичений' },
            { word: 'happy', translation: 'щасливий' },
          ],
          questions: [
            {
              id: 'l8-q1',
              question: 'Скільки років Роману?',
              options: ['10', '12', '14', '16'],
              correctIndex: 2,
              explanation: '"I\'m fourteen years old".',
            },
            {
              id: 'l8-q2',
              question: 'Який його улюблений шкільний предмет?',
              options: ['Математика', 'Англійська', 'Фізкультура', 'У тексті не сказано'],
              correctIndex: 1,
              explanation: '"My favourite subject is English. I love English very much!"',
            },
            {
              id: 'l8-q3',
              question: 'Що Роман робить після школи?',
              options: [
                'Робить домашку',
                'Дивиться телевізор',
                'Грає у футбол з друзями',
                'Йде спати',
              ],
              correctIndex: 2,
              explanation: '"After school I play football with my friends".',
            },
            {
              id: 'l8-q4',
              question: 'О котрій Роман лягає спати?',
              options: ['8', '9', '10', '11'],
              correctIndex: 2,
              explanation: '"I go to bed at 10".',
            },
          ],
        },
        {
          id: 'l8-translate',
          type: 'translate',
          prompt: 'Переклади:',
          sentence: 'Я граюся з друзями після школи.',
          answer: 'I play with friends after school.',
          acceptedAnswers: accepted('I play with friends after school.', [
            'i play with my friends after school',
          ]),
        },
      ],
    },
  ],
};
