import type { ProgramDetailData } from '@/components/molecules/ProgramDetail';

export const LIBRARY_PROGRAMS: ProgramDetailData[] = [
  { id: 'p1', slug: 'starter-kids',       title: 'Стартер для малюків',      description: 'Перші слова через ігри, пісні та малюнки. Ідеально для дітей 4–7 років.',           level: 'A0', levelColor: '', teacherName: 'Olga Kovalenko',  teacherPhoto: 'https://randomuser.me/api/portraits/women/44.jpg', tags: ['Діти 4–7','Ігри','Пісні'],          studentsCount: 18, lessonsCount: 24, rating: 4.9, reviews: 124, status: 'published', createdAt: 'Вер 2023' },
  { id: 'p2', slug: 'elementary-kids',    title: 'Базовий рівень',            description: 'Розмовна англійська, шкільна програма та улюблені теми дитини.',                     level: 'A1', levelColor: '', teacherName: 'Maria Sydorenko', teacherPhoto: 'https://randomuser.me/api/portraits/women/65.jpg', tags: ['Діти 7–11','Граматика','Розмова'],   studentsCount: 24, lessonsCount: 36, rating: 4.8, reviews: 89,  status: 'published', createdAt: 'Бер 2022' },
  { id: 'p3', slug: 'pre-intermediate',   title: 'Передсередній рівень',      description: 'Поглиблена граматика, читання та перші навички письма.',                             level: 'A2', levelColor: '', teacherName: 'Maria Sydorenko', teacherPhoto: 'https://randomuser.me/api/portraits/women/65.jpg', tags: ['Діти 9–12','Письмо','Читання'],      studentsCount: 15, lessonsCount: 40, rating: 4.7, reviews: 61,  status: 'published', createdAt: 'Лип 2022' },
  { id: 'p4', slug: 'intermediate-teens', title: 'Середній рівень',           description: 'Підготовка до шкільних тестів, складна граматика та вимова.',                       level: 'B1', levelColor: '', teacherName: 'Dmytro Petrenko', teacherPhoto: 'https://randomuser.me/api/portraits/men/32.jpg',   tags: ['Підлітки','Іспити','Вимова'],        studentsCount: 21, lessonsCount: 48, rating: 4.8, reviews: 203, status: 'published', createdAt: 'Лип 2021' },
  { id: 'p5', slug: 'upper-intermediate', title: 'Впевнений рівень',          description: 'Вільна розмова, бізнес-англійська та міжнародні сертифікати.',                      level: 'B2', levelColor: '', teacherName: 'Anna Vasylenko',  teacherPhoto: 'https://randomuser.me/api/portraits/women/23.jpg', tags: ['14+','Бізнес','Сертифікати'],        studentsCount: 15, lessonsCount: 52, rating: 4.9, reviews: 178, status: 'published', createdAt: 'Жов 2022' },
  { id: 'p6', slug: 'exam-prep',          title: 'Підготовка до ЗНО / NMT',  description: 'Цільова підготовка до державних іспитів з максимальним балом.',                     level: 'B2', levelColor: '', teacherName: 'Anna Vasylenko',  teacherPhoto: 'https://randomuser.me/api/portraits/women/23.jpg', tags: ['Старшокласники','ЗНО','Тести'],      studentsCount: 0,  lessonsCount: 30, rating: 5.0, reviews: 94,  status: 'draft',     createdAt: 'Бер 2026' },
  { id: 'p7', slug: 'toddlers',           title: 'Англійська для малят 2–4',  description: 'Ігрові заняття для найменших: кольори, тварини, перші фрази у форматі гри.',         level: 'A0', levelColor: '', teacherName: 'Iryna Moroz',     teacherPhoto: 'https://randomuser.me/api/portraits/women/37.jpg', tags: ['2–4 роки','Ігри','Пісні'],          studentsCount: 3,  lessonsCount: 16, rating: 4.6, reviews: 12,  status: 'draft',     createdAt: 'Лют 2026' },
  { id: 'p8', slug: 'legacy-basics',      title: 'Основи (старий формат)',    description: 'Застарілий курс. Учні переведені на новий формат.',                                 level: 'A1', levelColor: '', teacherName: 'Maria Sydorenko', teacherPhoto: 'https://randomuser.me/api/portraits/women/65.jpg', tags: ['Застарілий'],                       studentsCount: 0,  lessonsCount: 20, rating: 4.2, reviews: 30,  status: 'archived',  createdAt: 'Сер 2021' },
];
