import type { CourseSeed } from './types';

export const bluey: CourseSeed = {
  slug: 'bluey',
  lessons: [
    {
      slug: 'bluey-keepy-uppy',
      title: 'Episode: Keepy Uppy',
      orderIndex: 0,
      type: 'video',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'bluey-family-games',
      sectionTitle: 'Частина 1 · Ігри з родиною',
      sectionOrder: 0,
      isFree: true,
      topic: 'games',
      videoUrl: 'https://www.youtube.com/embed/GKJ2yWkr-xE',
      transcript:
        "It's a rainy day. Bluey and Bingo are bored. \"Dad, can we play a game?\" Bandit blows up a red balloon: \"Let's play Keepy Uppy — we can't let the balloon touch the floor!\" They jump, they hit, they dive. It's so much fun!",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Ігри та дії 🎈',
          body: "Bluey — мультфільм з австралійським акцентом. У цій серії родина грає у веселу гру з повітряною кулькою.",
          examples: [
            { en: 'balloon', ua: 'повітряна кулька' },
            { en: 'touch the floor', ua: 'торкатись підлоги' },
            { en: 'jump', ua: 'стрибати' },
            { en: 'hit', ua: 'вдаряти' },
            { en: 'bored', ua: 'нудно' },
            { en: 'fun', ua: 'весело' },
          ],
          tip: '💡 "Can we play?" — увічливе прохання ("Чи можемо ми пограти?").',
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Bluey: Keepy Uppy',
          url: 'https://www.youtube.com/embed/GKJ2yWkr-xE',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: "Яке правило у грі «Keepy Uppy»?",
          options: [
            'не можна розмовляти',
            'кулька не може впасти на підлогу',
            'треба стояти на одній нозі',
            'треба зловити кулю руками',
          ],
          correctIndex: 1,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: "We can't let the balloon touch the ",
          after: '.',
          answer: 'floor',
          hint: 'Підлога англійською…',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Тату, можна пограти в гру?',
          words: ['Dad', 'can', 'we', 'play', 'a', 'game'],
          answer: ['Dad', 'can', 'we', 'play', 'a', 'game'],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слова:",
          pairs: [
            { left: 'balloon', right: 'кулька' },
            { left: 'floor', right: 'підлога' },
            { left: 'jump', right: 'стрибати' },
            { left: 'fun', right: 'весело' },
          ],
        },
      ],
    },
    {
      slug: 'bluey-the-pool',
      title: 'Episode: The Pool',
      orderIndex: 1,
      type: 'video',
      durationMin: 9,
      xp: 15,
      sectionSlug: 'bluey-family-games',
      sectionTitle: 'Частина 1 · Ігри з родиною',
      sectionOrder: 0,
      topic: 'outdoor',
      videoUrl: 'https://www.youtube.com/embed/2EXBL6Z3Wpo',
      transcript:
        "The family is going to the pool. Mum packs the sunscreen. Dad packs towels. Bingo packs goggles. Bluey says: \"Dad, did you bring the floaties?\" — \"Oh no, I forgot the floaties!\" So Bingo learns how to swim without them.",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Басейн і речі 🏊',
          body: "Перед басейном треба зібрати багато речей. Ось слова до теми.",
          examples: [
            { en: 'pool', ua: 'басейн' },
            { en: 'swim', ua: 'плавати' },
            { en: 'towel', ua: 'рушник' },
            { en: 'sunscreen', ua: 'крем від сонця' },
            { en: 'goggles', ua: 'окуляри для плавання' },
            { en: 'floaties', ua: 'нарукавники (для плавання)' },
          ],
          tip: "💡 \"I forgot\" — \"Я забув/забула\". Часто чути у повсякденному житті.",
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Bluey: The Pool',
          url: 'https://www.youtube.com/embed/2EXBL6Z3Wpo',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: "Що забув тато вдома?",
          options: ['рушники', 'крем від сонця', 'нарукавники', 'окуляри'],
          correctIndex: 2,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: "Що вчиться робити Бінго у цій серії?",
          options: [
            'плавати без нарукавників',
            'стрибати з вишки',
            'пірнати глибоко',
            'кататись на велосипеді',
          ],
          correctIndex: 0,
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "Що береш у басейн?",
          pairs: [
            { left: 'towel', right: 'рушник' },
            { left: 'sunscreen', right: 'крем від сонця' },
            { left: 'goggles', right: 'окуляри' },
            { left: 'swimsuit', right: 'купальник' },
          ],
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Я забув рушник.',
          answer: 'I forgot the towel.',
          acceptedAnswers: [
            'I forgot the towel.',
            'I forgot the towel',
            'i forgot the towel',
          ],
        },
      ],
    },
    {
      slug: 'bluey-sleepytime',
      title: 'Episode: Sleepytime',
      orderIndex: 2,
      type: 'video',
      durationMin: 9,
      xp: 18,
      sectionSlug: 'bluey-emotions',
      sectionTitle: 'Частина 2 · Почуття',
      sectionOrder: 1,
      topic: 'emotions',
      videoUrl: 'https://www.youtube.com/embed/ZI5bSP7-zdM',
      transcript:
        "Bingo wants to sleep in her own bed tonight — like a 'big girl'. She has her favourite toy, Floppy, and dreams of travelling to the sun. But in the night, she feels lonely. Mum finds her in her own bed in the morning. \"You did it, Bingo!\"",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Сон і почуття 🌙',
          body: "Ця серія — про мужність малої Бінго, яка вперше спить сама. Повторимо слова про почуття.",
          examples: [
            { en: 'sleep', ua: 'спати' },
            { en: 'dream', ua: 'мріяти / сон' },
            { en: 'lonely', ua: 'самотньо' },
            { en: 'favourite toy', ua: 'улюблена іграшка' },
            { en: 'big girl', ua: 'доросла дівчинка' },
          ],
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Bluey: Sleepytime',
          url: 'https://www.youtube.com/embed/ZI5bSP7-zdM',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як звати улюблену іграшку Бінго?',
          options: ['Bluey', 'Floppy', 'Bandit', 'Snickers'],
          correctIndex: 1,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'Bingo has her favourite ',
          after: ', Floppy.',
          answer: 'toy',
          hint: 'Річ, якою грається дитина…',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай:",
          pairs: [
            { left: 'sleep', right: 'спати' },
            { left: 'dream', right: 'мріяти' },
            { left: 'lonely', right: 'самотньо' },
            { left: 'morning', right: 'ранок' },
          ],
        },
      ],
    },
  ],
};
