import type { CourseSeed } from './types';

/**
 * Flagship A1 kids course — "English for Kids — Starter".
 *
 * Three units (Knowing Me, Daily Life, First Grammar) with a mix of
 * theory + exercises, reading comprehension, and a listening video.
 * First two lessons are free so new learners can sample it.
 */
export const englishKidsStarter: CourseSeed = {
  slug: 'english-kids-starter',
  createIfMissing: {
    title: 'English for Kids — Starter',
    titleUa: 'Англійська для дітей — Старт',
    subtitle: 'A1 · 18 уроків · 3 юніти',
    description:
      'Дружній старт у вивченні англійської для дітей 7–11 років. Вчимось вітатись, розповідати про себе, говорити про день і розпорядок, описувати своє оточення.',
    descriptionShort:
      'Дружній старт в англійську для молодших школярів: вітання, родина, розпорядок дня, перша граматика.',
    level: 'A1',
    audience: 'kids',
    kind: 'course',
    iconEmoji: '🎒',
    tags: ['kids', 'speaking', 'grammar', 'vocabulary'],
  },
  lessons: [
    {
      slug: 'hello-goodbye',
      title: 'Hello & Goodbye',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'knowing-me',
      sectionTitle: 'Юніт 1 · Я і моє оточення',
      sectionOrder: 0,
      isFree: true,
      topic: 'greetings',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Вітання та прощання 👋',
          body: 'Перший крок у вивченні англійської — навчитись вітатись! Ці слова ти будеш використовувати щодня.',
          examples: [
            { en: 'Hello', ua: 'Привіт' },
            { en: 'Hi', ua: 'Привіт (неформально)' },
            { en: 'Goodbye', ua: 'До побачення' },
            { en: 'Bye', ua: 'Бувай' },
            { en: 'Good morning', ua: 'Доброго ранку' },
            { en: 'Good night', ua: 'На добраніч' },
          ],
          tip: '💡 "Hi" — коротше та більш неформальне, ніж "Hello"',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як сказати "Привіт" по-англійськи?',
          options: ['Goodbye', 'Hello', 'Good night', 'Please'],
          correctIndex: 1,
          explanation: '"Hello" або "Hi" — це вітання. "Goodbye" — до побачення.',
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Що означає "Good morning"?',
          options: ['На добраніч', 'До побачення', 'Доброго ранку', 'Дякую'],
          correctIndex: 2,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'A: Hello! B:',
          after: '! Nice to meet you.',
          answer: 'Hi',
          hint: 'Коротке вітання у відповідь…',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слово з перекладом:",
          pairs: [
            { left: 'Hello', right: 'Привіт' },
            { left: 'Goodbye', right: 'До побачення' },
            { left: 'Good morning', right: 'Доброго ранку' },
            { left: 'Good night', right: 'На добраніч' },
          ],
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Доброго ранку! Як справи?',
          answer: 'Good morning! How are you?',
          acceptedAnswers: [
            'Good morning! How are you?',
            'Good morning! How are you',
            'good morning! how are you?',
            'good morning how are you',
          ],
        },
      ],
    },
    {
      slug: 'my-name-is',
      title: 'My name is…',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'knowing-me',
      sectionTitle: 'Юніт 1 · Я і моє оточення',
      sectionOrder: 0,
      isFree: true,
      topic: 'introductions',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Як розповісти про себе 🙋',
          body: 'Коли знайомимось з кимось, треба сказати як нас звати і скільки нам років. Ось кілька корисних фраз.',
          examples: [
            { en: 'My name is Anna.', ua: 'Мене звати Анна.' },
            { en: "I'm Max.", ua: 'Я Макс.' },
            { en: 'I am eight years old.', ua: 'Мені вісім років.' },
            { en: 'Nice to meet you.', ua: 'Приємно познайомитись.' },
            { en: 'What is your name?', ua: 'Як тебе звати?' },
          ],
          tip: "💡 I'm = I am — просто коротша форма",
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як сказати "Мене звати Марія"?',
          options: ['I am Maria', 'My name is Maria', 'You name Maria', 'Name Maria me'],
          correctIndex: 1,
          explanation: '"My name is…" — найпоширеніша формула для знайомства.',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Мені десять років.',
          words: ['I', 'am', 'ten', 'years', 'old'],
          answer: ['I', 'am', 'ten', 'years', 'old'],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'Hi! My',
          after: ' is Tom.',
          answer: 'name',
          hint: 'Мене звати Том — моє… Том.',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай фрази:",
          pairs: [
            { left: 'What is your name?', right: 'Як тебе звати?' },
            { left: 'How old are you?', right: 'Скільки тобі років?' },
            { left: 'Nice to meet you.', right: 'Приємно познайомитись.' },
            { left: "I'm fine, thanks.", right: 'У мене все добре, дякую.' },
          ],
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Привіт! Мене звати Софія. Мені девʼять років.',
          answer: 'Hi! My name is Sofia. I am nine years old.',
          acceptedAnswers: [
            'Hi! My name is Sofia. I am nine years old.',
            "Hi! My name is Sofia. I'm nine years old.",
            'Hi, my name is Sofia. I am nine years old.',
            'hi my name is sofia i am nine years old',
          ],
        },
      ],
    },
    {
      slug: 'numbers-colors',
      title: 'Numbers & Colors',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 12,
      xp: 15,
      sectionSlug: 'knowing-me',
      sectionTitle: 'Юніт 1 · Я і моє оточення',
      sectionOrder: 0,
      topic: 'numbers-colors',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Числа та кольори 🎨',
          body: 'Вчимо перші 10 чисел та основні кольори. Ці слова знадобляться скрізь — від магазину до шкільних завдань.',
          examples: [
            { en: 'one, two, three', ua: 'один, два, три' },
            { en: 'four, five, six', ua: 'чотири, пʼять, шість' },
            { en: 'red, blue, green', ua: 'червоний, синій, зелений' },
            { en: 'yellow, orange, pink', ua: 'жовтий, оранжевий, рожевий' },
            { en: 'black, white', ua: 'чорний, білий' },
          ],
          tip: '💡 "Color" (AmE) та "colour" (BrE) — просто різне написання одного слова.',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Яке число йде після "seven"?',
          options: ['six', 'eight', 'nine', 'ten'],
          correctIndex: 1,
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай кольори:",
          pairs: [
            { left: 'red', right: 'червоний' },
            { left: 'blue', right: 'синій' },
            { left: 'green', right: 'зелений' },
            { left: 'yellow', right: 'жовтий' },
          ],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'The sky is ',
          after: '.',
          answer: 'blue',
          hint: 'Колір неба…',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'У мене три червоні яблука.',
          words: ['I', 'have', 'three', 'red', 'apples'],
          answer: ['I', 'have', 'three', 'red', 'apples'],
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Яким кольором зазвичай малюють сонце?',
          options: ['green', 'yellow', 'black', 'white'],
          correctIndex: 1,
        },
      ],
    },
    {
      slug: 'my-family',
      title: 'My Family',
      orderIndex: 3,
      type: 'reading',
      durationMin: 12,
      xp: 20,
      sectionSlug: 'knowing-me',
      sectionTitle: 'Юніт 1 · Я і моє оточення',
      sectionOrder: 0,
      topic: 'family',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Члени сімʼї 👨‍👩‍👧',
          body: 'Сімʼя — одна з перших тем у вивченні будь-якої мови. Запам\'ятай ці слова — вони допоможуть розповісти про найдорожчих.',
          examples: [
            { en: 'mother / mum', ua: 'мама' },
            { en: 'father / dad', ua: 'тато' },
            { en: 'brother', ua: 'брат' },
            { en: 'sister', ua: 'сестра' },
            { en: 'grandmother / grandma', ua: 'бабуся' },
            { en: 'grandfather / grandpa', ua: 'дідусь' },
          ],
          tip: '💡 Mum/Dad — коротка, ласкава форма. Mother/Father — формальна.',
        },
        {
          id: 'reading-1',
          type: 'reading',
          title: 'My family',
          text:
            "Hello! My name is Lena and I am ten years old. I have a big family. My mum is a teacher and my dad is a doctor. I have one brother. His name is Oleh and he is six. We have a small dog. Her name is Lucy. My grandma lives near us. She makes the best pancakes!",
          vocabulary: [
            { word: 'big family', translation: 'велика сімʼя' },
            { word: 'teacher', translation: 'вчителька' },
            { word: 'doctor', translation: 'лікар' },
            { word: 'brother', translation: 'брат' },
            { word: 'near us', translation: 'біля нас' },
            { word: 'pancakes', translation: 'млинці' },
          ],
          questions: [
            {
              id: 'q1',
              question: 'Скільки років Лені?',
              options: ['шість', 'вісім', 'десять', 'дванадцять'],
              correctIndex: 2,
            },
            {
              id: 'q2',
              question: 'Ким працює тато Лени?',
              options: ['вчителем', 'лікарем', 'водієм', 'інженером'],
              correctIndex: 1,
            },
            {
              id: 'q3',
              question: 'Як звати собаку?',
              options: ['Oleh', 'Lena', 'Lucy', 'Nana'],
              correctIndex: 2,
              explanation: 'У тексті: "Her name is Lucy".',
            },
            {
              id: 'q4',
              question: 'Що смачно готує бабуся?',
              options: ['піцу', 'млинці (pancakes)', 'торт', 'суп'],
              correctIndex: 1,
            },
          ],
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як англійською "дідусь"?',
          options: ['grandmother', 'grandfather', 'brother', 'father'],
          correctIndex: 1,
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'У мене є брат і сестра.',
          answer: 'I have a brother and a sister.',
          acceptedAnswers: [
            'I have a brother and a sister.',
            'I have a brother and a sister',
            'i have a brother and a sister',
            'I have brother and sister.',
          ],
        },
      ],
    },
    {
      slug: 'daily-routines',
      title: 'Daily Routines',
      orderIndex: 4,
      type: 'interactive',
      durationMin: 12,
      xp: 20,
      sectionSlug: 'daily-life',
      sectionTitle: 'Юніт 2 · Мій день',
      sectionOrder: 1,
      topic: 'daily-routines',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Мій день по-англійськи ⏰',
          body: "Навчимось розповідати про свій розпорядок дня. Ці фрази допоможуть описати що ти робиш щодня.",
          examples: [
            { en: 'wake up', ua: 'прокидатись' },
            { en: 'have breakfast', ua: 'снідати' },
            { en: 'go to school', ua: 'іти до школи' },
            { en: 'do homework', ua: 'робити домашнє завдання' },
            { en: 'go to bed', ua: 'лягати спати' },
            { en: 'watch TV', ua: 'дивитись телевізор' },
          ],
          tip: '💡 "I wake up at 7" = "Я прокидаюсь о 7-й". "At" використовуємо з часом!',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Що означає "wake up"?',
          options: ['лягати спати', 'снідати', 'прокидатись', 'іти до школи'],
          correctIndex: 2,
          explanation: '"Wake up" — прокидатись. "Go to bed" — лягати спати.',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я снідаю о восьмій годині.',
          words: ['I', 'have', 'breakfast', 'at', 'eight'],
          answer: ['I', 'have', 'breakfast', 'at', 'eight'],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'After school I',
          after: ' my homework.',
          answer: 'do',
          hint: '"Робити" домашнє завдання…',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай дію з перекладом:",
          pairs: [
            { left: 'wake up', right: 'прокидатись' },
            { left: 'go to school', right: 'іти до школи' },
            { left: 'watch TV', right: 'дивитись ТВ' },
            { left: 'go to bed', right: 'лягати спати' },
          ],
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Я прокидаюсь о сьомій і іду до школи.',
          answer: 'I wake up at seven and go to school.',
          acceptedAnswers: [
            'I wake up at seven and go to school.',
            'I wake up at seven and go to school',
            'i wake up at seven and go to school.',
            'I wake up at 7 and go to school.',
          ],
        },
      ],
    },
    {
      slug: 'food-drinks',
      title: 'Food & Drinks',
      orderIndex: 5,
      type: 'interactive',
      durationMin: 12,
      xp: 20,
      sectionSlug: 'daily-life',
      sectionTitle: 'Юніт 2 · Мій день',
      sectionOrder: 1,
      topic: 'food',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Їжа та напої 🍎',
          body: "Сьогодні вивчаємо слова про їжу та напої. Запам'ятай ці слова — вони потрібні щодня!",
          examples: [
            { en: 'apple', ua: 'яблуко' },
            { en: 'bread', ua: 'хліб' },
            { en: 'milk', ua: 'молоко' },
            { en: 'water', ua: 'вода' },
            { en: 'juice', ua: 'сік' },
            { en: 'cheese', ua: 'сир' },
          ],
          tip: '💡 "I like" + їжа = "Я люблю [їжу]". Наприклад: "I like apples".',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Що означає "milk"?',
          options: ['хліб', 'молоко', 'вода', 'сік'],
          correctIndex: 1,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Який напій НЕ вказано у теорії?',
          options: ['milk', 'water', 'juice', 'tea'],
          correctIndex: 3,
          explanation: 'У теорії були milk, water, juice. "Tea" (чай) — не було.',
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'I eat an ',
          after: ' every day.',
          answer: 'apple',
          hint: "Червоний фрукт, який дає лікар замість ліків 😉",
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слово з перекладом:",
          pairs: [
            { left: 'bread', right: 'хліб' },
            { left: 'water', right: 'вода' },
            { left: 'cheese', right: 'сир' },
            { left: 'juice', right: 'сік' },
          ],
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Я пʼю молоко на сніданок.',
          words: ['I', 'drink', 'milk', 'for', 'breakfast'],
          answer: ['I', 'drink', 'milk', 'for', 'breakfast'],
        },
      ],
    },
    {
      slug: 'my-house',
      title: 'My House',
      orderIndex: 6,
      type: 'reading',
      durationMin: 12,
      xp: 20,
      sectionSlug: 'daily-life',
      sectionTitle: 'Юніт 2 · Мій день',
      sectionOrder: 1,
      topic: 'home',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Мій дім 🏡',
          body: 'Опишемо свій дім по-англійськи. Запамʼятай основні кімнати — цими словами користуються щодня.',
          examples: [
            { en: 'kitchen', ua: 'кухня' },
            { en: 'bedroom', ua: 'спальня' },
            { en: 'bathroom', ua: 'ванна' },
            { en: 'living room', ua: 'вітальня' },
            { en: 'garden', ua: 'садок' },
          ],
          tip: '💡 "In the kitchen" = "На кухні". З кімнатами використовуємо "in + the".',
        },
        {
          id: 'reading-1',
          type: 'reading',
          title: 'My house',
          text:
            "My name is Max. I live in a small house with a big garden. The house has four rooms: a kitchen, a living room, and two bedrooms. I share my bedroom with my brother Taras. We have a cat called Nina. She likes to sleep on the sofa in the living room. In the garden, there is an old apple tree. I love my house!",
          vocabulary: [
            { word: 'small house', translation: 'маленький будинок' },
            { word: 'share', translation: 'ділити з кимось' },
            { word: 'sofa', translation: 'диван' },
            { word: 'apple tree', translation: 'яблуня' },
          ],
          questions: [
            {
              id: 'q1',
              question: 'Скільки кімнат в будинку Макса?',
              options: ['дві', 'три', 'чотири', 'пʼять'],
              correctIndex: 2,
            },
            {
              id: 'q2',
              question: 'З ким Макс ділить спальню?',
              options: ['з братом Тарасом', 'з сестрою', 'з котом', 'сам'],
              correctIndex: 0,
            },
            {
              id: 'q3',
              question: 'Де любить спати кішка Ніна?',
              options: ['на кухні', 'в ліжку', 'на дивані у вітальні', 'в саду'],
              correctIndex: 2,
            },
          ],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'We cook in the ',
          after: '.',
          answer: 'kitchen',
          hint: 'Де готують їжу?',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай кімнати:",
          pairs: [
            { left: 'kitchen', right: 'кухня' },
            { left: 'bedroom', right: 'спальня' },
            { left: 'bathroom', right: 'ванна' },
            { left: 'living room', right: 'вітальня' },
          ],
        },
      ],
    },
    {
      slug: 'present-simple-intro',
      title: 'Present Simple: I / You / We',
      orderIndex: 7,
      type: 'interactive',
      durationMin: 15,
      xp: 25,
      sectionSlug: 'first-grammar',
      sectionTitle: 'Юніт 3 · Перша граматика',
      sectionOrder: 2,
      topic: 'present-simple',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Теперішній простий час ✏️',
          body: 'Present Simple — це час який описує те, що відбувається завжди, щодня або зазвичай. З "I", "you", "we", "they" дієслово НЕ змінюється.',
          examples: [
            { en: 'I play football.', ua: 'Я граю у футбол.' },
            { en: 'You like apples.', ua: 'Ти любиш яблука.' },
            { en: 'We study English.', ua: 'Ми вчимо англійську.' },
            { en: 'They live in Kyiv.', ua: 'Вони живуть у Києві.' },
          ],
          tip: "💡 Без -s в кінці дієслова! Ці форми додаємо тільки з he/she/it (наступний урок).",
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Яке речення правильне?',
          options: ['I plays football', 'I play football', 'I playing football', 'I to play football'],
          correctIndex: 1,
          explanation: 'З "I" дієслово — без "-s" і без "-ing".',
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'I ',
          after: ' in a small house.',
          answer: 'live',
          hint: 'Жити = live',
        },
        {
          id: 'fill-2',
          type: 'fill-blank',
          before: 'We ',
          after: ' English on Mondays.',
          answer: 'study',
          hint: 'Вивчати = study',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Ти любиш морозиво.',
          words: ['You', 'like', 'ice', 'cream'],
          answer: ['You', 'like', 'ice', 'cream'],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай:",
          pairs: [
            { left: 'I play', right: 'Я граю' },
            { left: 'You like', right: 'Ти любиш' },
            { left: 'We study', right: 'Ми вчимось' },
            { left: 'They live', right: 'Вони живуть' },
          ],
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Ми живемо в Україні.',
          answer: 'We live in Ukraine.',
          acceptedAnswers: ['We live in Ukraine.', 'We live in Ukraine', 'we live in ukraine.'],
        },
      ],
    },
  ],
};
