import type { CourseSeed } from './types';

export const natgeo: CourseSeed = {
  slug: 'natgeo',
  lessons: [
    {
      slug: 'natgeo-cheetah',
      title: 'The fastest cat: Cheetah',
      orderIndex: 0,
      type: 'reading',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'natgeo-animals',
      sectionTitle: 'Частина 1 · Дикі тварини',
      sectionOrder: 0,
      isFree: true,
      topic: 'animals',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Швидкість і рухи 🐆',
          body: 'Ця стаття розповість про гепарда — найшвидшу кішку у світі. Ось корисні слова до теми.',
          examples: [
            { en: 'fast', ua: 'швидкий' },
            { en: 'run', ua: 'бігти' },
            { en: 'stop', ua: 'зупинятись' },
            { en: 'rest', ua: 'відпочивати' },
            { en: 'kilometre', ua: 'кілометр' },
            { en: 'short distance', ua: 'коротка дистанція' },
          ],
        },
        {
          id: 'reading-1',
          type: 'reading',
          title: 'Did you know?',
          text:
            'A cheetah can run as fast as a car on the highway — up to 120 kilometres per hour. But it can only run this fast for short distances. After 30 seconds, it must stop and rest. Cheetahs live in the grasslands of Africa. They eat small animals like gazelles.',
          vocabulary: [
            { word: 'highway', translation: 'автомагістраль' },
            { word: 'up to', translation: 'до' },
            { word: 'grasslands', translation: 'степи' },
            { word: 'gazelle', translation: 'газель' },
          ],
          questions: [
            {
              id: 'q1',
              question: 'Яка максимальна швидкість гепарда?',
              options: ['60 км/год', '100 км/год', '120 км/год', '200 км/год'],
              correctIndex: 2,
            },
            {
              id: 'q2',
              question: 'Як довго гепард може бігти з максимальною швидкістю?',
              options: ['5 хвилин', '30 секунд', '1 годину', 'цілий день'],
              correctIndex: 1,
            },
            {
              id: 'q3',
              question: 'Де живуть гепарди?',
              options: [
                'у лісах Європи',
                'у снігах Арктики',
                'у степах Африки',
                'у джунглях Амазонії',
              ],
              correctIndex: 2,
            },
          ],
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Що означає "fast"?',
          options: ['повільний', 'голодний', 'швидкий', 'зелений'],
          correctIndex: 2,
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слова:",
          pairs: [
            { left: 'run', right: 'бігти' },
            { left: 'stop', right: 'зупинятись' },
            { left: 'rest', right: 'відпочивати' },
            { left: 'fast', right: 'швидкий' },
          ],
        },
      ],
    },
    {
      slug: 'natgeo-ocean',
      title: 'Ocean giants',
      orderIndex: 1,
      type: 'reading',
      durationMin: 9,
      xp: 18,
      sectionSlug: 'natgeo-animals',
      sectionTitle: 'Частина 1 · Дикі тварини',
      sectionOrder: 0,
      topic: 'ocean',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Океан та його жителі 🐋',
          body: 'У статті про океан ти зустрінеш ці слова. Вони допоможуть уявити масштаб.',
          examples: [
            { en: 'ocean', ua: 'океан' },
            { en: 'whale', ua: 'кит' },
            { en: 'huge', ua: 'величезний' },
            { en: 'breathe', ua: 'дихати' },
            { en: 'sing', ua: 'співати' },
          ],
        },
        {
          id: 'reading-1',
          type: 'reading',
          title: 'The blue whale',
          text:
            "The blue whale is the biggest animal on Earth. It can be 30 metres long — longer than three buses! Its heart is as big as a small car. Blue whales live in cold oceans and eat tiny animals called krill. They can sing songs that travel for thousands of kilometres under the water.",
          vocabulary: [
            { word: 'the biggest', translation: 'найбільший' },
            { word: 'on Earth', translation: 'на Землі' },
            { word: 'metre', translation: 'метр' },
            { word: 'heart', translation: 'серце' },
            { word: 'krill', translation: 'криль (маленькі рачки)' },
            { word: 'under the water', translation: 'під водою' },
          ],
          questions: [
            {
              id: 'q1',
              question: 'Яка довжина синього кита?',
              options: ['3 метри', '15 метрів', '30 метрів', '100 метрів'],
              correctIndex: 2,
            },
            {
              id: 'q2',
              question: 'Що їдять сині кити?',
              options: ['рибу', 'акул', 'криль — маленьких рачків', 'морські водорості'],
              correctIndex: 2,
            },
            {
              id: 'q3',
              question: "Наскільки далеко лунають пісні кита під водою?",
              options: [
                '100 метрів',
                '1 кілометр',
                'декілька метрів',
                'тисячі кілометрів',
              ],
              correctIndex: 3,
            },
          ],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'The blue whale is the ',
          after: ' animal on Earth.',
          answer: 'biggest',
          hint: 'big → bigger → ?',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як англійською "океан"?',
          options: ['river', 'lake', 'ocean', 'sea'],
          correctIndex: 2,
        },
      ],
    },
    {
      slug: 'natgeo-volcano',
      title: 'How does a volcano work?',
      orderIndex: 2,
      type: 'reading',
      durationMin: 10,
      xp: 20,
      sectionSlug: 'natgeo-planet',
      sectionTitle: 'Частина 2 · Планета Земля',
      sectionOrder: 1,
      topic: 'geography',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Геологія простими словами 🌋',
          body: 'Кілька наукових слів, які зустрінуться в статті про вулкани.',
          examples: [
            { en: 'volcano', ua: 'вулкан' },
            { en: 'rock', ua: 'камінь' },
            { en: 'melt', ua: 'плавитись' },
            { en: 'lava', ua: 'лава' },
            { en: 'erupt', ua: 'вивергатись' },
          ],
        },
        {
          id: 'reading-1',
          type: 'reading',
          title: 'Rock that melts',
          text:
            'Deep inside the Earth, it is very hot. So hot that rocks melt and become a liquid. This liquid is called magma. Sometimes magma goes up through a mountain and comes out. We say the volcano "erupts". Outside the volcano, magma is called lava. When lava cools down, it becomes rock again.',
          vocabulary: [
            { word: 'deep inside', translation: 'глибоко всередині' },
            { word: 'liquid', translation: 'рідина' },
            { word: 'magma', translation: 'магма' },
            { word: 'cools down', translation: 'охолоджується' },
            { word: 'erupts', translation: 'вивергається' },
          ],
          questions: [
            {
              id: 'q1',
              question: 'Як називається рідкий камінь всередині Землі?',
              options: ['lava', 'magma', 'water', 'oil'],
              correctIndex: 1,
            },
            {
              id: 'q2',
              question: "Що відбувається з лавою, коли вона охолоджується?",
              options: [
                'вона випаровується',
                'вона стає водою',
                'вона стає каменем знову',
                'вона зникає',
              ],
              correctIndex: 2,
            },
          ],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай:",
          pairs: [
            { left: 'rock', right: 'камінь' },
            { left: 'melt', right: 'плавитись' },
            { left: 'lava', right: 'лава' },
            { left: 'erupt', right: 'вивергатись' },
          ],
        },
      ],
    },
  ],
};
