import type { CourseSeed } from './types';

export const peppa: CourseSeed = {
  slug: 'peppa',
  lessons: [
    {
      slug: 'peppa-muddy-puddles',
      title: 'Episode: Muddy Puddles',
      orderIndex: 0,
      type: 'video',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'peppa-season-1',
      sectionTitle: 'Сезон 1 · Улюблені серії',
      sectionOrder: 0,
      isFree: true,
      topic: 'cartoon',
      videoUrl: 'https://www.youtube.com/embed/X-qfi1tafds',
      transcript:
        "It's a rainy day. Peppa loves jumping up and down in muddy puddles! \"Mummy, can I go outside?\" — \"Yes, but put on your boots.\" Peppa jumps: splash, splash, splash! George wants to jump too, but first he falls in the mud. Oh dear!",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Дощ і калюжі ☔',
          body: 'У цій серії Пеппа стрибає по калюжах. Ось слова, які ти почуєш у відео.',
          examples: [
            { en: 'rainy day', ua: 'дощовий день' },
            { en: 'muddy puddle', ua: 'брудна калюжа' },
            { en: 'boots', ua: 'чоботи' },
            { en: 'jump', ua: 'стрибати' },
            { en: 'splash', ua: 'плюх' },
            { en: 'outside', ua: 'надворі' },
          ],
          tip: '💡 "Mummy" — британська форма слова "мама" (у США — "Mommy").',
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Peppa Pig: Muddy Puddles',
          url: 'https://www.youtube.com/embed/X-qfi1tafds',
          caption: 'Подивись серію повністю, потім виконай завдання нижче.',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Що Пеппа любить робити у дощ?',
          options: [
            'спати',
            'дивитись телевізор',
            'стрибати у калюжах',
            'малювати',
          ],
          correctIndex: 2,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'Mummy says: "Put on your ',
          after: '."',
          answer: 'boots',
          hint: 'Взуття для дощу…',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слова:",
          pairs: [
            { left: 'rain', right: 'дощ' },
            { left: 'puddle', right: 'калюжа' },
            { left: 'boots', right: 'чоботи' },
            { left: 'jump', right: 'стрибати' },
          ],
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади речення:',
          translation: 'Пеппа любить стрибати у калюжах.',
          words: ['Peppa', 'loves', 'jumping', 'in', 'puddles'],
          answer: ['Peppa', 'loves', 'jumping', 'in', 'puddles'],
        },
      ],
    },
    {
      slug: 'peppa-mr-dinosaur',
      title: "Episode: Mr. Dinosaur is Lost",
      orderIndex: 1,
      type: 'video',
      durationMin: 10,
      xp: 15,
      sectionSlug: 'peppa-season-1',
      sectionTitle: 'Сезон 1 · Улюблені серії',
      sectionOrder: 0,
      topic: 'cartoon',
      videoUrl: 'https://www.youtube.com/embed/WpGJdyy6zkc',
      transcript:
        "George loves his dinosaur. \"Dine-saw!\" he shouts. But one day, Mr. Dinosaur is lost. The family looks everywhere: in the kitchen, in the bedroom, in the garden. Finally, Daddy Pig finds him — on the roof! George is so happy.",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Кімнати та прийменники місця 🏠',
          body: 'Щоб знайти динозавра, сімʼя шукає його у різних місцях. Повторимо прийменники місця.',
          examples: [
            { en: 'in the kitchen', ua: 'на кухні' },
            { en: 'in the bedroom', ua: 'у спальні' },
            { en: 'in the garden', ua: 'у саду' },
            { en: 'on the roof', ua: 'на даху' },
            { en: 'under the bed', ua: 'під ліжком' },
          ],
          tip: '💡 "In" — всередині (in the box). "On" — зверху (on the table). "Under" — знизу (under the chair).',
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Peppa Pig: Mr. Dinosaur is Lost',
          url: 'https://www.youtube.com/embed/WpGJdyy6zkc',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Кого загубив Джордж?',
          options: ['кота', 'улюбленого динозавра', 'машинку', 'брата'],
          correctIndex: 1,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Де знайшовся містер Динозавр?',
          options: ['у ліжку', 'у ванній', 'на даху', 'у машині'],
          correctIndex: 2,
          explanation: 'У серії: "Finally, Daddy Pig finds him — on the roof!"',
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'Daddy Pig finds the dinosaur ',
          after: ' the roof.',
          answer: 'on',
          hint: 'Прийменник "на" (поверхні)',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай:",
          pairs: [
            { left: 'in', right: 'всередині' },
            { left: 'on', right: 'на' },
            { left: 'under', right: 'під' },
            { left: 'roof', right: 'дах' },
          ],
        },
      ],
    },
    {
      slug: 'peppa-best-friend',
      title: 'Episode: Peppa’s best friend Suzy',
      orderIndex: 2,
      type: 'video',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'peppa-season-2',
      sectionTitle: 'Сезон 2 · Друзі',
      sectionOrder: 1,
      topic: 'friendship',
      videoUrl: 'https://www.youtube.com/embed/nlaAG3fNHCg',
      transcript:
        "Peppa's best friend is Suzy Sheep. They do everything together. They play at school, they have picnics, and they share secrets. \"You're my best friend, Suzy!\" — \"And you're my best friend, Peppa!\"",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Про друзів 👯',
          body: 'Поговорімо про дружбу англійською.',
          examples: [
            { en: 'best friend', ua: 'найкращий друг' },
            { en: 'play together', ua: 'гратись разом' },
            { en: 'share', ua: 'ділитись' },
            { en: 'secret', ua: 'секрет' },
            { en: 'picnic', ua: 'пікнік' },
          ],
        },
        {
          id: 'video-1',
          type: 'video',
          title: "Peppa's best friend",
          url: 'https://www.youtube.com/embed/nlaAG3fNHCg',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: "Хто найкраща подруга Пеппи?",
          options: ['Rebecca Rabbit', 'Suzy Sheep', 'Emily Elephant', 'Candy Cat'],
          correctIndex: 1,
        },
        {
          id: 'tr-1',
          type: 'translate',
          prompt: 'Перекладіть англійською:',
          sentence: 'Ти мій найкращий друг.',
          answer: "You're my best friend.",
          acceptedAnswers: [
            "You're my best friend.",
            'You are my best friend.',
            "you're my best friend.",
            'you are my best friend',
          ],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай слова:",
          pairs: [
            { left: 'friend', right: 'друг' },
            { left: 'play', right: 'гратись' },
            { left: 'share', right: 'ділитись' },
            { left: 'secret', right: 'секрет' },
          ],
        },
      ],
    },
  ],
};
