import type { CourseSeed } from './types';

export const simpleSongs: CourseSeed = {
  slug: 'simple-songs',
  lessons: [
    {
      slug: 'songs-if-youre-happy',
      title: "If You're Happy and You Know It",
      orderIndex: 0,
      type: 'video',
      durationMin: 6,
      xp: 12,
      sectionSlug: 'songs-feelings',
      sectionTitle: 'Частина 1 · Почуття та дії',
      sectionOrder: 0,
      isFree: true,
      topic: 'song',
      videoUrl: 'https://www.youtube.com/embed/l4WNrvVjiTw',
      transcript:
        "If you're happy and you know it, clap your hands! (clap clap) If you're happy and you know it, clap your hands! (clap clap) If you're happy and you know it, and you really want to show it, if you're happy and you know it, clap your hands!",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Почуття та дії 😀',
          body: 'Пісня вчить нас казати, як ми почуваємось, та називати прості дії.',
          examples: [
            { en: 'happy', ua: 'щасливий' },
            { en: 'clap your hands', ua: 'плескати в долоні' },
            { en: 'stomp your feet', ua: 'тупотіти ногами' },
            { en: 'shout "Hooray!"', ua: 'кричати «Ура!»' },
            { en: 'know', ua: 'знати' },
            { en: 'show', ua: 'показувати' },
          ],
        },
        {
          id: 'video-1',
          type: 'video',
          title: "If You're Happy and You Know It",
          url: 'https://www.youtube.com/embed/l4WNrvVjiTw',
          caption: 'Послухай пісню декілька разів, підспівуй — потім виконай завдання.',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: "Що робити, якщо ти щасливий?",
          options: [
            'поплакати',
            'плескати в долоні',
            'лягти спати',
            'мовчати',
          ],
          correctIndex: 1,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'If you are happy, clap your ',
          after: '!',
          answer: 'hands',
          hint: 'Частина тіла, якою плескаєш…',
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай дії:",
          pairs: [
            { left: 'clap', right: 'плескати' },
            { left: 'stomp', right: 'тупотіти' },
            { left: 'shout', right: 'кричати' },
            { left: 'show', right: 'показувати' },
          ],
        },
      ],
    },
    {
      slug: 'songs-head-shoulders',
      title: 'Head, Shoulders, Knees and Toes',
      orderIndex: 1,
      type: 'video',
      durationMin: 5,
      xp: 12,
      sectionSlug: 'songs-body',
      sectionTitle: 'Частина 2 · Моє тіло',
      sectionOrder: 1,
      topic: 'body',
      videoUrl: 'https://www.youtube.com/embed/ZanHgPprl-0',
      transcript:
        "Head, shoulders, knees and toes, knees and toes! Head, shoulders, knees and toes, knees and toes! And eyes, and ears, and mouth, and nose! Head, shoulders, knees and toes, knees and toes!",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Частини тіла 👀',
          body: 'Ця класична пісня — ідеальний спосіб вивчити частини тіла. Показуй кожну частину під час співу!',
          examples: [
            { en: 'head', ua: 'голова' },
            { en: 'shoulders', ua: 'плечі' },
            { en: 'knees', ua: 'коліна' },
            { en: 'toes', ua: 'пальці ніг' },
            { en: 'eyes', ua: 'очі' },
            { en: 'ears', ua: 'вуха' },
            { en: 'mouth', ua: 'рот' },
            { en: 'nose', ua: 'ніс' },
          ],
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Head Shoulders Knees & Toes',
          url: 'https://www.youtube.com/embed/ZanHgPprl-0',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як англійською "коліна"?',
          options: ['toes', 'knees', 'ears', 'shoulders'],
          correctIndex: 1,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Який орган — "mouth"?',
          options: ['очі', 'рот', 'ніс', 'вуха'],
          correctIndex: 1,
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай частини тіла:",
          pairs: [
            { left: 'head', right: 'голова' },
            { left: 'nose', right: 'ніс' },
            { left: 'eyes', right: 'очі' },
            { left: 'ears', right: 'вуха' },
          ],
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади рядок пісні:',
          translation: 'Голова, плечі, коліна, пальці ніг.',
          words: ['Head', 'shoulders', 'knees', 'and', 'toes'],
          answer: ['Head', 'shoulders', 'knees', 'and', 'toes'],
        },
      ],
    },
    {
      slug: 'songs-old-macdonald',
      title: 'Old MacDonald Had a Farm',
      orderIndex: 2,
      type: 'video',
      durationMin: 6,
      xp: 12,
      sectionSlug: 'songs-animals',
      sectionTitle: 'Частина 3 · Тварини',
      sectionOrder: 2,
      topic: 'animals',
      videoUrl: 'https://www.youtube.com/embed/_6HzoUcx3eo',
      transcript:
        "Old MacDonald had a farm, E-I-E-I-O! And on his farm he had a cow, E-I-E-I-O! With a moo-moo here and a moo-moo there, here a moo, there a moo, everywhere a moo-moo! Old MacDonald had a farm, E-I-E-I-O!",
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Тварини на фермі 🐄',
          body: 'Пісня знайомить з тваринами і звуками, які вони видають англійською мовою. Ці звуки відрізняються від українських!',
          examples: [
            { en: 'cow — moo', ua: 'корова — му' },
            { en: 'pig — oink', ua: 'свиня — хрю' },
            { en: 'duck — quack', ua: 'качка — кря' },
            { en: 'dog — woof', ua: 'собака — гав' },
            { en: 'cat — meow', ua: 'кіт — няв' },
            { en: 'sheep — baa', ua: 'вівця — бе' },
          ],
          tip: '💡 В англійській свиня каже "oink", а не "хрю"! Це cultural fun fact.',
        },
        {
          id: 'video-1',
          type: 'video',
          title: 'Old MacDonald Had a Farm',
          url: 'https://www.youtube.com/embed/_6HzoUcx3eo',
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Як "каже" корова англійською?',
          options: ['oink', 'meow', 'moo', 'baa'],
          correctIndex: 2,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Яка тварина каже "quack"?',
          options: ['кіт', 'свиня', 'качка', 'собака'],
          correctIndex: 2,
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай тварину зі звуком:",
          pairs: [
            { left: 'cow', right: 'moo' },
            { left: 'dog', right: 'woof' },
            { left: 'cat', right: 'meow' },
            { left: 'sheep', right: 'baa' },
          ],
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'Old MacDonald had a ',
          after: '.',
          answer: 'farm',
          hint: 'Місце, де живуть корови і кури…',
        },
      ],
    },
  ],
};
