import type { CourseSeed } from './types';

export const wordPuzzle: CourseSeed = {
  slug: 'word-puzzle',
  lessons: [
    {
      slug: 'wp-food-challenge',
      title: 'Food Challenge',
      orderIndex: 0,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'wp-vocab',
      sectionTitle: 'Частина 1 · Словникові челенджі',
      sectionOrder: 0,
      isFree: true,
      topic: 'vocabulary-game',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Правила гри 🧩',
          body: 'У словесних пазлах ми складаємо слова й сортуємо їх за темами. У цьому раунді — тема "їжа".',
          examples: [
            { en: 'bread', ua: 'хліб' },
            { en: 'cheese', ua: 'сир' },
            { en: 'apple', ua: 'яблуко' },
            { en: 'soup', ua: 'суп' },
            { en: 'rice', ua: 'рис' },
            { en: 'chicken', ua: 'курка' },
          ],
          tip: '💡 Підказка: якщо слово починається з голосної (a, e, i, o, u) — вживай "an" замість "a". "An apple", "a banana".',
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади слово (букви переплутались):',
          translation: 'bread',
          words: ['b', 'r', 'e', 'a', 'd'],
          answer: ['b', 'r', 'e', 'a', 'd'],
        },
        {
          id: 'wo-2',
          type: 'word-order',
          prompt: 'Склади слово:',
          translation: 'cheese',
          words: ['c', 'h', 'e', 'e', 's', 'e'],
          answer: ['c', 'h', 'e', 'e', 's', 'e'],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "Категорія: Fruit vs NOT fruit — з'єднай зі значенням:",
          pairs: [
            { left: 'apple', right: 'fruit' },
            { left: 'bread', right: 'not fruit' },
            { left: 'banana', right: 'fruit' },
            { left: 'cheese', right: 'not fruit' },
          ],
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Що з переліченого — НЕ їжа?',
          options: ['rice', 'soup', 'chair', 'chicken'],
          correctIndex: 2,
          explanation: '"Chair" — стілець, це меблі. Інше — їжа.',
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'I eat ',
          after: ' apple every morning.',
          answer: 'an',
          hint: 'Перед голосною — "a" чи "an"?',
        },
      ],
    },
    {
      slug: 'wp-animals-challenge',
      title: 'Animals Challenge',
      orderIndex: 1,
      type: 'interactive',
      durationMin: 8,
      xp: 15,
      sectionSlug: 'wp-vocab',
      sectionTitle: 'Частина 1 · Словникові челенджі',
      sectionOrder: 0,
      topic: 'vocabulary-game',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Тварини 🐯',
          body: 'Раунд: тварини. Зʼєднуємо, складаємо, відгадуємо.',
          examples: [
            { en: 'lion', ua: 'лев' },
            { en: 'tiger', ua: 'тигр' },
            { en: 'elephant', ua: 'слон' },
            { en: 'monkey', ua: 'мавпа' },
            { en: 'bear', ua: 'ведмідь' },
            { en: 'zebra', ua: 'зебра' },
          ],
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади слово:',
          translation: 'monkey',
          words: ['m', 'o', 'n', 'k', 'e', 'y'],
          answer: ['m', 'o', 'n', 'k', 'e', 'y'],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай тварину з перекладом:",
          pairs: [
            { left: 'lion', right: 'лев' },
            { left: 'bear', right: 'ведмідь' },
            { left: 'zebra', right: 'зебра' },
            { left: 'elephant', right: 'слон' },
          ],
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Яка тварина має довгий хобот?',
          options: ['lion', 'tiger', 'elephant', 'zebra'],
          correctIndex: 2,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Яка тварина має чорно-білі смужки?',
          options: ['elephant', 'monkey', 'zebra', 'bear'],
          correctIndex: 2,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'The king of the jungle is a ',
          after: '.',
          answer: 'lion',
          hint: 'Цар звірів…',
        },
      ],
    },
    {
      slug: 'wp-colors-challenge',
      title: 'Colors & Shapes Challenge',
      orderIndex: 2,
      type: 'interactive',
      durationMin: 7,
      xp: 15,
      sectionSlug: 'wp-logic',
      sectionTitle: 'Частина 2 · Логіка + слова',
      sectionOrder: 1,
      topic: 'logic-game',
      steps: [
        {
          id: 'theory-1',
          type: 'theory',
          title: 'Кольори та форми 🎨',
          body: 'Поєднання кольору і форми — класична тема дитячих ігор. Ось головні слова.',
          examples: [
            { en: 'circle', ua: 'коло' },
            { en: 'square', ua: 'квадрат' },
            { en: 'triangle', ua: 'трикутник' },
            { en: 'star', ua: 'зірка' },
            { en: 'heart', ua: 'серце' },
            { en: 'purple', ua: 'фіолетовий' },
          ],
        },
        {
          id: 'match-1',
          type: 'match-pairs',
          prompt: "З'єднай форму з перекладом:",
          pairs: [
            { left: 'circle', right: 'коло' },
            { left: 'square', right: 'квадрат' },
            { left: 'triangle', right: 'трикутник' },
            { left: 'heart', right: 'серце' },
          ],
        },
        {
          id: 'mc-1',
          type: 'multiple-choice',
          question: 'Яка форма має три кути?',
          options: ['circle', 'square', 'triangle', 'star'],
          correctIndex: 2,
        },
        {
          id: 'mc-2',
          type: 'multiple-choice',
          question: 'Суміш червоного і синього — який колір?',
          options: ['green', 'purple', 'orange', 'yellow'],
          correctIndex: 1,
        },
        {
          id: 'fill-1',
          type: 'fill-blank',
          before: 'A ball is a ',
          after: '.',
          answer: 'circle',
          hint: "Кругла форма…",
        },
        {
          id: 'wo-1',
          type: 'word-order',
          prompt: 'Склади слово:',
          translation: 'purple',
          words: ['p', 'u', 'r', 'p', 'l', 'e'],
          answer: ['p', 'u', 'r', 'p', 'l', 'e'],
        },
      ],
    },
  ],
};
